### ISSUE TITLE
Add disjointness information to classes. 

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#107]
Testcase: testcases/owl2-primer/allDisjointClasses.owl

Currently this renders under class relations as follows:
![image](https://user-images.githubusercontent.com/32327979/205043766-7b3eb7d0-a22b-49ff-aff6-b68652bb8700.png)

The **Subclass of** is shown correctly. What is missing is the disjointness information.

Currently this is not shown in OLS3 either. Compare for instance [http://purl.obolibrary.org/obo/FOODON_03412115](https://www.ebi.ac.uk/ols/ontologies/foodon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFOODON_03412115) for which `AllDisjointClasses` are defined as follows:

```
<rdf:Description>
     <rdf:type rdf:resource="&owl;AllDisjointClasses"/>
    <owl:members rdf:parseType="Collection">
      <rdf:Description rdf:about="&obo;FOODON_03411220"/>
      <rdf:Description rdf:about="&obo;FOODON_03411455"/>
      <rdf:Description rdf:about="&obo;FOODON_03414901"/>
      <rdf:Description rdf:about="&obo;FOODON_03414902"/>
  </owl:members>
</rdf:Description>
```

In future, ideally this should be rendered as follows in the class relations info box for the testcase:
Have another heading like **Subclass of** but called **Disjoint with** and if `Man` is selected `Woman` should show, and when `Woman` is selected `Man` should show.

For the FOODON example, if `FOODON_03411220` is selected, under ** Disjoint with ** `FOODON_03411455`, `FOODON_03414901` and `FOODON_03414902` should show. Similar for other selections.

**Comment by henrietteharmse** [comment]
No is in fact correct! I am being silly!
What is not showing is the Disjointness, but that can be done later!

**Comment by jamesamcl** [comment]
Dataload updates are done for this. The frontend can find the IRIs in the `http://www.w3.org/2002/07/owl#disjointWith` field of the JSON.

**Comment by jamesamcl** [comment]
Implemented and working with the testcase:

<img width="1178" alt="Screenshot 2023-01-11 at 03 38 50" src="https://user-images.githubusercontent.com/454895/211712249-adbd368e-a181-49ab-8a93-95e57f47e6aa.png">

Foodon isn't loading at all in OLS4 so can't check that yet. Just working out why.

**Comment by jamesamcl** [comment]
Foodon not loading because it is invalid RDF/XML. I opened an issue:

https://github.com/FoodOntology/foodon/issues/263

**Comment by jamesamcl** [comment]
Can confirm this is fixed for foodon

<img width="1176" alt="Screenshot 2023-01-11 at 21 33 03" src="https://user-images.githubusercontent.com/454895/211922385-a8afeffb-66db-4a01-8e61-d5f0669bd6c5.png">
