### ISSUE TITLE
Information missing from Neo4J 

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#109]
- [x] - AllDisjointClasses

Testcase: testcases/owl2-primer/allDisjointClasses.owl

```
     <owl:AllDisjointClasses>
       <owl:members rdf:parseType="Collection">
         <owl:Class rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointClasses#Woman"/>
         <owl:Class rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointClasses#Man"/>
       </owl:members>
     </owl:AllDisjointClasses>
```
If this was specified per class it will look as follows:

```
    <owl:Class rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointClasses#Woman">
        <owl:disjointWith rdf:resource="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointClasses#Man"/>
    </owl:Class>
```

Looking at all the nodes and relations in Neo4J for  this ontology, I cannot see that this information is represented anywhere. If I have missed it, it will sufficient to point out where this information is in Neo4J.

- [x] AllDifferent 
Testcase: testcases/owl2-primer/namedIndividual-differentFrom.owl

```
    <rdf:Description>
        <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AllDifferent"/>
        <owl:distinctMembers rdf:parseType="Collection">
            <rdf:Description rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/namedIndividual-differentFrom#Bill"/>
            <rdf:Description rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/namedIndividual-differentFrom#John"/>
        </owl:distinctMembers>
    </rdf:Description>

```
If this was specified per individual it will look as follows:

```
    <owl:NamedIndividual rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/namedIndividual-differentFrom#Bill">
       <owl:differentFrom rdf:resource="http://www.ebi.ac.uk/testcases/owl2primer/namedIndividual-differentFrom#John"/>
    </owl:NamedIndividual>
```

- [x] AllDisjointProperties

Testcase: testcases/owl2-primer/allDisjointObjectProperties.owl

```
    <rdf:Description>
        <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AllDisjointProperties"/>
        <owl:members rdf:parseType="Collection">
            <rdf:Description rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointObjectProperties.owl#propA"/>
            <rdf:Description rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointObjectProperties.owl#propB"/>
            <rdf:Description rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointObjectProperties.owl#propC"/>
        </owl:members>
    </rdf:Description>
```
If this was specified per property, it will look as follows:
```
    <owl:ObjectProperty rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointObjectProperties.owl#propA">
        <owl:propertyDisjointWith rdf:resource="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointObjectProperties.owl#propB"/>
         <owl:propertyDisjointWith rdf:resource="http://www.ebi.ac.uk/testcases/owl2primer/allDisjointObjectProperties.owl#propB"/>
    </owl:ObjectProperty>
``

My main concern here is that if this is indeed missing, the transformation from RDF is not lossless.

**Comment by jamesamcl** [comment]
The transformation is lossless for the entities that it translates. The top levels of our translation are ontologies, classes, properties, and individuals (`owl:Ontology`, `owl:Class`, `owl:Property`, `owl:Individual`).

I think `owl:AllDisjointClasses` is completely separate so would need its own section in the output JSON.

Also: I don't think looking at Neo4j is a good way to evaluate the output of the dataload. Any of the fields that cannot be queried are munged into a `_json` field which you can't query. I would recommend looking at the JSON file that is the output of owl2json instead.

**Comment by henrietteharmse** [comment]
Yip, looked at the json as well, but that is more difficult to read. In Neo4J it was a bit easier to go through. I did not query it. I read through every node and relation.

**Comment by henrietteharmse** [comment]
It is important information, perhaps not for now but definitely something to add.

**Comment by jamesamcl** [comment]
That’s fine if you find it easier to read - BUT it does not contain all of the information we have available in the API and frontend. Those are contained in the _json field which is a string/blob. So all you can really see in Neo4j are the fields you can use in Cypher queries which is a subset of our actual data representation.

for example: class expressions are not present in the neo4j or solr schemas but you still get them in the json in the api and frontend

**Comment by henrietteharmse** [comment]
Back to the issue: `owl:AllDisjointClasses` contains important information about owl:Classes. This should be part of the transformation. Without this information we are loosing important information about the ontology.

**Comment by jamesamcl** [comment]
Dataload updates are done. Just needs to be added to the frontend now.
