### ISSUE TITLE
Tree navigation gets "stuck"

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#110]
Testcase: testcases/owl2-primer/equivalentClass.owl

How to reproduce:
![image](https://user-images.githubusercontent.com/32327979/205271507-9252aed3-3485-42f6-9985-d640264c3086.png)

Click on either of the 2 classes, say `Human`.
![image](https://user-images.githubusercontent.com/32327979/205271780-7540786f-77ea-4ba4-9123-5dbaf4809ba8.png)

Now there is no way to see the rest of the tree again. Clicking 
![image](https://user-images.githubusercontent.com/32327979/205272071-2ffabc84-6dac-46e5-b49f-e9324233fc2d.png) does not help either. The only way is to press the browser back button.

This is where show siblings feature may be helpful.

**Comment by serjoshua** [comment]
This is a good use case.
