### ISSUE TITLE
Add DifferentFrom information to Individuals

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#113]
Testcase: testcases/owl2-primer/namedIndividual-differentFrom.owl

Under **_Individual Relations_** we should have a **Different from** subheading. This should list all individuals the current selected individual is different from. I.e., in the example, when `Bill` is selected, `John` should be listed as a different individual.

A concrete example is from IAO is:
```
    <rdf:Description>
        <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AllDifferent"/>
        <owl:distinctMembers rdf:parseType="Collection">
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000226"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000227"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000228"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000229"/>
        </owl:distinctMembers>
    </rdf:Description>
```

**Comment by jamesamcl** [comment]
In the frontend these can be found in the `http://www.w3.org/2002/07/owl#differentFrom` field of the JSON.
