### ISSUE TITLE
Ontology IDs are vertical in safari

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#132]
<img width="729" alt="Screenshot 2022-12-15 at 02 30 11" src="https://user-images.githubusercontent.com/454895/207758401-009639af-2e3c-4b4d-b270-4af0dc2d470a.png">

**Comment by jamesamcl** [comment]
They also wrap in chrome

<img width="630" alt="Screenshot 2022-12-15 at 02 31 01" src="https://user-images.githubusercontent.com/454895/207758487-5fe7186a-e43e-4e63-9e99-4fa69a8e26a4.png">

I don't think IDs should ever wrap

**Comment by serjoshua** [comment]
I expect the wrapping happening, I could update it but I cannot seem to replicate the vertical thing in Safari. Any replication steps or you just randomly accessed the page?
