### ISSUE TITLE
Implement the Help and About pages in the frontend

### ISSUE THREAD

**Issue by udp** [EBISPOT/ols4#14]

**Comment by serjoshua** [comment]
This has been handled by commits starting from https://github.com/EBISPOT/ols4/commit/bd4706954c0a3f5283809b7203f42366c5cbb35e, https://github.com/EBISPOT/ols4/commit/fcb46790d079e5cb3744c1e113b7c19fcd210b48 and more.

For any discrepancies or updates related to these pages, feel free to raise a ticket.
