### ISSUE TITLE
Label different for predicate OLS3/OLS4

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#152]
OLS3: https://www.ebi.ac.uk/ols/api/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBTO_0000164
OLS4: https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBTO_0000164

OLS3 uses `bearer_of` for `RO_0000053` while OLS4 uses `has_characteristic`. They are both specified for `rdfs:label`. Maybe OLS4 needs to alphabetically sort the label list before choosing a label.

**Comment by matentzn** [comment]
Deterministic is a definitely a good idea for this. Another option is trying to use the _correct_ label. The correct label is the label that the entity (property, class, etc) has in the ontology it _belongs_ to. This requires keeping track of _base-iris_, which allow to identify membership of an IRI in an ontology. Not without effort, just throwing it in there. Sorting is probably the easier fix for now.

**Comment by jamesamcl** [comment]
@matentzn The ultimate conclusion to that line of reasoning is that if an ontology includes entities outside its base IRI, we shouldn't index those terms at all, instead just linking to the authoritative ones (if they are indexed). I know we have discussed that in the past and would be very interested to revive the discussion -

BUT if we do it I think we should do it and completely remove the duplicated entities. I don't think we should have a situation where we use some bits from the ontology that imported the term and some bits from the upstream ontology because that would be potentially very confusing.

I think we either completely trust the downstream ontology's version of the entity, or we completely ignore it.

**Comment by matentzn** [comment]
You are right @udp and I dont think using the external representation of the entities is worth the cost (especially the social cost - there will be an uproar). That's why probably sorting is the safer path for now..

**Comment by jamesamcl** [comment]
OLS4 does sort the list so very little we can do about this.
