### ISSUE TITLE
OLS home page search should allow for multilang searches

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#158]

**Comment by jamesamcl** [comment]
Currently the only thing stopping this is that the `&lang=` parameter defaults to `en` in the API. We could fix by allowing `&lang=all` in which case no language is used in the solr search.

**Comment by jamesamcl** [comment]
Looking good - using the SCDO example provided to us a while back.

<img width="679" alt="Screenshot 2023-01-18 at 05 47 36" src="https://user-images.githubusercontent.com/454895/213094202-ca385e0e-54fc-46d5-8556-c0da354e4501.png">
