### ISSUE TITLE
owl:equivalentClass

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#159]
`A equivalentClass B` implies `A subClassOf B` and `B subClassOf A`. We need to handle this in `RelatedAnnotator`.

Also, does this apply to the parents/children lists in OLS3?

**Comment by jamesamcl** [comment]
<s>Also if `A equivalentClass B` then `B equivalentClass A`, but the OWL file might just have `A equivalentClass B` and expect us to infer the reverse (the reasoner does not add this information).</s>

owl2json now adds these

**Comment by matentzn** [comment]
Is OLS going again to support reasoner and no-reasoner options for sources? I would recommend to focus on getting people to publish ontologies into an appropriate asserted structure..

**Comment by jamesamcl** [comment]
No we don't do any reasoning at all

**Comment by matentzn** [comment]
Ok missing context on this issue then! Thanks for clarifying!

**Comment by jamesamcl** [comment]
Because we don't use a reasoner we need to manually interpret some things like owl:equivalentClass implying subClassOf relationships. Because things are annoyingly left implicit in the OWL RDF spec, and even though we expect ontlogies to be reasoned before OLS4 loads them, the reasoner doesn't add the explicit information either.

**Comment by matentzn** [comment]
Ok! I just didnt realise this mattered to rendering the hierarchies (I assume that is what it is needed for, determining what do do when A=B in the tree view), but I guess it does!

**Comment by jamesamcl** [comment]
Neither did we !!!
