### ISSUE TITLE
String literal IRIs

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#166]
IRIs should be IRIs, not string literals. But unfortunately they are often string literals!

It is tempting to ignore this and let the ontologies fix it but I think we should do a best effort. We can look at string literal values and if they are the IRI of an entity in the ontology, include the referenced entity in `referencedEntities`.

We can then do something similar in the frontend to replace the IRI with a label and a link.

**Comment by cthoyt** [comment]
Parsing arbitrary IRIs into human-readable CURIEs with canonical links is another feature of the Bioregistry. It would be great to try and turn IRIs that are both hard to read and hard to contextualize for the standard user of the OLS into nice CURIEs for display on the site.

I added a stub implementation in #175

**Comment by jamesamcl** [comment]
We now have the linker which looks at all strings to see if they are the IRI of an entity defined in any ontology.
