### ISSUE TITLE
(After OLS4 release) - Cross-ontology label resolution

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#173]
Term: https://www.ebi.ac.uk/ols/ontologies/EFO/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0007126

OLS3:

<img width="553" alt="Screenshot 2023-01-14 at 04 08 50" src="https://user-images.githubusercontent.com/454895/212449993-2b1c2475-5d12-49e6-9310-7aba909cb429.png">

OLS4:

<img width="607" alt="Screenshot 2023-01-14 at 04 09 06" src="https://user-images.githubusercontent.com/454895/212450001-26ed3932-b0ec-401b-9865-4b1e81f3315e.png">

We are getting much closer to turning things into links. Now we just need to deal with IRIs which are part of other ontologies, like the exact matches above. The problem is that we load ontologies one at a time, in blissful ignorance of any of the other ontologies we are loading.

We can draw some inspiration from how the compilers of old worked/work. They compile each source file into an object file, then there is a linker stage which links the object files together. We could introduce a **linker** application which processes the owl2json output.

I see it like this:

* `owl2json` would no longer create the `referencedEntities` field. Currently, it populates this based on (a) links in the current ontology and (b) xrefs from go's xref file and bioregistry.

* Instead, there would be another `linker` application which would add `referencedEntities` to every entity. The linker would have access to all of the ontologies at the same time. It would therefore populate the field based on (a) links in the current ontology; (b) links across ontologies; and (c ) xrefs from go's xref file and bioregistry, as above.

* We would rename `referencedEntities` to `linkedEntities` to, uh, link them back to the linker !!

**Comment by jamesamcl** [comment]
The output of owl2json is a 40 GB JSON file. Though we would be able to load this into memory on the EBI cluster, one of the design goals of OLS4 is to run on hardware available to regular humans wherever possible, so we shouldn't assume the linker can just load everything.

Some random thoughts on a possible algorithm:

1. Scan through the JSON and make two maps:
    1. ontology ID -> (file offset in the JSON to read just that single ontology, ontology size)
    2. IRI -> set of ontology IDs that define that IRI. If any of the ontologies have `isDefiningOntology` true then keep only that ontology ID. Otherwise keep them all.
2. Scan through the JSON again and make a map (ontology ID -> referenced ontology ID) using O(1) lookups in the map (ii) above
3. Scan through the JSON again.
    1. For each distinct set of ontology IDs from step (2) load the referenced ontologies using map (i) from the first step.  
    2. For each ontology that requires the above set, output the ontology, linking as we go using O(1) lookups in maps (ii) then (i) from the first step

**Comment by cthoyt** [comment]
Might be useful to merge forces here. I've written a generic pipeline for a creating ID -> label database that is also usable for non-ontology resources: https://zenodo.org/record/4660694

This is deployed in the Biolookup service: http://biolookup.io/. I don't think our little deployement could handle the load from OLS but it's possible to deploy this yourself and hit your own endpoint that's got load balancing

**Comment by jamesamcl** [comment]
Thanks Charlie,

we now already have something lined up for this in another branch. The constraints with OLS are the number of terms (6 million+) and that everything has to be materialised once as part of the dataload in the OLS databases: we can't just hit an API at query time otherwise we wouldn't be able to know the labels/what is a link to render the pages.

Having said this I definitely want to make sure that our outward links are as high quality as possible. The Bioregistry integration is an excellent step in this direction and I'm sure there's a lot more we can do.
