### ISSUE TITLE
ols4 is missing in several links

### ISSUE THREAD

**Issue by rombaum** [EBISPOT/ols4#183]
At the moment at least the links of the actions, the breadcrumbs and the (class) relations are not correct. In all of them "ols4" is missing in the path of the hyperlink.

**Actions**
![actions](https://user-images.githubusercontent.com/47030738/214310597-99998e0e-59e2-4cd7-9081-7182bda79c0f.png)
source: https://www.ebi.ac.uk/ols4/ontologies

**Breadcrumb**
![readcrumb](https://user-images.githubusercontent.com/47030738/214310066-87eddb57-c89a-47ab-85fa-64ff132f8597.png)
**class relations**
![Auswahl_116](https://user-images.githubusercontent.com/47030738/214310094-1f81ee08-a5f0-4a7f-ae00-fb47fb3b3c54.png)
source: https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000400

**Comment by jamesamcl** [comment]
Thanks, fixed!
