### ISSUE TITLE
/api/search endpoint missing

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#185]
Compare for instance with OLS 3:

https://www.ebi.ac.uk/ols/api/search?q=liver
https://www.ebi.ac.uk/ols/api/search?q=humeroradial%20synostosis&queryFields=label&exact=true&ontology=efo,mondo,doid,mp&local=true

**Comment by jamesamcl** [comment]
It's implemented but testing required. Closing in favour of #209
