### ISSUE TITLE
MI ontology does not load

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#186]

**Comment by jamesamcl** [comment]
The dataload works; seems to be a frontend js error

**Comment by jamesamcl** [comment]
seems fine now 

<img width="1582" alt="Screenshot 2023-01-29 at 03 45 20" src="https://user-images.githubusercontent.com/454895/215303689-8d74a85a-d6d6-4dd7-bcc4-c2dd2656a2e1.png">
