### ISSUE TITLE
OLS4 search feedback

### ISSUE THREAD

**Issue by helenp** [EBISPOT/ols4#191]
Searching for myocardial infarction in OLS3 vs OLS4 striking differences in the quality of results:
OLS3 - first 7 hits are a lexical match.
OLS4 - the lexical match to query isn't in the first two pages.

Also the query autocomplete is less intuitive:
OLS3  - first autocomplete for myocardial infa... has 2 precise and three minor variations on the input term

In OLS4 autocomplete is 'family history of myocardial...'
Suggests the search ranking is performing differently. As a user of the GUI I want precision vs. my search term before recall in all search cases - I'll scroll to get to less precise results.

**Comment by jamesamcl** [comment]
Thanks Helen - we are aware of this (issue #99 though you provided much more detail than I did). Basically we haven't implemented the list of boost values for the different search fields properly, but should be fixed soon.

**Comment by helenp** [comment]
Thanks for the update.

**Comment by jamesamcl** [comment]
This seems resolved now. Searching for "myocardial infarction":

<img width="809" alt="Screenshot 2023-02-09 at 11 44 17" src="https://user-images.githubusercontent.com/454895/217803814-255686f4-bd59-4ec8-a372-fbbdd0405881.png">

Searching for "myocardial infa":

<img width="820" alt="Screenshot 2023-02-09 at 11 44 46" src="https://user-images.githubusercontent.com/454895/217803938-783e2a3b-2979-40d5-9cb0-da487a48ae4c.png">
