### ISSUE TITLE
Main search does not seem to work for short forms like NCIT:C9305

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#198]
Compare OLS 3
![image](https://user-images.githubusercontent.com/32327979/216625101-07229d10-f97f-4e68-99d7-329f375fdce3.png)

to OLS4
![image](https://user-images.githubusercontent.com/32327979/216626209-2ee0b7d6-66fc-4718-8bcb-e4397136a418.png)

Note that for OLS 3 NCIT related terms are listed while for OLS4 Mondo terms are listed.

**Comment by serjoshua** [comment]
Noticed this as well before. I usually swap the colon (:) with the underscore (_) to get what I need.

**Comment by jamesamcl** [comment]
I think : is not being escaped properly in the solr query

**Comment by jamesamcl** [comment]
This is fixed but needs a dataload.
