### ISSUE TITLE
Short forms should be CURIEs (: delimited) rather than _ delimited short forms

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#202]
See for example the orange boxes here:

<img width="800" alt="Screenshot 2023-02-09 at 11 47 20" src="https://user-images.githubusercontent.com/454895/217804487-726822e1-d5b3-49c6-a208-0c56888e178e.png">

**Comment by jamesamcl** [comment]
Currently we have two fields: `oboId` which is `:` delimited, and `shortForm` which is `_` delimited. These were inherited from OLS3. Perhaps they should be merged into a single : delimited `curie` field.

**Comment by matentzn** [comment]
Short_form should die an agonising death

**Comment by jamesamcl** [comment]
Will be fixed after next dataload
