### ISSUE TITLE
Class count in header does not match count in tree

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#204]
40,315 vs. 34,468. Not sure which one is correct or why they are different.

<img width="537" alt="Screenshot 2023-02-09 at 21 30 16" src="https://user-images.githubusercontent.com/454895/217943515-aa70a5b4-5643-41bb-8665-6841ead1eb17.png">

**Comment by jamesamcl** [comment]
Protegé shows 40,316 which I assume is the count from the header + `owl:Thing`. So our tree count seems to be missing some. Possibly the obsolete classes which aren't included in the tree.

**Comment by matentzn** [comment]
6K obsolete classes sounds too much :)

**Comment by jamesamcl** [comment]
Current EFO shows 40458 in the header, 34571 in the tree.

Querying https://www.ebi.ac.uk/ols4/api/v2/ontologies/efo/classes?isObsolete=true returns 5886 obsolete classes.

34571 + 5886 = 40457

+1 for owl:Thing = 40458.
