### ISSUE TITLE
Spaces after links on homepage

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#208]
Not sure what's going on here - I used the same class as other links? @serjoshua 

<img width="382" alt="Screenshot 2023-02-09 at 22 51 54" src="https://user-images.githubusercontent.com/454895/217957078-95a7e03c-aecf-45a1-b8da-2e14be8a4ad3.png">

**Comment by serjoshua** [comment]
HTML doesn't read whitespaces and newlines well. They always have to be inside a tag <></>. In your code, if there is a newline, it is automatically an empty string. If there are multiple whitespaces, they are displayed as a singular whitespace. To force HTML to display a whitespace outside a non-breaking tag, you need to use an HTML entity: `&nbsp;`. Try it! 😄

**Comment by serjoshua** [comment]
By the way, if you intend to force display just a regular breaking space, you could also use `&thinsp;` or `&ensp;`. Depending on how narrow you like it. I find the narrower _thinsp_ better with our IBM Plex Sans font.

**Comment by jamesamcl** [comment]
On the contrary - HTML collapses multiple spaces to a single space and has done since the 90s. JSX however does not, and your fix would have added non blocking spaces where they were not necessary. Fixed by adding `{' '}` to inject space text into the JSX.
