### ISSUE TITLE
Only OWL classes should be labelled as Ontology terms

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#21]
Currently individuals and properties are labelled with the OntologyTerm label in Neo4J, though only classes should be labelled with OntologyTerm.

The best reference I can find for the meaning of term in the biological community is the [OBO flat file spec](http://www.cs.man.ac.uk/~horrocks/obo/#2.3). This clearly states that only OWL classes are terms.

The use of the word "term" in OLS 3 has been a bit inconsistent. On the frontend OWL classes are terms, properties are properties and individuals are individuals. In the codebase this is a bit more fluid with both OWL classes and OWL properties being referred to as terms. This may have slipped in as part of copying and pasting code.

For completeness the OWL vs OBO spec mapping is as follows:

1. OWL class --> OBO term
2. OWL property --> OBO typedef
3. OWL individual --> OBO instances

**Comment by udp** [comment]
In that case I think we should drop the word Term completely. Because it would be on exactly the same objects as Class and therefore of no use to OLS for querying.
