### ISSUE TITLE
"Also defined in" going wild

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#220]
<img width="1744" alt="Screenshot 2023-02-20 at 02 05 24" src="https://user-images.githubusercontent.com/454895/219992487-81359d98-cb30-4575-80bd-cf63e271eb8c.png">

**Comment by jamesamcl** [comment]
Shouldn't be listed when "defined by" is present.

**Comment by matentzn** [comment]
Maybe "used in" instead of defined by as a seperate section is interesting information regardless!
