### ISSUE TITLE
<s>definedIn</s> appearsIn

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#222]
The definedIn arrays are very large, and in the case of linked terms aren't actually used anyway.

EFO:0000400

<img width="1380" alt="Screenshot 2023-02-21 at 22 17 15" src="https://user-images.githubusercontent.com/454895/220471137-e91249ba-40ac-4067-9cb7-4a6ad438353b.png">

We should probably instead populate definedBy if there is only 1 defining ontology, and get rid of definedIn. We can still support searching for which ontologies a term is defined in using solr so no functionality is lost, but materialising definedIn for all linked entities is making the DBs very large for no reason.

**Comment by jamesamcl** [comment]
If there is no definedBy, we could populate a numDefinedIn instead. Then clicking the link would take you to a disambiguation page where you can select from the ontologies in which the term is defined.

**Comment by jamesamcl** [comment]
I was thinking for each Entity:

`definedBy: [ ... ]`
`definedIn: [ ... ]`

And for each `linkedEntities` entry:

`definedBy: [ ... ]`
`hasLocalDefinition: <boolean>`
`numDefinedIn: <num>`

This way we can keep the "Defined by" and "Also defined in" lists on the entity page without any changes.

For entity links it would get, uhhhhh, very complex. I worked through the cases I think we would need to cover:

<img width="1607" alt="Screenshot 2023-02-21 at 23 35 37" src="https://user-images.githubusercontent.com/454895/220482976-3467bc43-1ba2-45bb-b572-86888bc1361d.png">

There might be a simpler way to approach this I guess? but the complexity of having potentially multiple canonical definitions AND/OR multiple other definitions AND/OR definitions within the current ontology means there are quite a few possibilities. I think it's worth it to turn everything we possibly can into a link though.

Where I wrote `<ICON>` to link to a disambiguation page, I'm not totally sure what to use to convey "search for definitions of this term". Possibly something like this (fontawesome)? I feel like just a search icon doesn't convey very well that there are DEFINITELY results and you are just choosing from one, whereas this somehow conveys both search and navigation.

<img width="141" alt="Screenshot 2023-02-21 at 23 42 51" src="https://user-images.githubusercontent.com/454895/220483916-1cf090ba-8f71-485f-a174-751aa2d2f3d9.png">

**Comment by jamesamcl** [comment]
Linker changes pending checking after indexing on the cluster

**Comment by jamesamcl** [comment]
definedIn is now called appearsIn. So the two properties are:

- `definedBy`: ontologies which are the canonical defining ontology for the IRI
- `appearsIn`: ontologies which provide a definition for the IRI, but are not the canonical defining ontology

where "canonical defining ontology" is established by `base_uri` from the config.

**Comment by matentzn** [comment]
I think this makes sense. Check if rdfs:definedIn, else go via base-iri config. Report appears in. Yes!

**Comment by jamesamcl** [comment]
This is deployed now! Will open more specific issues if anything arises.
