### ISSUE TITLE
Display errors in frontend

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#224]
Currently if there's e.g. a 404 the frontend just hangs indefinitely

Should show an error instead

**Comment by jamesamcl** [comment]
@serjoshua maybe you know a way to do this easily with redux?

**Comment by serjoshua** [comment]
This has now been handled by some of our previous commits like
https://github.com/EBISPOT/ols4/commit/d571e402286535552e3c0690ea6fe07d60d47257 and https://github.com/EBISPOT/ols4/commit/19394961798d3ab9a5bdc7519fa62aada83c0379.

For any discrepancies or errors that hasn't been handled, feel free to raise a ticket.
