### ISSUE TITLE
"Related from" heading redundant?

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#231]
Possibly the headings should just be "disease arises from feature" and "is_about".

<img width="351" alt="Screenshot 2023-02-28 at 02 09 05" src="https://user-images.githubusercontent.com/454895/221734713-79c57af8-7163-43ef-874a-caf53f548def.png">

**Comment by matentzn** [comment]
Wow I didn't realise you were showing related from stuff from other ontologies! Just be careful you have something in place for classes that are used by thousands of other classes?

**Comment by jamesamcl** [comment]
We’re actually not - these relations are defined within EFO, they just use MONDO and OGMS terms. It would be quite easy to do that though. Maybe a toggle.

**Comment by matentzn** [comment]
I didn't mean to make a feature request for now :D

**Comment by jamesamcl** [comment]
Actually the "Related to" heading would be redundant. "Related from" is in the opposite direction so needs a heading.
