### ISSUE TITLE
Filter non-defining ontologies from search results

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#232]
e.g. these results seem a bit excessive when we already know GO is the defining ontology

<img width="1695" alt="Screenshot 2023-02-28 at 02 34 06" src="https://user-images.githubusercontent.com/454895/221738525-9971f8c0-a34c-45c2-a5f0-ff8ec987b980.png">

**Comment by jamesamcl** [comment]
(Maybe original proposal was a bit too strong - not suggesting removing the results, just a filter option for is defining)

**Comment by matentzn** [comment]
I agree a lot!

**Comment by jamesamcl** [comment]
semi duplicate of #233
