### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#238]
Based on email from Helen:

Individual Resource pages - make sure resources you manage have licensing details displayed prominently, are unambiguous (eg don't refer to EBI general terms of use in one place and cc0 in another) and are up to date. https://www.ebi.ac.uk/licencing has some boilerplate text on licensing to reuse if required - by end of March

**Comment by jamesamcl** [comment]
I don't think CC0 is recommended for code. The license in the OLS3 repo https://github.com/EBISPOT/OLS/blob/dev/LICENSE is Apache 2.0.

**Comment by jamesamcl** [comment]
@serjoshua has a nice footer implementation in OXO2 we should add to OLS4

**Comment by serjoshua** [comment]
Merged initial changes to `dev` branch. I haven't deployed anything to any environments. Feel free to play around with it. I don't think I have plenty of sample pages in my local to test the footer to.

**Comment by jamesamcl** [comment]
One thing about OLS is that most of the content it displays has nothing to do with EBI. We should probably make that clear in the footer?

**Comment by serjoshua** [comment]
Ooh. If we have an existing verbiage we could copy or something, that would be great. I also noticed some of the footers of our tools in production are cluttered with links and info. Maybe there is an existing behavior we could pattern as well.
