### ISSUE TITLE
OBI Classes tree shows only Thing and nothing else

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#239]
![image](https://user-images.githubusercontent.com/32327979/222172060-2f91cbaa-62a3-4ab0-893a-96369ce29d82.png)

**Comment by jamesamcl** [comment]
The API is returning lots of classes. Must be a frontend tree issue.

**Comment by jamesamcl** [comment]
The fix was to exclude owl:Thing from the tree, as it's not actually defined by the ontology so we have no metadata for it. I'm still not sure why this only affected OBI but I've lined up a fix anyway.
