### ISSUE TITLE
owl:propertyChainAxiom

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#240]
I spotted this in RO

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/RO_0002204">
        <rdfs:subPropertyOf rdf:resource="http://purl.obolibrary.org/obo/RO_0002330"/>
        <owl:inverseOf rdf:resource="http://purl.obolibrary.org/obo/RO_0002205"/>
        <rdfs:domain rdf:resource="http://purl.obolibrary.org/obo/BFO_0000004"/>
        <rdfs:domain>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/BFO_0000031"/>
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/BFO_0000040"/>
                </owl:unionOf>
            </owl:Class>
        </rdfs:domain>
        <rdfs:range rdf:resource="http://purl.obolibrary.org/obo/BFO_0000002"/>
        <rdfs:range>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/BFO_0000031"/>
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/BFO_0000040"/>
                </owl:unionOf>
            </owl:Class>
        </rdfs:range>
        <owl:propertyChainAxiom rdf:parseType="Collection">
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/RO_0002512"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/RO_0002510"/>
        </owl:propertyChainAxiom>
        <obo:IAO_0000114 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000125"/>
        <obo:IAO_0000115>definition &quot;x has gene product of y if and only if y is a gene (SO:0000704) that participates in some gene expression process (GO:0010467) where the output of that process is either y or something that is ribosomally translated from x&quot;</obo:IAO_0000115>
        <obo:IAO_0000116>We would like to be able to express the rule: if t transcribed from g, and t is a noncoding RNA and has an evolved function, then t has gene product g.</obo:IAO_0000116>
        <obo:IAO_0000117 xml:lang="en">Chris Mungall</obo:IAO_0000117>
        <rdfs:label xml:lang="en">gene product of</rdfs:label>
    </owl:ObjectProperty>

We don't handle `owl:propertyChainAxiom` at all at the moment.

**Comment by matentzn** [comment]
Displaying these would be amazing!!

**Comment by jamesamcl** [comment]
Displaying them isn't a problem (would only require a frontend change) but how do you think we should label it in the UI?

I feel like a heading "Property chain" with a list of properties would be OWL jargon and wouldn't convey much meaning?

**Comment by jamesamcl** [comment]
"Equivalent to chain"?

**Comment by jamesamcl** [comment]
This is implemented now (pending tonight's data release):

<img width="1606" alt="Screenshot 2023-03-02 at 00 52 41" src="https://user-images.githubusercontent.com/454895/222302564-17022142-dda8-4fbf-9ae4-ae06e428515c.png">

Clearly issues with "also appears in" are still present (#235) and can argue about nomenclature for property chains later.

**Comment by matentzn** [comment]
I think your property chain solution is great!
