### ISSUE TITLE
Colour scheme consistency

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#244]
Not at all important for release, but wanted to open an issue while I'm thinking about it. There are three main colours in the OLS4 UI:

1. A kind of off-green (reminiscent of the Windows 95 default background colour - but let's call it "OLS green"). It's used for most of the UI including buttons, highlights, and **ontology IDs**
2. Orange, used for three random icons on the homepage which should probably be OLS green; but also for all **entity IDs**
3. Blue, used in the OLS logo, checkboxes, and links4. 

<img width="1058" alt="Screenshot 2023-03-06 at 02 50 24" src="https://user-images.githubusercontent.com/454895/223008311-213c507e-4c31-453b-8c94-dcaf5c9bcfb4.png">

I really like that we have a colour coded distinction between ontologies (OLS green) and entities (orange). I think we could potentially take this further by using the orange colour palette for entity-related parts of the UI. Notice in this screenshot that the only orange is the term ID at the top:

<img width="1068" alt="Screenshot 2023-03-06 at 02 53 36" src="https://user-images.githubusercontent.com/454895/223008721-e4e15d03-538f-4ce5-ab44-5427dd146265.png">

We could change the tree/graph buttons to be orange, as they are entity related (I would mock up but I don't have photoshop at the moment).

It would also make a lot of sense on the ontology page. The "Classes" tab highlight could be orange, and the tree/list buttons:

<img width="1067" alt="Screenshot 2023-03-06 at 02 54 46" src="https://user-images.githubusercontent.com/454895/223008891-77067bc8-6236-4924-a2a6-9f30fae0e86b.png">

**Comment by serjoshua** [comment]
Anything ontology: default green color
Anything entity: default yellow/orange color

**Comment by serjoshua** [comment]
Nice-to-have: change OLS logo color to default green, which relates to issue #33
