### ISSUE TITLE
Metadata about identifiers from non-ontology datasets e.g. ORCID

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#252]
Low priority but for example in PCL:

<img width="1318" alt="Screenshot 2023-03-08 at 23 35 19" src="https://user-images.githubusercontent.com/454895/223877042-c5c6df3e-393a-4d3b-8a4a-76533de1b04a.png">

The orcids should be replaced with the author name + orcid logo linking to their orcid. We can do this in the linker using the orcid data file:

https://orcid.figshare.com/articles/dataset/ORCID_Public_Data_File_2022/21220892

**Comment by jamesamcl** [comment]
Should also do the same for pubmed IDs, DOIs, ...

Pubmed IDs: need to convert the pubmed XML into some citation format; is there a Java library for this?

DOIs: not sure where to get the data dump

**Comment by jamesamcl** [comment]
ISBN

edit: seems difficult as there is no freely available ISBN metadata dump

**Comment by jamesamcl** [comment]
The problem is we can't hit APIs for every single identifier we come across as part of the dataload because it would take days. We therefore need to use metadata extracted from the data dumps ahead of time.

I've implemented this for ORCIDs as a test. We populate leveldb (a very fast embedded key->value store that scales to billions of entries) using the ORCID dataset, so we end up with a LevelDB (which just exists in a folder, it has no server) that has every extant ORCID->{author metadata}, which only takes a couple of hours (but only needs to happen every now and then, not for every OLS data release). The code to populate this is in `dataload/extras/orcid2level`.

Then the OLS linker has a new (optional) option `--leveldbPath`. If it can't find a link for the string in the ontologies or bioregistry AND a leveldb path is provided, it queries leveldb.

All of ORCID (15 million entries) takes up about 500 MB on disk. This should easily scale to add all of pubmed etc. and we can just add new loader programmes as necessary. They will always be completely optional and are not expected to be part of most OLS deployments. Equally it would be easy for others deploying OLS to populate leveldb with some metadata about another datasource. The value mapping is a simple JSON object gets added verbatim to `linkedEntities` by the linker and can then be displayed by the frontend.

**Comment by matentzn** [comment]
In a number of our ontologies we use https://github.com/cthoyt/orcidio

In case this is interesting. This at least gives readable names!

**Comment by jamesamcl** [comment]
ORCIDs are now displayed as names (see contributor in bottom right)

<img width="1681" alt="Screenshot 2023-04-12 at 22 38 31" src="https://user-images.githubusercontent.com/454895/231591746-0cf0e9be-1f22-4662-8c97-4036ee318437.png">
