### ISSUE TITLE
Clicking OLS logo should take you home

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#253]
Currently it just seems to refresh the page.

**Comment by serjoshua** [comment]
We might need some replication steps. I tried navigating around and then clicking the logo and it does go back to home. I double-checked the code and the hyperlink tag points to home as well.

**Comment by jamesamcl** [comment]
Yes it seems like it worked on some pages but not others. I fixed it by adding a trailing slash to the link (in my branch). will merge tomorrow
