### ISSUE TITLE
owl2primer testcase issues

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#254]
- [x] dataProperty-functional.owl `hasAge` does not show _functional_ characteristic. See Protege screenshot:
![image](https://user-images.githubusercontent.com/32327979/223981651-96f43506-1c9d-48a6-abd4-66b7ba144ea3.png)

- [x] dataProperty-hasKey.owl & objectProperty-hasKey.owl: Does not show _Target for key_ information. See Protege screenshot:
![image](https://user-images.githubusercontent.com/32327979/223984181-eef51c0d-6b4b-4555-82ab-47eb953399d6.png)

- [x] datatypes.owl: _Domain_ and _Range_ not showing. See Protege 
![image](https://user-images.githubusercontent.com/32327979/224019601-e2ddc91b-90d1-4063-b123-d97d89fff866.png)

- [x] disjointUnionOf.owl: _Disjoint Union of_ not showing. See Protege
![image](https://user-images.githubusercontent.com/32327979/224032913-4786a9be-3a67-4e40-9994-99eaae1eb1da.png)

- [x] objectProperty-inverse-withoutAssignedName.owl: You can apply inverse to a property without actually creating a new property. See Protege:
![image](https://user-images.githubusercontent.com/32327979/224108040-3bb7e52e-5da7-4052-859f-74dca3ca840b.png)
and what it looks like in OLS: 
![image](https://user-images.githubusercontent.com/32327979/224108599-b993af63-eb34-455a-b0f4-a41beffaa11e.png)

- [x] Individuals are not displayed when they do not have a type. See datatypes.owl and namedIndividual.owl.
![image](https://user-images.githubusercontent.com/32327979/224294918-1b886be5-6964-481f-ba72-8ae9005300b8.png)

- [x] objectProperty-negativePropertyAssertion.owl: Negative objectAssertions do not show up.
![image](https://user-images.githubusercontent.com/32327979/224297738-f6f88cdb-843d-4cb3-9115-78a3784cd0e6.png)

- [x] propertyRestriction-cardinality.owl, propertyRestriction-qualifiedCardinality.owl, propertyRestriction-minQualifiedCardinality.owl, propertyRestriction-maxQualifiedCardinality.owl, : Cardinality exact, min and max restrictions on type not showing. 
![image](https://user-images.githubusercontent.com/32327979/224301599-e870e190-c1e7-4d1f-936a-662ccf5a4f26.png)

- [x] class-expression-based-on-datatype-restriction.rdf - Protege 
![image](https://user-images.githubusercontent.com/32327979/224782784-ad93cc17-205e-4bb6-8340-ebdcedf1b7ca.png)
vs OLS 4
![image](https://user-images.githubusercontent.com/32327979/224782913-67ce1afb-216a-4668-bcf6-65db5b03ed6d.png)

**Comment by jamesamcl** [comment]
Need to check these in OLS3 to see if they are new features for the paper.

**Comment by henrietteharmse** [comment]
@udp  Be careful to not delete the tasks I have added! :-)

**Comment by henrietteharmse** [comment]
That is the last for now.
