### ISSUE TITLE
Separate text definitions as new paragraphs

### ISSUE THREAD

**Issue by ghost** [EBISPOT/ols4#260]
Currently, for classes with more than one text definition, those text definitions are displayed in OLS as concatenated strings with no separation between them.

Protégé:
<img width="458" alt="Screenshot 2023-03-10 at 09 20 24" src="https://user-images.githubusercontent.com/95643797/224277453-3b8e894c-a60d-413b-b4d5-a2d5e597d7a5.png">

OLS:
<img width="721" alt="Screenshot 2023-03-10 at 09 22 00" src="https://user-images.githubusercontent.com/95643797/224277404-30d11052-1acc-4330-949b-d0618374c73b.png">

In the current example, the class 'diabetes mellitus' has 3 text definitions, 2 of which are the same. OLS appears to at least deduplicate the redundant text definition. It would also be beneficial for viewers to see separation between the 2 distinct text definitions, at least with a white space, ideally with a new paragraph.

**Comment by jamesamcl** [comment]
Thanks for the detailed report!
