### ISSUE TITLE
graph view has the licence bar superimposed in the middle of the screen

### ISSUE THREAD

**Issue by helenp** [EBISPOT/ols4#261]
presume it should be moving when scrolling but it remains in the middle of the screen when I scroll
e.g.https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000091

**Comment by jamesamcl** [comment]
Thanks Helen - we have a fix lined up for this which should be deployed today.
