### ISSUE TITLE
Facet to filter ontologies

### ISSUE THREAD

**Issue by rsmsheriff** [EBISPOT/ols4#265]
A minor comment, it is my personal opinion, I miss the facet that allows one to search for the Ontology, let say I can choose UBERON and restrict my search within that. 

Now I have to search for an organ and then scroll down to check the ‘UBERON’ and then find the right term. 
I would personally prefer to have a text box with suggestions (in addition to the nice checkboxes), where I can directly type UBERON and check it, instead of having to scroll down. 

![image](https://user-images.githubusercontent.com/7849690/224987244-e238aec6-6c1c-4d55-b769-02e1505fd3f3.png)

**Comment by kalpanaps** [comment]
Same request from my end

**Comment by serjoshua** [comment]
We implemented a search filter just for ontology facets while retaining OLS4 faceting behavior in tact.
