### ISSUE TITLE
Lookup using iri have stopped working on OLS4

### ISSUE THREAD

**Issue by awaisathar** [EBISPOT/ols4#266]
Working: [https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http://www.ebi.ac.uk/efo/EFO_0003738](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http://www.ebi.ac.uk/efo/EFO_0003738) 
Not working: [https://www.ebi.ac.uk/ols4/ontologies/efo/terms?iri=http://www.ebi.ac.uk/efo/EFO_0003738](https://www.ebi.ac.uk/ols4/ontologies/efo/terms?iri=http://www.ebi.ac.uk/efo/EFO_0003738)

Background: We use the response from the `https://www.ebi.ac.uk/ols/api/ontologies/{ontology}/terms?short_form={short_form}` endpoint to create a link to `https://www.ebi.ac.uk/ols/ontologies/{ontology}/terms?iri={response._embedded.terms[0].iri}`

**Comment by serjoshua** [comment]
We now support `iri` as search parameter on the web and API. One thing to note though is that /terms redirects to /classes.
