### ISSUE TITLE
Drop jstree endpoint for OLS3 API?

### ISSUE THREAD

**Issue by udp** [EBISPOT/ols4#27]
We have not yet implemented the jstree endpoint in the OLS3 backwards compatible API. However, we do not use it in the OLS4 frontend and I question whether it is in use by any current users of the OLS3 API, as it was never really documented anyway. As it would be reasonably annoying to implement I wonder if we should just drop it in OLS4?

EDIT: The same goes for the /graph endpoint.

**Comment by udp** [comment]
@matentzn I don't suppose you know if anyone is using it?

**Comment by matentzn** [comment]
@srobb1? @shawntanzk on the new CL site (I don't think so, just covering bases)? I
Can't think of anyone else top of my head!

**Comment by shawntanzk** [comment]
We are only using the autocomplete widget for CL site, which I assume doesn't use jstree endpoint?

**Comment by henrietteharmse** [comment]
@shawntanzk Correct. This does not affect the autocomplete widget. Good point on the widgets though - we need to remember the widgets and the autocomplete widget is likely to be effected by OLS4.

@matentzn Can you please flag who is potentially using the autocomplete and tree control widgets? 

@udp Let us not implement the jstree endpoint for now at least until we get undeniable evidence to the contrary. It will really make our lives easier if we do not have to implement it.

**Comment by srobb1** [comment]
Hi Everyone,

We use: 
 - Auto Complete (https://planosphere.stowers.org/search/page/term)
 - Onto Graph and Tree (https://planosphere.stowers.org/ontology/PLANA_0002075)

**Comment by udp** [comment]
Thanks all. So we need to decide whether to:

1. Reimplement the OLS3 graph and jstree endpoints so the existing widgets continue to work with OLS4
2. Package up our new OLS4 graph and tree views (which will/do use the OLS4 API) as new and improved widgets and help users migrate to them
3. Both of the above?

**Comment by jamesamcl** [comment]
Example of jstree endpoint

https://www.ebi.ac.uk/ols/api/ontologies/efo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBA_2001024/jstree?viewMode=All&lang=en&siblings=false

```json
[ {
  "id" : "213107182_1",
  "parent" : "#",
  "iri" : "http://www.ebi.ac.uk/efo/EFO_0000001",
  "text" : "experimental factor",
  "state" : {
    "opened" : true
  },
  "children" : false,
  "a_attr" : {
    "iri" : "http://www.ebi.ac.uk/efo/EFO_0000001",
    "ontology_name" : "efo",
    "title" : "http://www.ebi.ac.uk/efo/EFO_0000001",
    "class" : "is_a"
  },
  "ontology_name" : "efo"
}, {
  "id" : "208419688_1",
  "parent" : "213082559_1",
  "iri" : "http://purl.obolibrary.org/obo/HP_0003674",
  "text" : "Onset",
  "state" : {
    "opened" : true
  },
  "children" : false,
  "a_attr" : {
    "iri" : "http://purl.obolibrary.org/obo/HP_0003674",
    "ontology_name" : "efo",
    "title" : "http://purl.obolibrary.org/obo/HP_0003674",
    "class" : "is_a"
  },
  "ontology_name" : "efo"
}, {
  "id" : "208425589_2",
  "parent" : "208419688_1",
  "iri" : "http://purl.obolibrary.org/obo/OBA_2001024",
  "text" : "age of onset of Huntington disease",
  "state" : {
    "opened" : true,
    "selected" : true
  },
  "children" : false,
  "a_attr" : {
    "iri" : "http://purl.obolibrary.org/obo/OBA_2001024",
    "ontology_name" : "efo",
    "title" : "http://purl.obolibrary.org/obo/OBA_2001024",
    "class" : "is_a"
  },
  "ontology_name" : "efo"
}, {
  "id" : "208419547_1",
  "parent" : "213107182_1",
  "iri" : "http://purl.obolibrary.org/obo/BFO_0000020",
  "text" : "material property",
  "state" : {
    "opened" : true
  },
  "children" : false,
  "a_attr" : {
    "iri" : "http://purl.obolibrary.org/obo/BFO_0000020",
    "ontology_name" : "efo",
    "title" : "http://purl.obolibrary.org/obo/BFO_0000020",
    "class" : "is_a"
  },
  "ontology_name" : "efo"
}, {
  "id" : "196752229_1",
  "parent" : "211334957_1",
  "iri" : "http://www.ebi.ac.uk/efo/EFO_0001444",
  "text" : "measurement",
  "state" : {
    "opened" : true
  },
  "children" : false,
  "a_attr" : {
    "iri" : "http://www.ebi.ac.uk/efo/EFO_0001444",
    "ontology_name" : "efo",
    "title" : "http://www.ebi.ac.uk/efo/EFO_0001444",
    "class" : "is_a"
  },
  "ontology_name" : "efo"
}, {
  "id" : "213082559_1",
  "parent" : "211349078_1",
  "iri" : "http://www.ebi.ac.uk/efo/EFO_0004949",
  "text" : "clinical temporal measurement",
  "state" : {
    "opened" : true
  },
  "children" : false,
  "a_attr" : {
    "iri" : "http://www.ebi.ac.uk/efo/EFO_0004949",
    "ontology_name" : "efo",
    "title" : "http://www.ebi.ac.uk/efo/EFO_0004949",
    "class" : "is_a"
  },
  "ontology_name" : "efo"
}, {
  "id" : "211349078_1",
  "parent" : "196752229_1",
  "iri" : "http://www.ebi.ac.uk/efo/EFO_0000719",
  "text" : "temporal measurement",
  "state" : {
    "opened" : true
  },
  "children" : false,
  "a_attr" : {
    "iri" : "http://www.ebi.ac.uk/efo/EFO_0000719",
    "ontology_name" : "efo",
    "title" : "http://www.ebi.ac.uk/efo/EFO_0000719",
    "class" : "is_a"
  },
  "ontology_name" : "efo"
}, {
  "id" : "211334957_1",
  "parent" : "213107182_1",
  "iri" : "http://purl.obolibrary.org/obo/IAO_0000030",
  "text" : "information entity",
  "state" : {
    "opened" : true
  },
  "children" : false,
  "a_attr" : {
    "iri" : "http://purl.obolibrary.org/obo/IAO_0000030",
    "ontology_name" : "efo",
    "title" : "http://purl.obolibrary.org/obo/IAO_0000030",
    "class" : "is_a"
  },
  "ontology_name" : "efo"
}, {
  "id" : "208425589_1",
  "parent" : "208419547_1",
  "iri" : "http://purl.obolibrary.org/obo/OBA_2001024",
  "text" : "age of onset of Huntington disease",
  "state" : {
    "opened" : true,
    "selected" : true
  },
  "children" : false,
  "a_attr" : {
    "iri" : "http://purl.obolibrary.org/obo/OBA_2001024",
    "ontology_name" : "efo",
    "title" : "http://purl.obolibrary.org/obo/OBA_2001024",
    "class" : "is_a"
  },
  "ontology_name" : "efo"
} ]
```

<img width="495" alt="Screenshot 2022-10-26 at 23 07 35" src="https://user-images.githubusercontent.com/454895/198147808-14e507ee-0e20-43a9-8cfa-69584a7ad149.png">

**Comment by jamesamcl** [comment]
Preliminary implementation is in OLS4 now; needs testing against OLS3 API

**Comment by jamesamcl** [comment]
@srobb1 Are you using the tree view from https://github.com/EBISPOT/OLS-treeview or has it been modified? I just tried the tree view from the repo and it doesn't provide the viewMode=All parameter, so returns no results, but on your planosphere website it does provide the viewMode=All parameter.

**Comment by srobb1** [comment]
Hi @udp,
I downloaded and set this up ages ago. The sys date on my ols-treeview.js is Mar 23, 2020, and there is a comment in the code near the top that says: // 2011-08-24

I can't remember if I modified it. Here is the code I am currently using: https://github.com/srobb1/tripal_ontologyPages/tree/master/theme/js/OLS-treeview. 

Ah, I did modify it, you can see here for in [my commit which contains ols-treeview.js](https://github.com/srobb1/tripal_ontologyPages/commit/97de07a1fc1b9dd0ef5f76334e6c0cadb170c50c). I did add  +'/jstree?viewMode=All' ;

Sofia

**Comment by jamesamcl** [comment]
Thanks @srobb1, that makes a lot of sense. We should update the OLS-treeview component to add ?viewMode=All as it is broken at the moment even with OLS3. I see you already have an issue open there so we'll definitely get around to it.

With regards to OLS4, the backwards compatible jstree endpoint is now implemented and I have checked it against the unmodified OLS3 tree view widget, which seems to work correctly. I'm now working on the graph view and I'm very close to having a working implementation. So it looks like we will be able to deploy OLS4 at EBI without any work required from existing users of the tree and graph view components.

**Comment by srobb1** [comment]
@udp 

Ok. So I should not be affected, but Is this something I should be looking into updating? When you have completed your deployment could you point me to the documentation. Or if there is documentation now? If I am understanding what is happening, OLS is being updated to OLS4 and the api calls that the widgets are making were going to not work, but now it seems like they will still be working.  Are there new preferred widgets I should be looking at updating my site with? 

Thank you for taking a few minutes to walk me through this. I greatly appreciate your time.

Sofia

**Comment by jamesamcl** [comment]
Hi @srobb1,

Sorry, you were pulled into this discussion when we were still deciding what to do so I appreciate this has been confusing. OLS is being updated to OLS4 next year, but we are in the process of implementing the OLS3 APIs in OLS4 for compatibility. So the API calls that the widgets are making will continue to work identically and there will be nothing to do from your end. We are actively testing the widgets as part of our OLS4 development to make sure this is the case.

In the future we would like to develop new widgets so we can redesign them and add new features, but that will not be for some time after OLS4 is released. We have no plans to deprecate the OLS3 API, even after those new widgets are released, so you will be able to migrate to them as and when you desire to. The OLS3 API is here to stay. :-)

cheers,

James

**Comment by jamesamcl** [comment]
Closing this as we now have no plans to drop the jstree endpoint; it will be supported as normal in OLS4 and the widgets will continue to function.

**Comment by srobb1** [comment]
Thank you very much. We really love the widgets and are very happy to have them on our site. We will be watching for the new widgets in the future.
