### ISSUE TITLE
Data properties duplicated

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#270]
See /testcases/owl2-primer/key-constraint-on-data-property.
![image](https://user-images.githubusercontent.com/32327979/225080639-1741b569-2a68-4956-9729-14fa91442e37.png)

Interestingly, for the 1 the domain is given as Person and for the other not. See below:
![image](https://user-images.githubusercontent.com/32327979/225081412-a25cfc5e-e026-4bef-a6da-178e38c650a3.png)

vs

![image](https://user-images.githubusercontent.com/32327979/225081125-ca49dec1-e570-4795-ab3f-05b43b6fe8d0.png)

**Comment by jamesamcl** [comment]
There are two different properties in the OWL file:

```xml
 <owl:AnnotationProperty
rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/key-constraint-on-data-property.owl#hasSSN"/>
```

and

```xml
<owl:DatatypeProperty
rdf:about="http://www.ebi.ac.uk/testcases/owl2primer/key-constraint-on-data-property#hasSSN">
```

Notice the IRIs are different (one has `.owl` in it and the other doesn't).
