### ISSUE TITLE
Add ols-announce email to landing page.

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#272]
![image](https://user-images.githubusercontent.com/32327979/225315474-4d13959b-f745-4afc-b8e0-b00a62f5dcf2.png)

This refers to the ols announce email without actually providing the email address: ols-announce@ebi.ac.uk.

**Comment by jamesamcl** [comment]
The link seems dead though? I just went to OLS3 and clicked the link and it took me here:

https://listserver.ebi.ac.uk/mailman/listinfo/ols-announce

I see this:

<img width="394" alt="Screenshot 2023-03-15 at 22 55 07" src="https://user-images.githubusercontent.com/454895/225461314-d803cc2b-a946-4fbb-9d8a-1d3d0abdbf08.png">

**Comment by serjoshua** [comment]
Correct link(s) has been added but do note the link's host sometimes is dead.
