### ISSUE TITLE
Add back glyphs for part_of, instance_of

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/ols4#273]
![image](https://user-images.githubusercontent.com/112839/225375106-9b1cef4a-27d3-4293-84f7-713c2245b060.png)
![image](https://user-images.githubusercontent.com/112839/225375410-43b1293b-bc43-47f5-9a24-71b2761703ea.png)
![image](https://user-images.githubusercontent.com/112839/225375617-825c99d7-cf5a-46e3-8b30-6f8d7b32b640.png)

**Comment by jamesamcl** [comment]
I wonder if we should be more explicit about it e.g. “has part” rather than a P icon?

**Comment by matentzn** [comment]
It will look very noisy in ontologies like Uberon, which have more part of then subclass hierarchy - I like the p, but we could look at an example.

**Comment by jamesamcl** [comment]
Fair point. I just remember when I first started using OLS finding the "I" and "P" icons confusing because I had no idea what they stood for. Would the text "part" and "instance" really take up that much more space? I was thinking in purple text like the class expressions.

**Comment by serjoshua** [comment]
I could look into this. I can implement different versions of it and you can choose _but_ I have to check first if we still have the `part_of` and `instance_of` thrown as CSS classes. If not, we definitely have to look back on OLS3's logic and how it adds those classes.

**Comment by dosumis** [comment]
I think it's important to have some way to indicate distinct relation types in the tree & as Nico says, full relation names could make the view a bit too busy.   Ideally with glyphs we'd have a key displayed somewhere, although maybe that's not trivial.

**Comment by matentzn** [comment]
I think a `legend` is a great idea David. There certainly should be some room for a legend, at least a popu when you hover over a glyph symbol

**Comment by jamesamcl** [comment]
I like the idea of a legend at the bottom of the tree (when the glyphs are used).

I try to avoid mouse hover as a primary interaction method where possible nowadays as (1) it doesn't work on mobile, which fair enough isn't really a consideration for OLS, but also (2) it isn't intuitive for anyone born this millenium for whom mice aren't their first learned input device!

**Comment by jamesamcl** [comment]
@serjoshua let me look at this one first - it requires changing how the tree is constructed as currently we just use the lossy hierarchicalParent edge which does not include any information about how the hierarchy was derived.

Probably we need to completely ignore hierarchicalParent when constructing the tree and instead construct it from rdfs:subClassOf, interpreting the various types of class expression as we go. (We still make use of hierarchicalParent for retrieving the entities that should be placed in the tree, as it forms direct edges in neo4j; but only the class expressions can provide all of the info we need to display.)

The good news is that this would just be a frontend change.

**Comment by jamesamcl** [comment]
Ended up using hierarchicalParent as we were before, but I reified it to add the relation.

<img width="486" alt="Screenshot 2023-05-27 at 21 21 38" src="https://github.com/EBISPOT/ols4/assets/454895/bed80507-50a2-4494-88f0-178a9217637e">
