### ISSUE TITLE
Navigation issue in search box

### ISSUE THREAD

**Issue by ubyndr** [EBISPOT/ols4#274]
You cannot navigate in the dropdown menu from search box with up ⬆️  and down ⬇️  arrow keys

![image](https://user-images.githubusercontent.com/20892222/225637505-a798d213-0a40-44a2-80ee-c260493e3bba.png)

**Comment by cpauvert** [comment]
Hi,
great new interface by the way, keep up the good work! :muscle: 

I noticed the same as @ubyndr on Firefox v111.0 and Brave 1.47.171.

Hope that helps, 
Best,
