### ISSUE TITLE
Finish implementing graph view

### ISSUE THREAD

**Issue by udp** [EBISPOT/ols4#28]
So far we have a very basic configuration of CytoscapeJS embedded for the graph view. This needs developing to have feature parity (or close enough) to OLS3.

**Comment by jamesamcl** [comment]
Since we now have the OLS3 graph view endpoints implemented, it may be quicker to simply embed the [OLS3 graph view](https://github.com/EBISPOT/OLS-graphview) for the time being. The code has been copied into this repo in the https://github.com/EBISPOT/ols4/tree/dev/legacy-plugins-test folder.
