### ISSUE TITLE
Search parameters in REST API

### ISSUE THREAD

**Issue by ens-lgil** [EBISPOT/ols4#281]
Hi,

We use the OLS REST API v3 with the parameters `obo_id` and `id`, but it looks like with OLS v4 it only works with `iri`.

For instance we use the parameter `obo_id` in the **/ontologies/efo/terms/** endpoint:
https://www.ebi.ac.uk/ols/api/ontologies/efo/terms?obo_id=EFO:0009531

And the parameter `id` the **/ontologies/efo/ancestors/** endpoint:
https://www.ebi.ac.uk/ols/api/ontologies/efo/ancestors?id=MONDO_0005041

Is it something that is going to be (re)implemented in OLS v4 ?

Thanks,
Laurent

**Comment by henrietteharmse** [comment]
In order to be backward compatible we ideally need to implement this.

**Comment by ens-lgil** [comment]
Thanks!

**Comment by serjoshua** [comment]
Good day, Laurent. Apologies for not getting back to you the soonest. We already implemented code to handle this but it seems like there is an issue when `obo_id` or `short_form` is passed for some APIs like **ancestors**. They work but return empty data. If you pass the term's full IRI though as `id` or `iri`, it works as it should be. Check below OLS4 **ancestors** APIs for MONDO:0005041.

https://www.ebi.ac.uk/ols4/api/ontologies/efo/ancestors?id=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005041
https://www.ebi.ac.uk/ols4/api/ontologies/efo/ancestors?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005041

As for the **terms** API, we handle `obo_id` as `oboId` or `curie` now. While `short_form` is now `shortForm`.

https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?curie=EFO:0009531
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?oboId=EFO:0009531
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?shortForm=EFO_0009531
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?id=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005041
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005041

I'm going to keep this ticket open to track why some API like **ancestors** couldn't handle some parameters.

**Comment by ens-lgil** [comment]
Thanks Joshua!
I can see that the `terms` endpoint works with the `oboId` parameter.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Hi Joshua,

I tried the `terms` endpoint and using the different parameters it seems that only few of them work:
- `short_form`: https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?short_form=MONDO_0016056
- `iri`: https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?iri=http://purl.obolibrary.org/obo/MONDO_0016056

The other parameters seem to return all the entries (+40K), e.g.:
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?shortForm=MONDO_0016056
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?oboId=MONDO_0016056
https://www.ebi.ac.uk/ols4/api/ontologies/efo/terms?curie=MONDO_0016056
I tried the IDs with `_` and with `:` but it didn't change the results.

Thanks,
Laurent

**Comment by serjoshua** [comment]
Hello Laurent,

I just deployed an update to OLS4 API. You may ignore everything I mentioned earlier. The endpoints you are using right now, just change **ols** to **ols4** and it should work. If not, feel free to create a new ticket and report the affected term in OLS.

Thank you!
