### ISSUE TITLE
Loading placeholder for one term takes 30s to load and  set a hidden 500 server response

### ISSUE THREAD

**Issue by cpauvert** [EBISPOT/ols4#286]
Hi, 
first of all, thank for this tool and the new update of the ols4, it looks already great and I look forward to it being released officially.

However, I noticed a strange bug. When I'm clicking on a term (e.g., https://www.ebi.ac.uk/ols4/search/GO:0098743), I'm brought to the term's page, but there is a loading placeholder, as below:

![loading](https://user-images.githubusercontent.com/12406679/226843930-94eb25ea-7aa2-4496-b27b-a578ef3e4af8.png)

This placeholder **remains for 30s, and upon inspection, it seems that there is a 500 internal error of the server**:

![Screenshot_2023-03-22_09-25-28](https://user-images.githubusercontent.com/12406679/226844143-b3f1a0a7-15ed-493d-b98f-c604aba6926d.png)

This was observed with Brave browser and Firefox browser.

Best,

**Comment by jamesamcl** [comment]
Thanks, the kubernetes cluster we are sharing was experiencing heavy load. We plan to move OLS4 to a bigger cluster hopefully in the coming week.

**Comment by cpauvert** [comment]
Thanks James for the quick reply. Good that the v4 attracts attention :thumbsup:. Shall I close the issue then?
Best,

-------- Original Message --------

**Comment by jamesamcl** [comment]
We can leave open until the new cluster is deployed in case anyone else has the same issue.
