### ISSUE TITLE
[OLS4 feedback] - resources logo

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/ols4#287]
In the ontology tables, some resources have logos displayed and others not, https://www.ebi.ac.uk/ols4/ontologies

While I like the idea of logos, I find this distracting here, and as logos are not consistent in look and feel, sizing etc it is hindering the user experience and table consistency.

Options could be removing logos, or putting them in a distinct fixed width column.

**Comment by henrietteharmse** [comment]
Sizing is now reasonably consist
