### ISSUE TITLE
[OLS4 feedback] - URL direct links

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/ols4#288]
Would it be possible to have URL parameters to enable direct linking to pages?

At the moment I can't point to page 4 of the ontology table https://www.ebi.ac.uk/ols4/ontologies which is where DUO is for example, or a direct link to the list view at https://www.ebi.ac.uk/ols4/ontologies/duo

**Comment by jamesamcl** [comment]
Thanks for reporting this - every page should have a unique URL; where they are missing it's considered a bug.
