### ISSUE TITLE
OLS4 feedback

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/ols4#290]
Looks good! Thanks for all you do. Just two very small requests, if possible: 

1. In OLS3, we could bookmark, eg, EFO ontology results only (https://www.ebi.ac.uk/ols/search?q=&submit1=1&ontology=efo). It doesn't seem to be possible with OLS4? 

2. When searching the homepage for a term (https://www.ebi.ac.uk/ols4/), pressing enter takes you to the next page okay. But when searching from the subsequent page (eg. https://www.ebi.ac.uk/ols4/search/apnea?exactMatch=false&includeObsoleteEntities=false&isDefiningOntology=true) and pressing enter, the suggested terms box remains until you click off it:
<img width="1297" alt="Screenshot 2023-03-23 at 08 48 32" src="https://user-images.githubusercontent.com/61545198/227150700-4905b3a5-fa58-4dbd-9f3f-3bcac0a5110e.png">

**Comment by jamesamcl** [comment]
Thanks! these are both bugs :)

**Comment by serjoshua** [comment]
We now support `q`, `ontology` and `type` path parameters in search. Please do note that `type` and `ontology` can only accept one value at a time.

**Comment by jamesamcl** [comment]
They should support multiple values to be compatible with OLS3. Will open separate issue

**Comment by serjoshua** [comment]
Cool. It is easily testable since the search parameters are directly passed to the API.
