### ISSUE TITLE
AFO hierarchy not displaying correctly.

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#294]
Issue raised on Help desk regarding AFO ticket: http://helpdesk.ebi.ac.uk/Ticket/Display.html?id=644975

abrading material description

http://purl.allotrope.org/ontologies/result#AFR_0002711
should not have 'material' as superclass

abrasion source description
http://purl.allotrope.org/ontologies/result#AFR_0002709
should not have 'material' as superclass

coated material description
http://purl.allotrope.org/ontologies/result#AFR_0002710
should not have 'material' as superclass
material
http://purl.allotrope.org/ontologies/material#AFM_0000275

atom
http://purl.allotrope.org/ontologies/material#AFM_0001028
should not have 'subatomic particle' as superclass
subatomic particle
http://purl.obolibrary.org/obo/CHEBI_36342

**Comment by ghost** [comment]
Screenshot of `abrading material description` in Protégé. `material` is part of a restriction here.

![for ols - abrading material description - protégé](https://user-images.githubusercontent.com/128794436/227473970-299c85d0-f05d-4526-a541-8beb4a9b2951.png)

Screenshot from OLS:

![ols-screenshot-material](https://user-images.githubusercontent.com/128794436/227473976-51b3a509-a27a-4b56-8b42-00abe7a2dd0a.png)

Note from our tester:

I have rechecked the inferencing in AFO.
`abrading material description` is a subclass of `description` and is not a subclass of `material`.

It is formally defined as (in Manchester syntax):
```
Subclass of 
af-r:description and subclass of
‘iao:is about’ some (af-m:material and (‘ro has role’ some ‘af-rl:abrading material role’)) 
```

which is correct.

**Comment by jamesamcl** [comment]
I can't reproduce any of these locally with the current code.

<img width="1607" alt="Screenshot 2023-03-26 at 02 11 09" src="https://user-images.githubusercontent.com/454895/227749846-13f5470b-8910-4a25-bc9a-eb849b4f732a.png">

<img width="1573" alt="Screenshot 2023-03-26 at 02 11 25" src="https://user-images.githubusercontent.com/454895/227749854-eefe1650-78b5-4c4a-b448-277a98838466.png">

<img width="1575" alt="Screenshot 2023-03-26 at 02 11 50" src="https://user-images.githubusercontent.com/454895/227749875-d934ed89-e7fc-431b-9e29-f4c967943279.png">

<img width="1550" alt="Screenshot 2023-03-26 at 02 12 15" src="https://user-images.githubusercontent.com/454895/227749894-4cd54ef7-c0e4-492d-9581-532808ec3929.png">

Possibly it got fixed as part of another issue but the code hasn't been deployed yet. As OLS4 prod is down I can't verify so will have to wait until the cluster is back.
