### ISSUE TITLE
Provide EBI OLS dataset as a download

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#298]
We can gzip it and put on FTP. Gzipped it's only in the tens of GBs. We should include:

- `ontologies.json`
- `ontologies_linked.json`
- solr database
- neo4j database

Ideally these would be dated with an archive of historical releases. This would enable developers to:

- Start a local OLS instance with the entire EBI dataset
- Start a local Solr or Neo4j instance to query, with prepopulated indexes
- Access ontology information (including processed/linked info with the extra edges added by owl2json and links from the linker) through the JSON files

We should be clear that their representation is undocumented and subject to change at any time, but I think it would be a very useful community resource - and we are already putting the CPU cycles in to perform the dataload so why not.

These can be linked from the OLS homepage in a downloads section.

We can also update the readme of this repo with instructions to get an OLS instance with the EBI dataset preloaded.

**Comment by matentzn** [comment]
I still think this is the way to go for OxO and I will explain why in a call. Can you gzip these all as separate files?

**Comment by jamesamcl** [comment]
Yes they should be gzipped as separate files.

**Comment by jamesamcl** [comment]
OLS already has a folder at https://ftp.ebi.ac.uk/pub/databases/spot/ols/ but we don't currently have access. I've opened a ticket with TSC.

**Comment by matentzn** [comment]
Sweet, let me know when its done, and I will explain to you my thinking.

**Comment by jamesamcl** [comment]
OLS4 data releases now available at https://ftp.ebi.ac.uk/pub/databases/spot/ols/

Still need to add a link to the UI
