### ISSUE TITLE
Add ORCIDIO to OLS 4

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/ols4#301]
Can we add ORCIDO to OLS4: https://github.com/cthoyt/orcidio

This we can also use this to simply label ORCIDs across ontologies, and retrieve basic provenance information

cc @cthoyt

**Comment by cthoyt** [comment]
Similarly, can we also add RORIO? It's at https://GitHub.com/cthoyt/rorio and downloadable from https://w3id.org/rorio/rorio.owl

**Comment by jamesamcl** [comment]
Not sure about adding something called "ORCIDO" that actually only has a tiny subset of the ORCID dataset. Granted these are the ORCIDs used by OBO, but OLS should be able to display ORCIDs used in any ontology not just OBO ones.

We already have a more general solution to displaying the name+link for *ANY* orcid lined up for deployment.

**Comment by jamesamcl** [comment]
ORCIDs are now displayed as names (see contributor in bottom right)

<img width="1688" alt="Screenshot 2023-04-12 at 22 39 09" src="https://user-images.githubusercontent.com/454895/231591837-7d7a7c6a-6e8a-4bb2-9b37-eef27ed2e5b1.png">

We match against all of ORCID so no need for ORCIDO.

**Comment by matentzn** [comment]
How awesome is that! Nice one :)
