### ISSUE TITLE
Search bar within ontology does not search in ontology

### ISSUE THREAD

**Issue by LCCarmody** [EBISPOT/ols4#302]
Search bar within ontology does not search in ontology:

When I am in MAXO ontology, there is a search bar that says 'search MAXO'. However, when entering a term to query maxo, it searches OLS wide and not within MAXO. 
<img width="1549" alt="Screen Shot 2023-04-07 at 10 00 39 AM" src="https://user-images.githubusercontent.com/26067008/230621842-43412ec6-eaf8-4fb7-9519-e96ff63ed61b.png">

**Comment by jamesamcl** [comment]
I can't reproduce this

<img width="1578" alt="Screenshot 2023-04-11 at 00 31 47" src="https://user-images.githubusercontent.com/454895/231018513-eccff3a6-8139-4121-bbf8-b120a6148571.png">

**Comment by jamesamcl** [comment]
<img width="1574" alt="Screenshot 2023-04-11 at 00 32 13" src="https://user-images.githubusercontent.com/454895/231018566-d34e818e-2691-4e53-9fc1-33d0e4cd52d9.png">

**Comment by matentzn** [comment]
I also noticed this: the index in solr response correctly but click on the "search" button and it will reveal results from outside the ontology

**Comment by LCCarmody** [comment]
So....sorta. Yes, when you type in what you are interested in (ex. diabetes...) there is a list of maxo terms which you can select. Yay. 

HOWEVER, if you are not certain about the term---or it isn't listed, then it searches all of OLS. For example, complete the word 'diabetes' and hit return without selecting a specific MAXO term. Then the top search result will be an HP term.

Previous iterations of OLS, it would only list terms from the ontology you are searching (in this case 'MAXO). 

I am not sure if there are other scenarios where this is true, but this is one.  I do need this search feature because sometimes there are too many terms within a single ontology and I need to look for it. Or I am not certain of the name or spelling.  Having me go back to all of OLS is counterproductive.

FTR, using Mac/chrome for searching.
Thx.
