### ISSUE TITLE
Clicking on search suggestions does not populate search field

### ISSUE THREAD

**Issue by ghost** [EBISPOT/ols4#307]
The following was observed in the Safari browser.

**Expected**: When clicking on a search suggestion, it is expected that the clicked term would populate the search field. This is how OLS3 functioned, as shown below, where the term '1st arch mandibular component' is being searched. Additionally, OLS3 also automatically shows the search results after the suggested term is clicked.
![OLS3-populate](https://user-images.githubusercontent.com/95643797/231429177-4639ce26-1d86-40f6-843a-405faf530c0f.gif)

--

**Observed**: When clicking on a search suggestion in OLS4, the term does not populate the search field.
![OLS4-not-populate](https://user-images.githubusercontent.com/95643797/231428510-f3d77eec-7ba9-40ef-a670-f97fe6ab4d7a.gif)

**Proposed fix**: When clicking a suggested search term in OLS4, populate the search field with the clicked term.

**Comment by ghost** [comment]
Additionally, after typing the search string in OLS4 and pressing "enter / return" on the keyboard, nothing happens. A user is required to click the "Search" button on the webpage in order to submit the search string.

**Comment by serjoshua** [comment]
This has been deployed to production. Let us know if you experience any issues.

**Comment by ghost** [comment]
Thank you, @serjoshua.
Once a term from the drop-down list of suggestions is clicked, it now populates the search field as expected.

While not a major issue, but to make record of the difference, OLS3 would automatically go to the search results once the term was clicked (see first .gif above).
In OLS4, however, the user must still click the "Search" button on the web page after clicking the suggested string in order to navigate to the search results page. Pressing "enter / return" on a keyboard will not take the user to the search results after a term is selected from the drop down. In OLS4, pressing "enter / return" on a keyboard will yield search results only if the user does **not** click out of the search field.

**Comment by serjoshua** [comment]
Welcome!

In OLS4, the enter/return key press only works when the search box is in focus (cursor is inside the input field).

As for the clicking of suggestions, I suggest using the down arrow key (to select) and enter/return key press to redirect directly to the search results. When clicking using the mouse cursor, yes, it will only fill the input field. Redirection using mouse cursor click will only work for "Jump to" entries. Thank you for documenting your observations by the way. Sadly, we will have to keep the current behavior for now.
