### ISSUE TITLE
out of date oral health and disease ontology

### ISSUE THREAD

**Issue by wdduncan** [EBISPOT/ols4#312]
The version of the [oral health and disease ontology](https://github.com/oral-health-and-disease-ontologies/) on the OLS4 is out of date.

The OLS4 version for [OHD](https://www.ebi.ac.uk/ols4/ontologies/ohd) shows Version `2022-10-10` . But, the most recent version is `2023-04-14 ` (e.g., see [Ontobee](https://ontobee.org/ontology/OHD) or check its [purl](http://purl.obolibrary.org/obo/ohd.owl)).

**Comment by jamesamcl** [comment]
Looks like this has updated now?

https://www.ebi.ac.uk/ols4/ontologies/ohd

<img width="488" alt="Screenshot 2023-04-20 at 00 16 31" src="https://user-images.githubusercontent.com/454895/233219468-bbbbfb72-543d-49ba-871b-59ae99378df5.png">

**Comment by wdduncan** [comment]
Yes. It looks like has updated. Thanks!  
Will update automatically now when changes are made?

**Comment by henrietteharmse** [comment]
Yes, it should update automatically.
