### ISSUE TITLE
Interactive API Documentation

### ISSUE THREAD

**Issue by giraygi** [EBISPOT/ols4#313]
An interactive documentation page might be helpful to introduce the current state of the API and to perform queries against it via a convenient interface. OpenAPI 3 specification and swagger might be a good candidate for this.

**Comment by dosumis** [comment]
Looks great, but think it also might be worth pulling over the old doc as it reflects the HAL approach to API building that informed the design of the OLS3 API which OLS4 is designed to replicate (at least for now in order to support backwards compatibility: https://www.ebi.ac.uk/ols/docs/api

**Comment by jamesamcl** [comment]
I think this is a good starting point - we can always copy the ols3 docs over in addition

**Comment by udp** [comment]
This has gone live but is not currently accessible as we need to update EBI firewall rules to route through `/swagger-ui/` to the backend as well as `/api/` (currently they hit the frontend, but the swagger docs are provided by the backend).

This also applies to the Docker frontend server.

**Comment by serjoshua** [comment]
Old documentation has been migrated. Duplicate of #319.
