### ISSUE TITLE
Blank page when clicking on connected_to RO:0002170

### ISSUE THREAD

**Issue by anitacaron** [EBISPOT/ols4#317]
The link is this https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002170

It's a property, and I didn't find another example. The sub property of connected_to is fine https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002382?lang=en

**Comment by serjoshua** [comment]
Fix has been deployed. Let us know if there are still issues. Thanks.
