### ISSUE TITLE
Tree not visible for PR_000001954 in CL

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#318]
https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPR_000001954?isDefiningOntology=false

**Comment by serjoshua** [comment]
this is also broken in OLS3: it just displays the root "cell" class 

https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_36080

**Comment by serjoshua** [comment]
Fix has been deployed. Thanks.
