### ISSUE TITLE
Add CPONT to OLS4

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/ols4#323]
Hi- could we please request that the Critical Path Application Ontology be added to OLS4?

it is in the old OLS version:
https://www.ebi.ac.uk/ols/ontologies/cpont

Thank you!

**Comment by jamesamcl** [comment]
@serjoshua Currently the OLS4 config isn't pulled from git, it's on the NFS somewhere (you can find by looking at the LSF script for rdf2json, it should be called `ebi.json` to differentiate it from the obo foundry config). We need to move this to git but that's a separate issue.

In theory `ebi.json` should contain everything from OLS3 but it's possible cpont got missed. If so you will need to dig out the old OLS3 config from the OLS-Config repo and convert it to json.

If it's not there, the config got lost during the OLS3 era and we will need to re-establish it with the ontology import form as with any new ontology, then add to `ebi.json`.

**Comment by nicolevasilevsky** [comment]
thanks @udp and @serjoshua

**Comment by serjoshua** [comment]
Hi @nicolevasilevsky, we already added CPONT to the configuration and is now available in OLS4. Let us know if you experience any issues.

**Comment by nicolevasilevsky** [comment]
Fantastic, thank you!
