### ISSUE TITLE
BUG: Graph view gives error message

### ISSUE THREAD

**Issue by emquardokus** [EBISPOT/ols4#325]
When pressing graph button, only error appears: 

Failed to do the second webservice call! Is the server down? Tried to reach https://www.ebi.ac.uk/ols4/api/ontologies/uberon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0002113/graph for data

with "loading...' on middle of page

Tried for the last week.

**Comment by serjoshua** [comment]
Apologies for not getting back to you soon enough. OLS4 was indeed down for a few days but it is back up now. Let us know if you still experience any issues.
