### ISSUE TITLE
Tree and graph not appearing for terms in OLS4

### ISSUE THREAD

**Issue by ghost** [EBISPOT/ols4#326]
Platform: Mac
Browser: Safari
Issue: The tree and graph do not appear on the term pages.

For example, https://www.ebi.ac.uk/ols4/ontologies/ohpi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000235:

<img width="1078" alt="Screenshot 2023-05-02 at 11 37 11" src="https://user-images.githubusercontent.com/95643797/235644766-6b4f893f-dbca-41bb-96fd-ee37c6489877.png">

--

<img width="1028" alt="Screenshot 2023-05-02 at 11 36 56" src="https://user-images.githubusercontent.com/95643797/235644798-25e43471-65ed-472a-b67d-0e39158731fa.png">

**Comment by henrietteharmse** [comment]
Thanks. Yes, we are aware and working on getting OLS 4 up and running ASAP.

**Comment by serjoshua** [comment]
OLS4 is back up again. Let us know if you still experience any issues.

**Comment by ghost** [comment]
@serjoshua, @henrietteharmse, unfortunately it appears the issue of no tree or graph display has returned.
https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_2000603?lang=en


<img width="1261" alt="Screenshot 2023-07-07 at 12 52 35" src="https://github.com/EBISPOT/ols4/assets/95643797/084d44e9-b909-4ebf-a147-05dcdf3386bb">

<img width="1090" alt="Screenshot 2023-07-07 at 12 52 18" src="https://github.com/EBISPOT/ols4/assets/95643797/e014fada-f5b4-419e-96ca-e4bb3cb41cf6">
