### ISSUE TITLE
hp link has no label

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#328]
https://www.ebi.ac.uk/ols4/ontologies/oba/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBA_2020000

In the class relations there is an hp term. But it appears as an iri instead of its label

<img width="447" alt="Screenshot 2023-05-04 at 16 10 58" src="https://user-images.githubusercontent.com/454895/236250582-58501c38-c430-48ad-8d8e-797817ea74ab.png">

**Comment by serjoshua** [comment]
Fix has been deployed. Thanks.
