### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by udp** [EBISPOT/ols4#33]
Very minor issue at this point in time, but before I forget we only have a PNG of the logo. At some point I found out which font it was to make the OntoString logo, so it would be nice to recreate the OLS one as an SVG for the new frontend so that it's resolution independent <s>and we can make OLS T-shirts</s>.

**Comment by serjoshua** [comment]
By the way, I got curious what font is this.

**Comment by serjoshua** [comment]
Font families:
- Fortuna Dot
- Avalon (Poppins - Google Fonts alternative)

**Comment by serjoshua** [comment]
![Screen Shot 2023-10-06 at 11 24 09 AM](https://github.com/EBISPOT/ols4/assets/25520595/3c712bcc-2b80-435b-ad61-8128d08fac14)
