### ISSUE TITLE
where has the "Also in" part gone in the results screen?

### ISSUE THREAD

**Issue by only1chunts** [EBISPOT/ols4#331]
a feature that is of particular use in the previous version is the "Also In" field in the summary results. It gives a quick and easy guide to see which term is being re-used in multiple ontologies and therefore well integrated into networks.
See the example screenshot for diabetes:
![image](https://user-images.githubusercontent.com/6037145/236480374-e7c3cc98-298f-4344-a55b-6dfcfe01932a.png)
The NCIT term is not integrated with any other ontologies where as DOID term is also used in various other ontologies, and therefore more likely to be the one I look at first to assess whether its definition was exactly what I'm after.
Please can you add that feature into the v4 results list.

**Comment by jamesamcl** [comment]
@serjoshua we already show this info on the entity page so it’s in the Entity object; just needs displaying in the results, should be a quick frontend fix.

**Comment by jamesamcl** [comment]
Fixed by @serjoshua and deployed ! Let us know if you have any more issues.
