### ISSUE TITLE
Use external OLS config.

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#334]

**Comment by jamesamcl** [comment]
Need to update the OLS-Config repo with the current OLS4 config from the NFS as some ontologies have been added/updated.

**Comment by jamesamcl** [comment]
@cthoyt is asking me about opening PRs against the OLS4 config

**Comment by matentzn** [comment]
I agree this would be nice

**Comment by cthoyt** [comment]
I would also like to suggest that some metadata (e.g., contact information, homepage, description of ontology) gets pulled in from Bioregistry at build time to reduce curation burden / duplication

**Comment by matentzn** [comment]
I dont think there is much primary metadata beyond the OBO metadata that is being pulled in directly from OBO..

**Comment by serjoshua** [comment]
Deployment now pulls configuration from https://github.com/EBISPOT/ols4/blob/dev/ebi_ontologies.json
