### ISSUE TITLE
EquivalentTo and SubClassOf relations do not show

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#335]
Liver disease in EFO is a good example of this: [https://www.ebi.ac.uk/ols4/ontologies/clo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0001421?isDefiningOntology=true](https://www.ebi.ac.uk/ols4/ontologies/clo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0001421?isDefiningOntology=true)

This is the class relations displayed in OLS4 (this is the same whether "Canonical definitions only" is checked or not):
![image](https://github.com/EBISPOT/ols4/assets/32327979/8513c6f9-43dc-40a2-8c55-c9afb5e2875b)

This is the class relations displayed in OLS3: 
![image](https://github.com/EBISPOT/ols4/assets/32327979/8c2e8297-2418-4a32-9b21-8450b7d5f447)

This is what it looks like in Protege:
![image](https://github.com/EBISPOT/ols4/assets/32327979/c0e3dd92-732a-470e-8a1b-2037ce680d97)

**Comment by serjoshua** [comment]
You are looking at an imported EFO term in CLO.

OLS3 (CLO): https://www.ebi.ac.uk/ols/ontologies/clo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001421
OLS4 (CLO): https://www.ebi.ac.uk/ols4/ontologies/clo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0001421

OLS3 (EFO): https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001421
OLS4 (EFO): https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0001421

**Comment by henrietteharmse** [comment]
Ah! That is indeed correct! This is a relief! 

This how this happened: 
![image](https://github.com/EBISPOT/ols4/assets/32327979/f8b79452-7afd-4308-b77e-4f24d16435c6)
