### ISSUE TITLE
Implement preferred roots

### ISSUE THREAD

**Issue by udp** [EBISPOT/ols4#34]

**Comment by jamesamcl** [comment]
@serjoshua :

* Add a ViewMode parameter to the ontology page: All or PreferredRoots, and the UI to toggle between them:

<img width="871" alt="Screenshot 2022-10-27 at 15 27 11" src="https://user-images.githubusercontent.com/454895/198313927-c715edc9-a76e-4151-86bc-2615da0b5f90.png">

Pass it to the EntityTree. The EntityTree currently calls just `/roots`, so you need to change it to use `/preferredRoots` instead when preferred roots is selected.

James:

* implement `/preferredRoots` endpoint.

**Comment by jamesamcl** [comment]
Also need to implement this in the OLS3 jstree endpoint.
