### ISSUE TITLE
Enhance default view of Vertebrate Breed Ontology (VBO)?

### ISSUE THREAD

**Issue by franknic** [EBISPOT/ols4#341]
The increasing numbers of users of the Vertebrate Breed Ontology (VBO) would be very grateful if the default view could be enhanced to: 
1. show the hierarchical levels of the ontology, as at [https://www.informatics.jax.org/vocab/mp_ontology] 
2. show the returns of a search as the branches of the ontology that contain the search terms.

My colleagues and I would be very grateful if we could arrange a discussion about the possibilities of achieving these aims.
Frank Nicholas (franknic)

**Comment by matentzn** [comment]
@franknic - what do you mean "show the hierarchical levels of the ontology" 

![image](https://github.com/EBISPOT/ols4/assets/7070631/a6a465af-6f9f-4ba8-a9a4-47df386af5e6)

Which terms are you looking to be in a hierarchy and are not?

**Comment by franknic** [comment]
Thank you very much, Nico, for responding so quickly.
One of the biggest problems with the present display is that most of the screen is occupied with NCBI taxon levels that are not actually in the VBO, and which are not of any interest to the vast majority of people who will use VBO. It would be great if the displayed hierarchy could start at species.
Then, it would be a huge improvement if the hierarchical display showed the other two levels of the VBO hierarchy, namely transboundary within species and breed-country within transboundary or, for those breeds that exist only in one country, breed-country within species.
It would be even better if the synonyms for transboundary and breed-country were shown alongside (in the same row) as the relevant transboundary or breed-country entry.
Also, it would be great if the entries could be shown in alphabetical order within a level. At present, both the levels and the entries within a level appear to be ordered randomly. The fact that the list in your comment is alphabetical may indicate that I need to change the settings in EBI OLS; the lists that I have generated from a range of searches in EBI OLS have never been ordered alphabetically.
In essence, my aim is to achieve a display that will show first-time users the structure of VBO
If I can achieve this by altering the settings, that would be absolutely wonderful!
At the moment, I have even less success with OLS4 than with OLS3. I appreciate that the former is still under development. Indeed, it is because it is still under development that I thought it might be helpful to post my thoughts on what would be really helpful for users to visualise VBO.
I would probably be able to explain my thoughts more clearly verbally than in writing. If a chat is feasible, I would be very grateful.
Thank you, again, for spotting my post, and for responding.
Best wishes
Frank

**Comment by franknic** [comment]
To expand on my previous message, I can show two comparative screenshots. The first shows the default OLS3 view of the Livestock Breed Ontology (LBO), created and curated by our colleagues at Iowa State University:
![Screenshot (1078)_cropped](https://github.com/EBISPOT/ols4/assets/79228708/c1c888f8-b99c-4c93-a85d-2a5e596e27eb)
This clearly shows the top level of the LBO (labelled "Breed" but really meaning "Species"), including an alphabetical list of all the LBO species, each item having a + sign indicating that it can be expanded to show all items in the next level of the hierarchy.
In contrast, the default OLS3 view of the VBO is:
![Screenshot (1080)_cropped](https://github.com/EBISPOT/ols4/assets/79228708/5b8a7185-c97b-4069-8d21-f458d352bea7)
Unlike the LBO default view, this view gives no indication of the structure of the VBO.
Is it possible to arrange for the default view of the VBO to be analogous to the default view of the LBO?
There are several other enhancements that would be much appreciated, but it is probably best to start with just this one.

**Comment by matentzn** [comment]
We can do that; but this is something that needs to be done on our side (VBO), not OLS. OLS just Displays whatever we give them, if we want something else to be displayed, we need make some changes to the ontology. But it's not that problematic in this case I think. If you make a new ticket at the VBO repo to "add preferred roots for OLS" and mention me I can deal with that, and OLS will automatically show the roots we told it to.

**Comment by franknic** [comment]
Thank you very much, Nico!

**Comment by jamesamcl** [comment]
Closing as this appears to be upstream issue
