### ISSUE TITLE
OLS4 questions regarding ORDO

### ISSUE THREAD

**Issue by Orphanet** [EBISPOT/ols4#347]
Dear all, 
Nice work for the new OLS4

I was testing https://www.ebi.ac.uk/ols4/ontologies/ordo and it's good to see it updated here.

Nevertheless, I have 2 questions :

1) Redirection
Will those links will be maintened/ redirected ?
ex:
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http://www.orpha.net/ORDO/Orphanet_730
=>
https://www.ebi.ac.uk/ols4/ontologies/ordo/terms?iri=http://www.orpha.net/ORDO/Orphanet_730

2) Inferred view
With previous version, when displaying the "group of disorders" class, the OLS was showing the inferred view of it (which was useful to display the classifications tree)

the new version display a list of concepts within the class "group of disorders" and partial trees.
(I assume based on subclass of relation. Did "part of" also considered ?

For this one, I assume the issue could be also on our side with this version of ORDO.
Still, is the display mechanism will be different between OLS and OLS4 regarding the trees / inferred views ?

Best regards,

**Comment by jamesamcl** [comment]
1. Yes we will maintain both links indefinitely to ease the transition. One will redirect to the other when OLS3 is taken down, at which point it won't matter which one you use.

2. To avoid adding unintended axioms, we assume any reasoning has already taken place. So you should provide a pre-reasoned version of your ontology for us to index as OLS will not do any reasoning.

> the new version display a list of concepts within the class "group of disorders" and partial trees.
(I assume based on subclass of relation. Did "part of" also considered ?

Yes "part of" is considered. You can see lots of examples of it in the link you provided https://www.ebi.ac.uk/ols4/ontologies/ordo/terms?iri=http://www.orpha.net/ORDO/Orphanet_730 : we recently added the "P" icon to denote part of.
