### ISSUE TITLE
No global search results but autosuggestion works

### ISSUE THREAD

**Issue by EliotRagueneau** [EBISPOT/ols4#348]
Regarding MI ontology, when searching for a term such as MI:0316 like in the following screenshot, the website shows no results. 
![Screenshot 2023-05-15 at 11 17 18](https://github.com/EBISPOT/ols4/assets/42945601/dc5c0a52-af6b-488f-82a6-dabe7213559f)

However, the autosuggestions is able to pickup on the correct instance as you can see in the screeenshot.
![Screenshot 2023-05-15 at 11 12 23](https://github.com/EBISPOT/ols4/assets/42945601/52e2620c-ac42-4377-b827-8b593a5c072a)

And the term is well in OLS as you can see:
![Screenshot 2023-05-15 at 11 17 44](https://github.com/EBISPOT/ols4/assets/42945601/6f09b727-5d21-4cfa-b957-38e05d5c47e8)

**Comment by jamesamcl** [comment]
This is fixed now, thanks!

**Comment by EliotRagueneau** [comment]
Thanks for having fixed that this quickly!
