### ISSUE TITLE
Source ontologies missing from results

### ISSUE THREAD

**Issue by daniwelter** [EBISPOT/ols4#350]
It seems that classes that are reused in other ontologies only show up in search results for the reuse ontologies, not for the source ontologies, eg search for "ancestry category" "(HANCESTRO:0004) returns results for that class in EFO, OBIB, FoodOn and RBO but not HANCESTRO itself. "breast cancer" (MONDO:0007254) shows the term in EFO, CPONT, OBA and others but not for MONDO. For the first search, "HANCESTRO" doesn't show in the list of ontologies. For the 2nd, "MONDO" does but if selected, only returns for breast cancer-related terms imported into MONDO from HP, Uberon etc.  Similar experience with other terms and ontologies. I haven't been able to find a native term that isn't reused in another ontology so can't comment in that scenario.

Is this expected behaviour? If yes, could this please be explicitly documented somewhere because it's a change from the old OLS?

**Comment by jamesamcl** [comment]
I think this, #348, and #343 are all the same issue and should be fixed once #349 is deployed.

**Comment by jamesamcl** [comment]
This should be fixed now, can you confirm?

**Comment by daniwelter** [comment]
Yes, can confirm the behaviour is now as expected. Thank you!
