### ISSUE TITLE
Direct links to entries on OLS4 vs OLS3

### ISSUE THREAD

**Issue by renatocjn** [EBISPOT/ols4#351]
Hello,

I'm currently a curator for the identifiers.org registry and I'm looking into migrating our URL patterns to OLS4 from OLS3. We currently use URLs that rely on the `short_form` and `obo_id` URL parameters to redirect users to specific entries in ontologies. For example:
- https://www.ebi.ac.uk/ols/ontologies/sio/terms?short_form=SIO_000276
- https://www.ebi.ac.uk/ols/ontologies/envo/terms?obo_id=ENVO:09200010

My problem is that when I replace the "ols" with "ols4" in these URLs, the specific entry (SIO_000276 or ENVO:09200010) is not shown in the resulting page, they are rather hidden in the tree view.

My question is if these parameters are still supported in OLS4 and if there there is another way to link directly to entries in OLS4.

Best

**Comment by jamesamcl** [comment]
Thanks for reporting!

@serjoshua To fix this we need to implement `/classes?short_form=xxxx` where `short_form` maps to `shortForm` in the API call. Similarly `obo_id` should map to `oboId`.

**Comment by renatocjn** [comment]
Thank you for the quick reply. I suppose you plan to adjust the code to support these parameters?

I guess you wish to support all features of OLS3, but on my side, I'm happy to use any existing alternative if that is easier for you.

**Comment by jamesamcl** [comment]
We would like OLS4 to be a drop-in replacement to OLS3 wherever possible, so we're very happy to fix these issues!

**Comment by serjoshua** [comment]
Yes, I believe this is already our opportunity to implement a catch-all frontend routing to call corresponding backend APIs. Will keep you posted regarding this matter. Thanks for raising this issue.

**Comment by serjoshua** [comment]
OLS4 pages are now accessible using obo_id and short_form parameters. Let us know if you experience any issues.

**Comment by renatocjn** [comment]
Works great, thank you.

One small question, I see that the end of the URL is rewritten from terms to classes. I assume this is done via JS since there is no 3xx response. Would it be best to keep using "terms" or change our URL patterns to end with "classes"?

**Comment by serjoshua** [comment]
@renatocjn initially, we implemented /terms to always redirect to /classes. Now, we use /terms as an agnostic endpoint wherein frontend users can use to pass IDs that could be a property, a class or an individual and it will redirect to /properties, /classes or /individuals, respectively. OLS4 is actively trying to adapt and at the same be as compatible as it can be to previous OLS. We actually do not have any concrete answers when you posted your last question but now we do 😄 Hopefully, this helps. Also, feel free to raise tickets whenever you see issues in OLS4 you deem important.
