### ISSUE TITLE
Future support of ebi.ac.uk/ols4 URL

### ISSUE THREAD

**Issue by EliotRagueneau** [EBISPOT/ols4#352]
Hi,

We would like to do the migration from OLS 3 to OLS4 as you recommended us to do, however we are not sure if https://ebi.ac.uk/ols4 will stay the URL after you retire OLS3, or if you will replace https://ebi.ac.uk/ols4 by https://ebi.ac.uk/ols.

I'm asking this because we would like to avoid having to change twice in a row the URL we are pointing to. 

Ideally you could maybe keep both url, and just make one redirect to the other, so that we can start updating our tech stack to the new OLS4 and not have to update it again once you deprecate OLS3

**Comment by jamesamcl** [comment]
There will definitely be a redirect, but we haven't decided whether it will be from ols4->ols or ols->ols4. Either way, both URLs will still work.

**Comment by EliotRagueneau** [comment]
Perfect thanks !
