### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#354]
https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0003692

depiction_of should be embedded as an image like in OLS3

**Comment by jamesamcl** [comment]
I haven't tested this but I wonder if we should show a thumbnail that can be clicked to show the image in a lightbox kinda thing? Otherwise the images will either be too big (making it impossible to read the properties) or too small (can't see the image)

I believe @dosumis has use cases for this feature

**Comment by dosumis** [comment]
Looks like this is broken in OLS3 - but it used to show all images if linked via FOAF:depicted_by   We have many examples of this in Uberon, curated for the purpose of showing on OLS and with Protege plugin.  I am likely to have many examples in future (e.g. large number of images  coming from HubMap.

**Comment by serjoshua** [comment]
More examples would be really nice. With that said, I checked OLS4 just now and the fix has been deployed. Would you prefer to create a separate ticket to implement the lightbox/popup/viewer thing, if finalized? If yes, I would consider this issue closed.

<img width="1274" alt="Screen Shot 2023-05-22 at 12 19 14 PM" src="https://github.com/EBISPOT/ols4/assets/25520595/f80ef2ad-9294-4dcd-9585-861aa6df17e0">

**Comment by jamesamcl** [comment]
Thanks @serjoshua - this is great progress

I think the images should be promoted to the grey box area at the top (below "also appears in" in your screenshot); and omitted from the class information box. They should be displayed as clickable thumbnails with a lightbox on click. We can leave this issue open until then.
