### ISSUE TITLE
Is OLS the correct Github for submitting inaccurate or missing cross-references across multiple ontologies?

### ISSUE THREAD

**Issue by ssyeds3** [EBISPOT/ols4#355]
The NCI Cancer Research Data Commons (CRDC) Program (https://datacommons.cancer.gov/) is developing data standards for submitting data to the CRDC ecosystem. As part of this effort, the CRDC Data Standards Service (DSS) Team is identifying industry standards that can be leveraged for this harmonization and standardization effort. 

In the process of mapping valid values across Uberon (and other ontologies) and NCIt we (the DSS Team) came across terms in several OLS ontologies that either did not have a cross-reference to NCIt terms or that we thought did not cross-reference to the correct NCIt term. Is OLS the correct Github to raise these questions or should we be trying to contact the individual ontologies? If the latter, could you direct us to what GitHub?

**Comment by matentzn** [comment]
@ssyeds3 the right place to make these issues is on the issue trackers of the respective ontology. On OLS4, you can see the "Issue Tracker" button on the right: 
<img width="885" alt="image" src="https://github.com/EBISPOT/ols4/assets/7070631/5aa8d524-4e34-47a5-8fe7-8707e3d282b7">

Making such issues is an amazing help for the community and make our ontologies better!

**Comment by cthoyt** [comment]
pages for each ontology indexed in the OLS have lots of information on how to get in touch with the people who curate that resource. For example, the OLS page for UBERON (https://www.ebi.ac.uk/ols4/ontologies/uberon) links to the homepage, mailing list, and issue tracker for UBERON

@ nico jinx

**Comment by ssyeds3** [comment]
Thank you both, this information really helps! We have been back and forth with Uberon, but wanted to make sure we had all the correct Githubs for the other ontologies and were addressing them in the correct space.
