### ISSUE TITLE
Using obo_id as parameter is not returning results

### ISSUE THREAD

**Issue by serjoshua** [EBISPOT/ols4#357]
When trying to access the term ENVO:09200010 using `obo_id` through v2/api, it returns 0 (zero) elements:
https://www.ebi.ac.uk/ols4/api/v2/ontologies/envo/classes?oboId=ENVO%3A09200010
![Screen Shot 2023-05-17 at 12 47 46 PM](https://github.com/EBISPOT/ols4/assets/25520595/db5b7e37-ebd0-4f98-a04c-a7d74fb74f02)

But when accessing using `short_form`, it returns one:
https://www.ebi.ac.uk/ols4/api/v2/ontologies/envo/classes?shortForm=ENVO_09200010
![Screen Shot 2023-05-17 at 12 52 56 PM](https://github.com/EBISPOT/ols4/assets/25520595/c79ee8d6-2598-4256-9267-f54641e21148)

**Comment by jamesamcl** [comment]
Ah - it’s because oboId is now called curie in OLS4

**Comment by serjoshua** [comment]
I see. I will create a utility function for these cases. Right now, we only have a function to convert underscores to camel case.
