### ISSUE TITLE
Implement properties information and relations boxes

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#36]

**Comment by jamesamcl** [comment]
Information seems implemented

<img width="1113" alt="Screenshot 2023-01-11 at 01 55 32" src="https://user-images.githubusercontent.com/454895/211699968-aae66da3-57d5-4d22-baef-064bc07a34d7.png">

this property has no relations in OLS3 so need to find another one to check

**Comment by serjoshua** [comment]
So far we can handle **Equivalent** properties and **Subproperties**. I checked OLS3 and it has code for "Instances" and "Related From" which I am not sure if they are even valid Property relations.

**Comment by jamesamcl** [comment]
They are not valid property relations as far as I know. Think we can close this one then.
