### ISSUE TITLE
API calls on id using underscore should work

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#366]
Example:
On OLS3 this worked: https://www.ebi.ac.uk/ols/api/ontologies/efo/hierarchicalDescendants?id=EFO_0000305
On OLS4 this is giving an error: https://www.ebi.ac.uk/ols4/api/ontologies/efo/hierarchicalDescendants?id=EFO_0000305

**Comment by udp** [comment]
I guess id should search both `shortForm` (underscores) and `curie` (colon).

**Comment by jamesamcl** [comment]
We don't have anything called `id` in ols4. We have `curie` which is semicolon delimited and `shortForm` which is underscores. So maybe `id` should map to `shortForm`.

**Comment by serjoshua** [comment]
Found the culprit. `getOneById(ontologyId, id, lang)` for the following endpoints pass parameters as (ontologyId, lang, id) instead of (ontologyId, id, lang). Committing changes in a few.

- /{onto}/children
- /{onto}/descendants
- /{onto}/hierarchicalChildren
- /{onto}/hierarchicalDescendants

**Comment by serjoshua** [comment]
Just to add, after doing the fix in my local. Using `iri` and `id` with the class IRI as value returns 44 elements for hierarchicalDescendants:

_PATH_
/api/ontologies/efo/hierarchicalDescendants?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000305
/api/ontologies/efo/hierarchicalDescendants?id=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000305

_RESPONSE_
> {
>   "_embedded": {
>     "terms": [ ... ]
>   },
>   "_links": { ... },
>   "page": {
>     "size": 20,
>     "totalElements": 44,
>     "totalPages": 3,
>     "number": 0
>   }
> }

As for `oboId`, `curie` and `shortForm`, they all return empty data for hierarchicalDescendants:

_PATH_
/api/ontologies/efo/hierarchicalDescendants?curie=EFO:0000305
/api/ontologies/efo/hierarchicalDescendants?oboId=EFO:0000305
/api/ontologies/efo/hierarchicalDescendants?shortForm=EFO_0000305

_RESPONSE_
> {
>   "_links": { ... },
>   "page": {
>     "size": 0,
>     "totalElements": 0,
>     "totalPages": 1,
>     "number": 0
>   }
> }
