### ISSUE TITLE
"synonym" show both exact and no-exact synonym

### ISSUE THREAD

**Issue by sabrinatoro** [EBISPOT/ols4#368]
The synonyms shown on a term page include both exact and non-exact synonyms, and there is no indication on which one is exact or not. This is confusing and misleading. 

For examples: 
[Alzheimer disease](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004975) :
"Alzheimer disease, familial" is a "narrow synonym" in Mondo, and should not be considered exact 

[hemangioma ](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0006500):
'angioma' and 'benigh angioma' are 'related synonym' and should not be considered exact.

**Proposal**: 
- Only show exact synonym in the term box on top of the page
- show the not-exact synonym in the "class information" on the right side of the page.

**Comment by henrietteharmse** [comment]
#369

**Comment by cmungall** [comment]
Any progress on this? Synonym scopes are used broadly by many OBO ontologies - GO, Mondo, Uberon, ENVO, CL, ...

OLS shows axiom annotations on mouseover which is great, but the actual predicate is 100x more important for most people!!

Also I think this is unrelated to 369 which can be closed.

**Comment by matentzn** [comment]
Thanks for resurfacing this! Very important indeed!

**Comment by sbello** [comment]
Any progress on this? It would be a very useful feature.

**Comment by matentzn** [comment]
Bumping the importance of this again, I have a lot of discussions with curators that are confused by this!

**Comment by haideriqbal** [comment]
Fixed in OLS now. Synonym would appear as they are curated in ontology file
![Screenshot 2024-11-26 at 12 34 52](https://github.com/user-attachments/assets/86854443-cf76-49e1-a6b3-fb70f8e5fa48)

**Comment by matentzn** [comment]
this is awesome thank you @haideriqbal
