### ISSUE TITLE
Implement individual information and relations boxes

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#37]

**Comment by jamesamcl** [comment]
Seems ok (OLS3 right)

Interestingly OLS4 picks up on the "Different from" relations while OLS3 doesn't.

The tree view is broken in OLS4 but will open a separate issue for that.

<img width="2171" alt="Screenshot 2023-01-11 at 03 15 27" src="https://user-images.githubusercontent.com/454895/211709647-0916bcbd-cdbc-449a-9dda-d1a6a3fd5c0d.png">
