### ISSUE TITLE
Part of icon not available for the tree view in OLS4

### ISSUE THREAD

**Issue by helenp** [EBISPOT/ols4#370]
Hi team,
the OLS3 visualisation displays a 'P' for partonomy. Not seen in OLS4. I find this helpful feature. Could it be ported across?
Also:
When the graph is visualised if there is no is-a then a single node is alone. Could partonomy be on by default. Especially important to have this for anatomy ontologies. Possible to easily configure?
Nothing urgent here, 
thanks
Helen

**Comment by jamesamcl** [comment]
Thanks Helen,

David reported this too in #273. Will close this one to avoid duplicating the ticket.
