### ISSUE TITLE
DC Vocab should be terms, not elements

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/ols4#372]
Right now, the DC vocab in OLS is the old, "elements" namespace:

http://purl.org/dc/elements/1.1/creator

See here how Dublin Core itself talks about this: https://www.dublincore.org/specifications/dublin-core/dcmi-terms/

> http://purl.org/dc/terms/ The /terms/ namespace was originally created in 2001 for identifying new terms coined outside of the original fifteen-element Dublin Core. In 2008, in the context of defining formal semantic constraints for DCMI metadata terms in support of RDF applications, the original fifteen elements themselves were mirrored in the /terms/ namespace. As a result, there exists both a dc:date (http://purl.org/dc/elements/1.1/date) with no formal range and a corresponding dcterms:date (http://purl.org/dc/terms/date) with a formal range of "literal". While these distinctions are significant for creators of RDF applications, most users can safely treat the fifteen parallel properties as equivalent. The most useful properties and classes of DCMI Metadata Terms have now been published as [ISO 15836-2:2019](https://www.iso.org/standard/71341.html) [ISO 15836-2:2019]. While the /elements/1.1/ namespace will be supported indefinitely, DCMI gently encourages use of the /terms/ namespace.

In OBO and everywhere, we are trying hard to get [rid of the elements namespace](https://github.com/information-artifact-ontology/ontology-metadata/issues/54). It would be good of OLS could help promoting that as well!

**Comment by jamesamcl** [comment]
We load dcterms too:

https://www.ebi.ac.uk/ols4/ontologies/dcterms

We have to load both to resolve all the IRIs, as ontologies use both. Maybe we need a way to mark one as deprecated.

**Comment by matentzn** [comment]
Ahh ok! Thanks for the clarification. if the ontology would have been called DCE I might have thought about looking, but doesn't matter. Thanks for the clarification @udp!
