### ISSUE TITLE
Exact match not boosted enough

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#377]
I searched L-arabinose and got lots of non exact matches before the exact match in chebi

https://www.ebi.ac.uk/ols4/search/l-arabinose

<img width="867" alt="Screenshot 2023-06-02 at 01 42 43" src="https://github.com/EBISPOT/ols4/assets/454895/e38ab9e6-9b9c-42d1-b169-607be2bee48e">

**Comment by henrietteharmse** [comment]
There do not seem to be any exact matches for this [https://www.ebi.ac.uk/ols4/search?q=L-arabinose&exactMatch=true](query. 
https://www.ebi.ac.uk/ols4/search?q=L-arabinose&exactMatch=true) seems provide the desired result.
