### ISSUE TITLE
Review existing UI components

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#38]
OLS3 provided a number of UI components that people rely on. These will need to be replaced in OLS 4 

[Auto complete](https://github.com/EBISPOT/OLS-autocomplete)
[Tree view](https://github.com/EBISPOT/ols-tabbed-term-treeview) 
[Graph view ](https://github.com/EBISPOT/OLS-graphview) - See [example](https://www.ebi.ac.uk/ols/ontologies/efo/terms/graph?iri=http://purl.obolibrary.org/obo/UBERON_0002107)

**Comment by udp** [comment]
I suppose we can factor these out of the OLS4 frontend and make them separate libraries on which OLS4 itself depends. Then other people can also depend on them.

**Comment by jamesamcl** [comment]
Lots of activity on this in #27. Autocomplete and tree view seem to be working with OLS4. I have added to this repo a `legacy-plugins-test` directory with a HTML file that embeds all of the components so we can check easily.

I am currently working on the APIs for graph view which should be ready to go shortly.

**Comment by jamesamcl** [comment]
These all now work unmodified with OLS4. You can test by starting up a local OLS4 instance and loading the `legacy-plugins-test/test.html` in a browser.
