### ISSUE TITLE
search API: fieldList parameter has no effect? (Want to be able to return synonyms)

### ISSUE THREAD

**Issue by marius-mather** [EBISPOT/ols4#381]
Currently it does not seem to be possible to change the fields that are returned for each item in the search results with the `fieldList`, e.g. there is no difference between:

* https://www.ebi.ac.uk/ols4/api/search?q=cow&ontology=ncbitaxon&queryFields=label,synonym
* https://www.ebi.ac.uk/ols4/api/search?q=cow&ontology=ncbitaxon&queryFields=label,synonym&fieldList=iri,obo_id

My main use case for this is I sometimes need to return the `synonym` field in search results. In the past I've also made use of the ability to return arbitrary annotations with `fieldList=has_exact_synonym_annotation`, is that functionality going to be preserved?

**Comment by marius-mather** [comment]
Thanks, the fieldList option now controls the fields that come back in search results. Will returning synonyms (by including "synonym" in the fieldList) be possible in the search API? If not I will have to rewrite some code for API calls I'm doing.

**Comment by serjoshua** [comment]
Good day Marius, sadly we currently don't support including synonyms. We have the folllowing fields supported though:
- iri
- ontology_name
- label
- description
- short_form
- obo_id
- is_defining_ontology
- type

**Comment by jamesamcl** [comment]
Does synonyms work in OLS3? If so it needs to be implemented in OLS4…

**Comment by marius-mather** [comment]
Yes, `synonym` was supported in the `fieldList` option for searches in OLS3 (although maybe not documented that well) - I am currently just trying to adapt existing code that uses OLS3 and get all the API calls working in OLS4.

**Comment by serjoshua** [comment]
Implemented support for "synonym" in fieldList of select and search endpoints. We'll just have to wait for the next code deployment for the changes to reflect.

<img width="665" alt="Screen Shot 2023-06-15 at 1 32 26 PM" src="https://github.com/EBISPOT/ols4/assets/25520595/bf1b5f91-88c0-4850-aa49-7f53f09df9ce">
<img width="798" alt="Screen Shot 2023-06-15 at 1 34 35 PM" src="https://github.com/EBISPOT/ols4/assets/25520595/9f3b6164-d82a-427e-92bc-0d0d071e9bd5">
<img width="798" alt="Screen Shot 2023-06-15 at 1 36 46 PM" src="https://github.com/EBISPOT/ols4/assets/25520595/39943585-0d31-4d62-9e37-ec90afd7862f">
