### ISSUE TITLE
select result different in OLS4

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#389]
from Slack:

I noticed a discrepancy between the number of records being returned in the old API as compared to the new one.
This is the old endpoint we are using on our legacy systems:
[https://www.ebi.ac.uk/ols/api/select?type=class&ontology=edam&sort=label%20desc&row[…]00&q=data&allChildrenOf=http://edamontology.org/operation_0004](https://www.ebi.ac.uk/ols/api/select?type=class&ontology=edam&sort=label%20desc&rows=1000&q=data&allChildrenOf=http://edamontology.org/operation_0004)
and this a the same query string, but using ols4 instead of 3:
[https://www.ebi.ac.uk/ols4/api/select?type=class&ontology=edam&sort=label%20desc&ro[…]00&q=data&allChildrenOf=http://edamontology.org/operation_0004](https://www.ebi.ac.uk/ols4/api/select?type=class&ontology=edam&sort=label%20desc&rows=1000&q=data&allChildrenOf=http://edamontology.org/operation_0004)
Notice that the older API returns 36 records, where as the newer one returns 27

**Comment by jamesamcl** [comment]
Copying docs for select API so we can check the options are implemented properly

<img width="991" alt="Screenshot 2023-06-12 at 13 52 30" src="https://github.com/EBISPOT/ols4/assets/454895/2b70492a-6ea0-4fdf-9dfd-53957087410d">

**Comment by jamesamcl** [comment]
There also seem to be fields missing in the default OLS4 response, e.g.

OLS3:

```json
{"id":"edam:class:http://edamontology.org/operation_0227",
"iri":"http://edamontology.org/operation_0227",
"short_form":"operation_0227",
"obo_id":"operation:0227",
"label":"Indexing",
"ontology_name":"edam",
"ontology_prefix":"EDAM",
"type":"class"},
```

OLS4

```json
{"iri":"http://edamontology.org/operation_0227",
"id":"edam:class:http://edamontology.org/operation_0227",
"label":"Indexing",
"type":"class"},
```

**Comment by serjoshua** [comment]
We are already getting the expected results from OLS4 API. Field discrepancies are either fixed or alread raised in a separate issue.
