### ISSUE TITLE
Add API call to return all obsolete classes, properties and individuals for a given ontology.

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#391]
I thought we already had such API, but seems like I am mistaken.

**Comment by jamesamcl** [comment]
Should be as simple as adding a flag to the `OntologyTermController` and the corresponding repository.

**Comment by henrietteharmse** [comment]
Ignore the list of ontologies as the `OntologyTermController` does not support a list of ontologies.
