### ISSUE TITLE
Mondo Version update? 

### ISSUE THREAD

**Issue by kanems** [EBISPOT/ols4#396]
OLS4 is still showing mondo Version 2023-05-01, but Mondo released version 2023-06-01 two weeks ago: https://github.com/monarch-initiative/mondo/releases/tag/v2023-06-01 
When will the newest version be uploaded to OLS4?

**Comment by serjoshua** [comment]
We had our data release for OLS4 just today. Our automated deployment has been halted because of some needed improvements for a smoother deployment process. Thank you for your patience.
