### ISSUE TITLE
Add Semantic Mapping Vocabulary to OLS

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/ols4#402]
https://raw.githubusercontent.com/mapping-commons/semantic-mapping-vocabulary/main/semapv.owl

I am happy to fill in whatever table or form is needed, also edit the metadata directly to reduce effort for you, just say the word!

**Comment by jamesamcl** [comment]
You can just open a PR directly to: https://github.com/EBISPOT/ols4/blob/dev/ebi_ontologies.json 

this is used by the dataload
