### ISSUE TITLE
Promote term replaced by/obsolete to top of page

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#411]
To help curators, when a term is obsolete we should show it as a warning banner at the top of the term page, ideally with a link to the replacement where available.

**Comment by matentzn** [comment]
Great idea. And ideally, the banner should be very prominent, as in: make the whole background red.

**Comment by serjoshua** [comment]
Sample deprecated entities we tested:
![Screen Shot 2023-07-06 at 3 46 28 PM](https://github.com/EBISPOT/ols4/assets/25520595/75ca4e11-811f-40c6-8a1f-e974df5b6d81)
![Screen Shot 2023-07-06 at 5 23 16 PM](https://github.com/EBISPOT/ols4/assets/25520595/ad9e5e64-8b4e-4cee-a6d9-0c7c0ceab168)
![Screen Shot 2023-07-06 at 5 23 48 PM](https://github.com/EBISPOT/ols4/assets/25520595/caf4d934-c056-437d-a61b-070256603ad6)
![Screen Shot 2023-07-06 at 5 24 08 PM](https://github.com/EBISPOT/ols4/assets/25520595/932a662e-a9a5-46a7-a197-fe9b0bdf28e3)
![Screen Shot 2023-07-06 at 5 24 23 PM](https://github.com/EBISPOT/ols4/assets/25520595/58f0b097-1b4d-46f0-a188-9ae28c2e08c1)

**Comment by matentzn** [comment]
This is fantastic:

https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0035448

Anything we can do about the obsoletion reason up top? It says "object: Object"

**Comment by serjoshua** [comment]
Oops. We might have to add logic when handling JSON object or reified(? @udp) data. I think most of the reason data are in string format. I will create a separate ticket for this bug. Thank you for testing @matentzn.
