### ISSUE TITLE
XML parsing errors when using the API in browser: API responses may need a Content-Type header set

### ISSUE THREAD

**Issue by marius-mather** [EBISPOT/ols4#417]
While testing out the OLS4 API I was seeing a lot of `XML Parsing Error: not well-formed` errors in my browser console, this was confusing as I had set the `Accept: application/json` header and seemed to be getting JSON returned.

It [looks like this can be solved](https://stackoverflow.com/questions/51347771/got-xml-parsing-error-not-well-formed-when-i-expect-json) by ensuring the server sets a `Content-Type: application/json` header on the response.

**Comment by serjoshua** [comment]
Hello @marius-mather, may we know what endpoints you are accessing?

**Comment by marius-mather** [comment]
Yes, sorry, I should have specified originally. I'm seeing this with the search endpoint, e.g. <https://www.ebi.ac.uk/ols4/api/search?q=hamster&ontology=ncbitaxon&rows=10&queryFields=label,synonym&fieldList=iri,obo_id,label,synonym>, I'm not sure if I've done an exhaustive test of the different endpoints.

For a quick way to check, Firefox displays response with the correct Content-Type header in a nice JSON explorer view, e.g. <https://www.ebi.ac.uk/ols4/api/ontologies/ncbitaxon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCBITaxon_9913/>, whereas without the header the result is just shown in plain text.
