### ISSUE TITLE
http 500 response on 'select'

### ISSUE THREAD

**Issue by amnonkhen** [EBISPOT/ols4#418]
I am trying to port my app from ols3 to ols 4.
The following `select` operation fails:
`https://www.ebi.ac.uk/ols4/api/select?groupField=iri&start=0&q=*&rows=30&ontology=hcao&ontology=uberon`.
It also happens for other values of the `ontology` parameter.

Initiaal investigation:
1. It seems the `*` value of the `q` param is causing the problem. When I change it with some other string, e.g. `BFO_0000023` it works well.
2. `q=*` results in the correct response when adding `local=true`

**Comment by henrietteharmse** [comment]
Done
