### ISSUE TITLE
Get search results in home page does not work

### ISSUE THREAD

**Issue by serjoshua** [EBISPOT/ols4#42]
There are two promises being fulfilled to retrieve search results for the home page search. The /api/v2/entities?search=**&size=10 API returns 500 error, while /api/v2/ontologies?search=**&size=3 API resolves but seems like an empty response.

![Screen Shot 2022-10-18 at 12 02 14 PM](https://user-images.githubusercontent.com/25520595/196412524-d821af3c-07fb-436f-92dd-9421ed790d42.png)

**Comment by jamesamcl** [comment]
@serjoshua Can you confirm if this is fixed?

**Comment by serjoshua** [comment]
Yes it is. I will raise a separate ticket if there are any issues encountered.
