### ISSUE TITLE
Plant Ontology not listed when searching, not updating? 

### ISSUE THREAD

**Issue by cooperl09** [EBISPOT/ols4#421]
We have recently published a new release of the Plant Ontology, but it is not showing up on the new site when I search for it.

I was able to locate it at: https://www.ebi.ac.uk/ols4/ontologies/po

It also is not updating with the new release published 7-13-23.  

You can compare to: https://obofoundry.org/ontology/po.html

**Comment by henrietteharmse** [comment]
Updated
![image](https://github.com/EBISPOT/ols4/assets/32327979/829bd53e-20a5-4884-ad62-d10d849ce6e4)
![image](https://github.com/EBISPOT/ols4/assets/32327979/68cdd487-bf5b-4395-935d-d01a4a06e879)
