### ISSUE TITLE
PECO and TO are both displaying incorrect version

### ISSUE THREAD

**Issue by cooperl09** [EBISPOT/ols4#422]
Re:  https://www.ebi.ac.uk/ols4/ontologies/peco
https://www.ebi.ac.uk/ols4/ontologies/to

Newly released version was uploaded yesterday, but is still showing the old date:
PECO Version 2020-08-21
TO: Version 2022-04-13

Thanks

**Comment by henrietteharmse** [comment]
Yes, please allow at least 48 hours for OLS to complete existing data load, then pick up latest changes and then to process the latest changes.

**Comment by cooperl09** [comment]
Thanks, looks good now
