### ISSUE TITLE
500 response from terms endpoint

### ISSUE THREAD

**Issue by apriltuesday** [EBISPOT/ols4#424]
While testing OLS4 migration I found the following endpoint returning a 500:
https://www.ebi.ac.uk/ols4/api/terms?iri=http://purl.obolibrary.org/obo/HP_0002180

vs. response from OLS3:
https://www.ebi.ac.uk/ols/api/terms?iri=http://purl.obolibrary.org/obo/HP_0002180

Not sure if this is an isolated incident, other terms e.g. https://www.ebi.ac.uk/ols4/api/terms?iri=http://purl.obolibrary.org/obo/HP_0002181 seem to work fine.

Thanks in advance for addressing this, and other issues I've opened.

**Comment by henrietteharmse** [comment]
https://www.ebi.ac.uk/ols4/api/ontologies/ado/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FADO_0000007
