### ISSUE TITLE
Inconsistent Term model 

### ISSUE THREAD

**Issue by EliotRagueneau** [EBISPOT/ols4#425]
There are inconsistencies in your models depending on the endpoint you are querying for, specially between `search` and `terms` 
e.g.  https://www.ebi.ac.uk/ols4/api/terms?id=MI_2190 and https://www.ebi.ac.uk/ols4/api/search?q=MI_2190

| terms | search |
| ------ | ------- |
| synonyms[] | synonym[] |
| short_form | short_form[] |
| label | label[] |
| obo_id | obo_id[] |

Apart from synonym _s_ the other changes are coming with the new OLS 4 release, and where not present in the previous version as you can see at https://www.ebi.ac.uk/ols/api/search?q=MI_2190 . 

I would therefore propose to homogenise the model across the different endpoints, either with the new model if needed, or with the previous one (preferably) to avoid having to change client side implementation

**Comment by EliotRagueneau** [comment]
I didn't see this issue, but it is basically a duplicate of https://github.com/EBISPOT/ols4/issues/407, except for the synonym

**Comment by EliotRagueneau** [comment]
Temporary workaround if using Java and Jackson to map results:
```java
ObjectMapper mapper = new ObjectMapper()
                .configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
```

This allows Jackson to handle singular values as Arrays containing only one item if there is a mismatch between the declared type, and the actual answer from the API.
e.g. if label is defined as `label[]` but is actually a single value `label`, then it is going to populate label the following way instead of failing:
```json
{
 "label": "EXEMPLE"
}
```

```java
 private List<String> label = List.of("EXEMPLE")
```

**Comment by jamesamcl** [comment]
@henrietteharmse this should be an easy fix, it's because the search endpoint uses solr directly.

Change e.g. this line to getFirstString to fix short_form: https://github.com/EBISPOT/ols4/blob/dev/backend/src/main/java/uk/ac/ebi/spot/ols/controller/api/v1/V1SearchController.java#L226

**Comment by henrietteharmse** [comment]
The "synonymS" vs "synonym" inconsistency is unfortunately not something we can change. This is how it was in OLS3.
