### ISSUE TITLE
Handle deprecation details (e.g., reason) that are not in string format

### ISSUE THREAD

**Issue by serjoshua** [EBISPOT/ols4#428]
https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0035448

Related to #411

**Comment by matentzn** [comment]
Actually, most deprecation reasons should be documented using 
https://www.ebi.ac.uk/ols4/ontologies/omo/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FIAO_0000231

Not as strings, but as individuals from the https://www.ebi.ac.uk/ols4/ontologies/omo:

https://www.ebi.ac.uk/ols4/ontologies/omo/individuals/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FIAO_0000227

Note that you currently cant unfold the Class correctly when navigating to the class and "opening it":  https://www.ebi.ac.uk/ols4/ontologies/omo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FIAO_0000225 (maybe needs new issue)

**Comment by serjoshua** [comment]
Yes, nodes with arrows that don't have children is a separate issue. I think we have some related ones to it. What happens there is that JS tree creation is saying that the node have children but the children API returns an empty result set (when "opening it").

My ontology language is limited but the string I was referring to is the transformed data. The transformed data is in JSON format and that property (reason) could be a literal (string, number) or a JSON object (object, array), etc. I think the property is returning an object/array and we just need to handle it.
