### ISSUE TITLE
Failure downloading ontologies

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#430]
Currently a number of ontologies fail during download (2. Predownload RDF).

1. Create a list of ontologies failing.
2. For each failing ontology determine reason for failure. I.e. temporary (temporary network issue) or permanent (url cannot be accessed).
3. Follow up and create corresponding issues for each of the permanent failures in the corresponding issue trackers.

**Comment by jamesamcl** [comment]
Linking to #1 before closing it

**Comment by serjoshua** [comment]
Please refer to #453 for consolidated information on this issue and #431.
