### ISSUE TITLE
Failure parsing ontologies

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#431]
Convert RDF to JSON fails for a number of ontologies:
1. List failing ontologies.
2. For each failing ontology determine reason for failure. I.e., is it something OLS is not dealing with (OLS) or is it an error in creating the ontology (Provider)
3. For each OLS issue create a related issue.
4. For each provider create a corresponding issue in their issue tracker and reference it here.

**Comment by henrietteharmse** [comment]
genepio already dealt with in #304.

**Comment by jamesamcl** [comment]
#1 did some of this but very old now

**Comment by serjoshua** [comment]
Please refer to #453 for consolidated information on this issue and #430.
