### ISSUE TITLE
OLS3/4 Different API behaviour for term IRIs that are not found

### ISSUE THREAD

**Issue by apriltuesday** [EBISPOT/ols4#435]
Our code sometimes relies on the fact that OLS returns an empty response for term IRIs that are malformed or not found, which is the behaviour in OLS3, e.g.:
* https://www.ebi.ac.uk/ols/api/terms?iri=http://identifiers.org/medgen/C1866239
* https://www.ebi.ac.uk/ols/api/terms?iri=somethingElse

But in OLS4 we seem to get a valid response containing many unrelated terms: 
* https://www.ebi.ac.uk/ols4/api/terms?iri=http://identifiers.org/medgen/C1866239 
* https://www.ebi.ac.uk/ols4/api/terms?iri=somethingElse

It would be preferable for OLS4 to either return no results or perhaps an appropriate error code.

**Comment by jamesamcl** [comment]
@henrietteharmse  This is an important use case for the API
