### ISSUE TITLE
Search not supporting exact match

### ISSUE THREAD

**Issue by EliotRagueneau** [EBISPOT/ols4#436]
Hi,

In the previous API, the exact match was working as you can see here:
[https://www.ebi.ac.uk/ols/api/search?q=liver&queryFields=label,synonym&rows=100&start=0&fieldList=iri,label,short_form,obo_id,ontology_name,ontology_prefix,description,type,score,ontology_iri,is_defining_ontology&exact=true](https://www.ebi.ac.uk/ols/api/search?q=liver&queryFields=label,synonym&rows=100&start=0&fieldList=iri,label,short_form,obo_id,ontology_name,ontology_prefix,description,type,score,ontology_iri,is_defining_ontology&exact=true)

However in the new implementation, it seems this filter is not effective as using the same parameters yields 4808 entries instead of the former 47, see:
[https://www.ebi.ac.uk/ols4/api/search?q=liver&queryFields=label,synonym&rows=100&start=0&fieldList=iri,label,short_form,obo_id,ontology_name,ontology_prefix,description,type,score,ontology_iri,is_defining_ontology&exact=true](https://www.ebi.ac.uk/ols4/api/search?q=liver&queryFields=label,synonym&rows=100&start=0&fieldList=iri,label,short_form,obo_id,ontology_name,ontology_prefix,description,type,score,ontology_iri,is_defining_ontology&exact=true)

In this new API, adding or removing the `exact` parameter doesn't change at all the ouput, letting me think that this filter is indeed just not working.

According to the API v2 you are using on the web page https://www.ebi.ac.uk/ols4/search?q=liver&exactMatch=true , the new results expected is supposed to be 51 when filtering for `exactMatch`, that would be perfectly suitable to my needs: https://www.ebi.ac.uk/ols4/search?q=liver&exactMatch=true

**Comment by EliotRagueneau** [comment]
Sorry to press you on this but when do you think you could fix this issue? 
It's the last bit that prevent ols-client (https://github.com/PRIDE-Utilities/ols-client) to migrate to OLS 4 according to its tests. 
And I'm dependent on this update for some of our projects, because the OLS 3 API does not support synonym search., while OLS4 does.

Thanks a lot for being so reactive on all my issues by the way 😄

**Comment by EliotRagueneau** [comment]
I have performed abt more testing and I realised that actually, exact does work, but not in the same way as before:

- OLS3: exact = full match, case insensitive
- OLS4: exact = partial match, case sensitive

You can see that by comparing previous API results with the following which are using `Liver` instead of `liver`
- OLS3: https://www.ebi.ac.uk/ols/api/search?q=Liver&queryFields=label,synonym&rows=100&start=0&fieldList=iri,label,short_form,obo_id,ontology_name,ontology_prefix,description,type,score,ontology_iri,is_defining_ontology&exact=true
- OLS4: https://www.ebi.ac.uk/ols4/api/search?q=Liver&queryFields=label,synonym&rows=100&start=0&fieldList=iri,label,short_form,obo_id,ontology_name,ontology_prefix,description,type,score,ontology_iri,is_defining_ontology&exact=true

Knowing this, ideally the API should have the same behaviour as before, but maybe you could add another parameter "case_sensitive" which overrides the default behaviour of exact to combine positive aspects of both old and new implementation, while keeping old API as it was

**Comment by serjoshua** [comment]
Made some fixes. We actually had a logic that was overlooked during migration. It involves properly adding a prefix for string fields to return exact matches only. I will try to deploy this change to production the soonest.

**Comment by EliotRagueneau** [comment]
Okay, thanks a lot for your reactivity!
