### ISSUE TITLE
long term name collide with the options box

### ISSUE THREAD

**Issue by arzuozturk** [EBISPOT/ols4#438]
As shown below, some long term names (like abnormal dorsal/ventral axis specification) can collide with the options box.

![image](https://github.com/EBISPOT/ols4/assets/66944690/e0146ee8-cb9a-4a87-8552-05556d37d8b0)

https://www.ebi.ac.uk/ols4/ontologies/fbcv/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FFBcv_0000324?lang=en

Could you please look into this?

Thanks.
Arzu

**Comment by serjoshua** [comment]
Adding comments from @julian-schneider regarding handling this issue when using the tree as a widget.

> Yeah, this is definitely related. When adding the EntityTreeWidget into our widgets storybook the issue becomes more severe, so that the controls overlap the entire tree. So, here for example, "experimental factor" can not be clicked at all:

![pastedImage](https://github.com/EBISPOT/ols4/assets/25520595/31847dde-fe42-44ad-af11-8103bec7d554)

> If this tree was opened, or if the top-level node had a longer label, the entire thing would be wider, and the right-aligned controls would slide over, eventually opening up the nodes for clicking. Which is why we can work around this by wrapping the widget in a div with a min-width of around 600px. If you wanted to make sure that something like this can never happen to your tree, you would need controls that are never in the way, no matter how little space the tree uses. For example by removing the inline `position: absolute` from the controls div [here](https://github.com/EBISPOT/ols4/blob/c961ac9a91a0d72f4be62e7794c0d66c5c7d306b/frontend/src/pages/ontologies/entities/EntityTree.tsx#L318). Then they'd always be above the tree like this:

![pastedImage-1](https://github.com/EBISPOT/ols4/assets/25520595/88e7147f-8ab0-44a9-8ead-c6835a1b18e8)
