### ISSUE TITLE
HANCESTRO gone from OLS4

### ISSUE THREAD

**Issue by daniwelter** [EBISPOT/ols4#451]
HANCESTRO 3.0 was released on Monday. This was a major release with a rename of the source repo and primary branch, and a number of changes to the release artefacts. The configs in the OBO Foundry were updated and the release translated ok to there, and most of the ontology browsers that run off OBO Foundry, but the ontology has disappeared entirely from OLS4 now.

Could you please check what went wrong and what needs to happen for HANCESTRO to get back into OLS?

**Comment by matentzn** [comment]
(Wild guess: the release was done before we changed the PURLS) - all will work on reload.

**Comment by daniwelter** [comment]
It's possible, although both the release and the PURL changes happened on Monday/overnight into Tuesday, and Ontobee/Bioportal picked up (or failed to pick up in the case of Bioportal) the new ontology yesterday. OLS still had v2.8 yesterday afternoon and the ontology was gone when I checked again just now.

**Comment by henrietteharmse** [comment]
Yes, it is due to purl. Should reappear once current OLS data release is complete.

**Comment by daniwelter** [comment]
@henrietteharmse any idea when the current data release will be done? Still no sign of HANCESTRO in OLS

**Comment by serjoshua** [comment]
HANCESTRO is back in OLS4. Thanks everyone for your patience. Feel free to raise a ticket if there are any discrepancies.
