### ISSUE TITLE
subset not returned in search endpoint

### ISSUE THREAD

**Issue by marius-mather** [EBISPOT/ols4#462]
In the OLS3 API it was possible to include `subset` in the `fieldList` parameter of the search endpoint and have it included in results (where available), e.g.:

https://www.ebi.ac.uk/ols/api/search?q=Holstein%20(Horse)&ontology=vbo&queryFields=label,synonym&fieldList=iri,label,synonym,subset

In OLS4 the subset is not in the results, e.g.:

https://www.ebi.ac.uk/ols4/api/search?q=Holstein%20(Horse)&ontology=vbo&queryFields=label,synonym&fieldList=iri,label,synonym,subset

I have also previously used annotations in the `fieldList`, e.g. including `annotations_trimmed` or requesting specific annotations like `exists_in_country_annotation`, but from browsing the issues here it looks like getting annotations into the search results is a separate issue.

**Comment by serjoshua** [comment]
Sharing that `annotations_trimmed` field was discussed in https://github.com/EBISPOT/ols4/issues/395#issue-1757839660
