### ISSUE TITLE
data from OWL API generated files without prefixes are not correctly indexed

### ISSUE THREAD

**Issue by rombaum** [EBISPOT/ols4#475]
I had the issue that an owl file without owl: was not correctly indexed. I took a sample file from our ols3 production instance and wanted to index it in a local ols4 version. The result looks like this:

![only six classes were indexed](https://github.com/EBISPOT/ols4/assets/47030738/2b8d1636-752d-4047-800a-4357fa6bd5bf)
fig. 1 only six classes were indexed

I checked than the owl input file and I recognized that maybe the missing **_owl:_** prefix(see fig. 2) could be the issue.
![owl: prefix is missing](https://github.com/EBISPOT/ols4/assets/47030738/bd771934-d508-4ff4-8540-70968b6f61e8)
fig. 2 owl-class without an _**owl:**_ prefix

I changed that in the file(see fig. 3) and everything worked as expected(see fig. 4).

![owl: prefix is set](https://github.com/EBISPOT/ols4/assets/47030738/bf3194fd-f362-4260-9729-841239d8d773)
fig. 3 owl-class with an _**owl:**_ prefix
![all classes were indexed](https://github.com/EBISPOT/ols4/assets/47030738/c461684d-9701-453c-8f65-bb5fc8f8fb40)

fig. 4 all classes were indexed

The same issue appears also with annotation properties (56 in fig.1 vs. 85 in fig.4). The indexed classes and properties in fig. 1 are from SKOS and probably indexed directed by OLS since the classes are not described in my input file.

By the way the input file was generated with the following .owl API. I could change the file from my side and index everything which is needed for a correct parsing. I'm also not sure if this is really an issue. But I think this documentation could be helpful for other people who has similar .owl files. OLS3 by the way didn't had this restriction in the past.

`<!-- Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi -->`

**Comment by henrietteharmse** [comment]
@rombaum Thank you for logging this. Can you please provide a minimal complete ontology with config illustrating the problem?

**Comment by rombaum** [comment]
@henrietteharmse I added also a small example here in a zip file:

[entities-without-prefix-are-not-indexed.zip](https://github.com/EBISPOT/ols4/files/12399382/entities-without-prefix-are-not-indexed.zip)

The .zip-file contains two .owl-files and their corresponding config file.

Again: You have to change the **path** of **_ontology_purl_** in the config files. I hope the names of the files are self-explanatory.

**Comment by jamesamcl** [comment]
The failing example is valid RDF, but it does not represent an OWL ontology. You can check it here:

https://www.w3.org/RDF/Validator/

I pasted `entities-are-not-imported.owl` into the box and clicked "Parse RDF". Here is the result:

<img width="1386" alt="Screenshot 2023-09-06 at 01 00 09" src="https://github.com/EBISPOT/ols4/assets/454895/3139d727-2966-4dac-a6ae-fc1e76304d7f">

Notice the IRIs like `http://exmpl.org/xmpl/xmpl.owl#AnnotationProperty` which are not OWL IRIs. This is because you omitted the `owl:` prefix in the rdfxml and it defaulted to the xml:base, as per the RDF spec, which was `http://exmpl.org/xmpl/xmpl.owl`.

If this works/worked in OWLAPI it is a bug in OWLAPI.

**Comment by henrietteharmse** [comment]
@rombaum I am closing this as I agree with James' assessment.
Thank you for bringing this to our attention - I agree with you that it is useful for document purposes as someone else is likely to stubble into this issue.
