### ISSUE TITLE
missing ontologies? PRIDE ; UNIMOD

### ISSUE THREAD

**Issue by lcdaugherty** [EBISPOT/ols4#482]
In OLS4 there seems to be some missing ontologies eg: PRIDE and UNIMOD. 
 eg: OLS3 https://www.ebi.ac.uk/ols/ontologies/unimod
OLS4 nothing...

Is there a reason for this? Are there any alternative Peptide ontologies?

**Comment by serjoshua** [comment]
The reason for this is that OLS4 only loads OWL files. UNIMOD and PRIDE seem to use OBO. You could see the list of other ontologies that do not load in OLS4 in this [issue](https://github.com/EBISPOT/ols4/issues/453).

If anyone could provide an ontology PURL that points to an OWL or could provide a copy of an OWL file so we could load locally from our servers, please let us know.

**Comment by lcdaugherty** [comment]
@serjoshua Thank you for the info that makes sense. I am in the early stages of reviewing some data with some specific ontologies in mind, so hopefully the source UNIMOD and PRIDE can provide you with OWL format 
OLS has always been my go to tool  (I am sure I'll eventually get used to the new tree graph view in OLS4...but change is always hard  :)

**Comment by serjoshua** [comment]
You are welcome. Another workaround is to convert the linked OBO files for UNIMOD and PRIDE to OWL (could be inferred or not) then load them from our local server.
