### ISSUE TITLE
Show images from `foaf:depiction` annotation

### ISSUE THREAD

**Issue by anitacaron** [EBISPOT/ols4#487]
We have been using an annotation that never existed, `foaf:depicted_by`. Instead, we should use [foaf:depiction](http://xmlns.com/foaf/0.1/#term_depiction).

Since 2017, we have [an issue](https://github.com/obophenotype/uberon/issues/1364) to change this in Uberon, and many ontologies also use this annotation. We'll soon fix that in Uberon.

In the meantime, in the section "Depicted by", could you load the image from both annotations, please? It would also be good to change the section's name to "Depiction".

**Comment by udp** [comment]
@henrietteharmse this is a high priority issue for OBO/monarch

**Comment by henrietteharmse** [comment]
@anitacaron Can you please provide an OLS example where this is a problem?
