### ISSUE TITLE
Case sensitivity issue with OLS4 search API

### ISSUE THREAD

**Issue by zChxrlie** [EBISPOT/ols4#498]
With the new OLS the search term seems to now be case sensitive.

This result
https://www.ebi.ac.uk/ols4/api/search?q=Liver&rows=10000&fieldList=short_form
returns 995 results, whereas,

https://www.ebi.ac.uk/ols4/api/search?q=liver&rows=10000&fieldList=short_form
returns 10184 results,

the old OLS did not have this difference in results.

**Comment by zChxrlie** [comment]
Would making the search term lower case return all the expected results, or could this fail to match for results with a capitalised search term?

**Comment by henrietteharmse** [comment]
Yes, lowercase will return both upper and lowercase liver results.
