### ISSUE TITLE
404 on config url

### ISSUE THREAD

**Issue by marcoooo** [EBISPOT/ols4#501]
**Describe the bug**

The following url is not responding anymore under new path for `ols4`: https://www.ebi.ac.uk/ols/api/ols-config?ids=aero,efo 

**To Reproduce**

Go to  https://www.ebi.ac.uk/ols4/api/ols-config?ids=aero,efo

**Expected behavior**

 Download config file as previous behavior. 

If the url is not maintained anymore for new version, please tell us to we can find a work around in our code: https://github.com/Ensembl/OLS-docker

**Comment by serjoshua** [comment]
Hello @marcoooo,

Sadly, we stopped support for `/ols/api/ols-config` endpoint's datasource. Also, OLS4 uses mostly JSON files now for configuration and uses Docker images, some of it detailed in the repository landing page. As for your concern though, we could recommend using `/ols4/api/ontologies/{ontology}` endpoint (e.g., [/ols4/api/ontologies/efo](https://www.ebi.ac.uk/ols4/api/ontologies/efo)) to retrieve information for a specific ontology. In the JSON response, it has the `config` field wherein you can find all the information you need. I hope converting it to YAML won't be that much of a hassle.

On the other hand, `/ols4/api/ontologies/{ontology}` endpoint does not support returning multiple ontologies. It could be a new feature that we could add though. Let us know of what you think. All the best.

**Comment by henrietteharmse** [comment]
@marcoooo  Is this a workable solution for you?

**Comment by marcoooo** [comment]
> @marcoooo Is this a workable solution for you?

Hi @henrietteharmse , I'll give it a try shortly. Thanks!
