### ISSUE TITLE
Missing data on OLS pages

### ISSUE THREAD

**Issue by kanems** [EBISPOT/ols4#502]
**Describe the bug**
I am a frequent user of Mondo data on OLS4 and in the last couple of weeks I've noticed data missing from Mondo entries in OLS4 viewer: http://purl.obolibrary.org/obo/MONDO_0008300 
I am used to seeing data for the xrefs as well as URLs for Exact Matches. The data are still present in the JSON file from OLS, so it's not that Mondo stopped reporting this in their releases.
**To Reproduce**
1. Go to https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0008300?lang=en
2. View right-hand description section, there are sections for "class information" and "class relations" but not "Exact Match" or "database cross references" or "close match"

**Expected behavior**
I expected to see the details on the right more like what is still displaying on OLS3 viewer; https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0008300 

**Screenshots**

**Upload minimal complete example**
If your ontology is not indexing correctly, please upload a minimal complete example ontology and related configuration that illustrates the problem.

**Additional context**

**Comment by matentzn** [comment]
Following this.

**Comment by jamesamcl** [comment]
It seems some code was added by @henrietteharmse in https://github.com/EBISPOT/ols4/commit/d3018c10c0ef5d5b415d64cd1331672b5a6733d3 to filter out any properties which are known to be object or data properties:

https://github.com/EBISPOT/ols4/blob/dev/frontend/src/model/Entity.ts#L110-L112

Commenting out these lines makes the properties display as expected:

![image](https://github.com/EBISPOT/ols4/assets/454895/37d8f6ac-2655-4765-8aaa-8892bc893d6b)

**Comment by henrietteharmse** [comment]
Fixed now!
