### ISSUE TITLE
Deployment instructions do not include the dataload

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#524]
The deployment instructions in the repository readme start with *compressing* the neo4j and solr databases, but do not actually include instructions to create the databases.

**Comment by jamesamcl** [comment]
Not sure why the "production outage" label got added, sorry!

**Comment by henrietteharmse** [comment]
> Not sure why the "production outage" label got added, sorry!

Because I messed up the labels! Fixed it now.
