### ISSUE TITLE
Update link to OLS announce mailing list

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/ols4#530]
**Describe the bug**
On the page https://www.ebi.ac.uk/ols4/about the link for the `OLS announce mailing list` in`For announcements relating to OLS (low traffic), such as new releases and new features sign up to the [OLS announce mailing list](https://listserver.ebi.ac.uk/mailman/listinfo/ols-announce)` seems to resolve to an internal page (https://listserver.ebi.ac.uk/mailman/listinfo/ols-announce) vs. the mailing list sign-up page.

**Comment by henrietteharmse** [comment]
The following screenshot shows the error message.
![image](https://github.com/EBISPOT/ols4/assets/32327979/94ad5f8b-de7b-411d-9e2d-42791778f7ee)

**Comment by henrietteharmse** [comment]
Done!
