### ISSUE TITLE
Annotation tool tip appears on wrong Class Relation statement

### ISSUE THREAD

**Issue by ghost** [EBISPOT/ols4#533]
**Describe the bug**
At least in one instance, the annotation tool tip for a class relation statement appears associated with the wrong statement.
For example, for the UBERON class '[nail plate](http://purl.obolibrary.org/obo/UBERON_0008198)', the following class relations appear:

<img width="359" alt="Screenshot 2023-10-03 at 15 56 04" src="https://github.com/EBISPOT/ols4/assets/95643797/8dfef6c7-ee4a-4169-a20d-5726e47dc7b7">

Note that next to **'part of' some 'skin epidermis'** an informational tool tip icon is present and "*MA (source)" appears when hovering over the icon.

However, when viewing in Protégé, this annotation is associated with the statement **'part of' of some nail**, NOT 'part of' some 'skin epidermis':

<img width="411" alt="Screenshot 2023-10-03 at 15 58 57" src="https://github.com/EBISPOT/ols4/assets/95643797/48b372b7-f57a-4d37-b9e5-de28f1d10183">

<img width="541" alt="Screenshot 2023-10-03 at 15 59 12" src="https://github.com/EBISPOT/ols4/assets/95643797/80e9f5fe-9132-4ccf-a02a-b5392f79e304">

**To Reproduce**
Go to https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0008198.
See findings that are illustrated above.

**Expected behavior**
The annotation tool tip icon would appear next to the statement **'part of' of some nail** in OLS4, NOT next to 'part of' some 'skin epidermis'

**Screenshots**
See above.

**Upload minimal complete example**
See above.

**Additional context**
I have not checked if this unexpected finding is a global issue.

**Comment by henrietteharmse** [comment]
Nice catch!

**Comment by ghost** [comment]
Checked a few other examples. 

https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001933
<img width="355" alt="Screenshot 2023-10-03 at 16 12 20" src="https://github.com/EBISPOT/ols4/assets/95643797/ea5a9444-9b0a-4ec5-891e-c1ab74eba3c2">

Protégé shows this annotation on the statement **'part of' some 'intermediate hypothalamic region'**, NOT what appears in OLS4:

<img width="412" alt="Screenshot 2023-10-03 at 16 13 13" src="https://github.com/EBISPOT/ols4/assets/95643797/4232a1be-cb0c-4e77-b108-33b96639a6b3">

However, other examples that have more than one annotation tool tip in the Class Relations appear aligned with Protégé, for example, https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0008862. Those match the annotations in Protégé.

**Comment by henrietteharmse** [comment]
@bvarner-ebi Thank you for a very detailed explanation of the issue!
