### ISSUE TITLE
 Documentation example for `/api/ontologies/{ontology_id}/terms/{term_iri}/{property_iri}` returns 301

### ISSUE THREAD

**Issue by ramiromagno** [EBISPOT/ols4#537]
The sample request for `/api/ontologies/{ontology_id}/terms/{term_iri}/{property_iri}` given in the [documentation](https://www.ebi.ac.uk/ols4/help) returns a 301 response with zero elements. I suppose that is not intended.

```bash
curl -L 'http://www.ebi.ac.uk/ols4/api/ontologies/uberon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000016/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050' -i -H 'Accept: application/json'
```

```
HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Date: Thu, 05 Oct 2023 20:17:55 GMT
Location: https://www.ebi.ac.uk/ols4/api/ontologies/uberon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000016/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050
Connection: Keep-Alive
Content-Length: 0

HTTP/1.1 200 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Content-Type: application/json
Strict-Transport-Security: max-age=0
Date: Thu, 05 Oct 2023 20:17:57 GMT
Transfer-Encoding: chunked
Content-Disposition: inline;filename=f.txt

{
  "_links" : {
    "self" : {
      "href" : "https://www.ebi.ac.uk/ols4/api/ontologies/uberon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000016/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050?page=0&size=20"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}⏎
```

**Comment by serjoshua** [comment]
This is an issue on the data or the API itself but the format of the API URL is definitely correct. We appreciate you raising your concern.

**Comment by henrietteharmse** [comment]
Interesting! I have actually never in my almost 5 years at EBI came across this query! Nor has anyone asked about this query, even though it is indeed part of documented features!

@udp in looking into this, we are not storing this in Neo4J graph currently, but this information is available from the `_json` property in Neo4J or then from Solr. You are probably way more knowledgable about parsing the `_json` field. Can you perhaps look into this?

**Comment by ramiromagno** [comment]
:) I have a tendency to stumble on corner cases...

**Comment by haideriqbal** [comment]
Updated documentation is live on OLS website.
