### ISSUE TITLE
Cannot query Mondo and likely other ontologies by API in OLS3

### ISSUE THREAD

**Issue by eweitz** [EBISPOT/ols4#538]
EBI's Ontology Lookup Service is really valuable -- thanks for providing key infrastructure for bioinformatics!

This reports a problem in https://www.ebi.ac.uk/ols, i.e. OLS3.  The issue tracker noted there says it's now read-only and links here.  So, even though this repo is for the new upcoming default version, OLS4, I figured I'd start by filing this issue here as it seems like a general technical issue with the OLS API and could plausibly relate to work on OLS4.

### Screenshot of page that is not loading

<img width="1512" alt="OLS_Mondo_down__2023-10-05T2027Z" src="https://github.com/EBISPOT/ols4/assets/1334561/65c4730a-bcb6-4646-bec1-d4aca6d53cd7">

---

### API that is not loading
https://www.ebi.ac.uk/ols/api/ontologies/mondo 

In our logs, my team sees:

`Unable to parse response from https://www.ebi.ac.uk/ols/api/ontologies/mondo`

### Diagnostics
Since it's requested in the issue template, here's some information about my laptop and browser.

 - OS: macOS Ventura 13.4 (22F66)
 - Browser: Chrome
 - Version: Version 117.0.5938.132 (Official Build) (arm64)

### Additional context
[Single Cell Portal](https://singlecell.broadinstitute.org/) (SCP) uses EBI OLS to validate metadata for new single-cell studies that researchers upload to our web application.  Without SCP being able to query Mondo via OLS, researchers are blocked from fully initializing new datasets.

We're currently using OLS3, the version of OLS that is (to our understanding) the default until 2023-10-30.  If we need to request OLS4 specifically at https://www.ebi.ac.uk/ols4 as of that date, or before then, then please let me know and SCP can update accordingly.

Thanks in advance for your help!

**Comment by henrietteharmse** [comment]
OLS3 is definitely not the default as we have not been able to update its data since the beginning of the year. OLS4 is the service that should be used.

We will look at this when have time, but OLS4 takes preference as we are severely staff constrained.

**Comment by eweitz** [comment]
Thanks for the fast response, Henriette.  

It looks like simply replacing "ols" with "ols4" in that API URL (i.e. changing https://www.ebi.ac.uk/ols/api/ontologies/mondo 
 to https://www.ebi.ac.uk/ols4/api/ontologies/mondo) returns a valid response, so we'll try that.  

I assume OLS4 API endpoints under https://www.ebi.ac.uk/ols4/api will be supported for a reasonably long term, e.g. there are no current plans to require clients to change from /ols4/api endpoints to e.g. /ols/api or /ols5/api etc. for a while.  If I'm mistaken, please let me know!

**Comment by henrietteharmse** [comment]
Yes, simply replacing `ols` with `ols4` should do it. We tried our best to ensure backward compatibility. If this is not the case for some reason for your use case let us know ASAP.  
Yes, there is no immediate plan for an /ols5/.

BTW, OLS 3 is up and running again. Mongo database became unavailable that lead to the outage. A limited restore is in place, but still you are encouraged to migrate to OLS 4 as soon as possible.

**Comment by eweitz** [comment]
Thanks the OLS3 fix!  What will happen to `ols/api/` when OLS3 is replaced by OLS4 on 2023-10-30?

I imagine two possibilities:
1. `ols/api/` becomes OLS4 (returning what `ols4/api/` does now), and clients that hadn't beta-tested might encounter issues due to breaking changes, but the transition will likely be smooth
2. `ols/api/` goes down or becomes unmaintained, and clients needing stability must point to `/ols4/api/`
