### ISSUE TITLE
OLS Search and Data stats are not loading

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/ols4#539]
Using Chrome (Version 117.0.5938.132) on Mac the Search feature is not working.

**Screenshot of page that is not loading**
<img width="1362" alt="ols4-error" src="https://github.com/EBISPOT/ols4/assets/2167174/4c0e70ba-90b5-4136-a67e-989aed877963">

**Comment by henrietteharmse** [comment]
Hi Trish!

Thank you for reporting this!
As far as I can see all the OLS4 pods were up and running at this time, but K8s related services had an extreme high memory use. I have opened a ticket with infrastructure to follow up on this. I will report back once I have feedback from them.

**Comment by henrietteharmse** [comment]
Infrastructure have addressed this now.

**Comment by twhetzel** [comment]
@henrietteharmse - fyi, this behaviour is happening again.

**Comment by twhetzel** [comment]
It's working again.

**Comment by henrietteharmse** [comment]
This problem came up again today. I am following up with infrastructure.

**Comment by henrietteharmse** [comment]
Happened again. Hence latest settings is still not resolving the issue.

**Comment by henrietteharmse** [comment]
And again!

**Comment by henrietteharmse** [comment]
We had a productive discussion with infrastructure in this regard. Currently it seems the node on which the ols4-backend runs, may be hitting some limit. Figuring this out is made difficult by the fact that the very sophisticated monitoring that infrastructure has on the cluster also fails when we have an outage on the backend. I am are checking the ols backend for potential leaks that can cause this behaviour and hope to have this complete by 23 Oct latest.  Infrastructure is monitoring specific limits to see whether crashes can be associated with reaching a specific limit.

**Comment by henrietteharmse** [comment]
It seems like we now have gotten to the bottom of this issue. Based on infrastructure monitoring the ols-backend created a disproportionate amount of threads (125000!!!). This was due to Solr, Neo4J and HTTP connections that were not closed in the ols-backend. After the latest commit on stable I can now confirm that all connections are closed and since the update on the 19 hours ago, the number of threads used in the ols-backend have been stable.
