### ISSUE TITLE
Error in "groupField" query parameter when migrating to OLS4

### ISSUE THREAD

**Issue by theisuru** [EBISPOT/ols4#540]
Hello, 

We have been using OLS for ontology resolution in biovalidator (JSON Schema validator tool). One of the example query we use for validation is 
`https://www.ebi.ac.uk/ols/api/search?q=MONDO%3A0000001&exact=true&groupField=true&queryFields=obo_id`

I have tried this in OLS 4 with below and it gives me an error. After playing a bit with the query params, I realised `groupField` is the one giving the error. If I removed `groupField` param, query works. 
`https://www.ebi.ac.uk/ols4/api/search?q=MONDO%3A0000001&exact=true&groupField=true&queryFields=obo_id`

**To Reproduce**
1. Following query is broken (because of groupField param)
[https://www.ebi.ac.uk/ols4/api/search?q=MONDO%3A0000001&exact=true&groupField=true&queryFields=obo_id](https://www.ebi.ac.uk/ols4/api/search?q=MONDO%3A0000001&exact=true&groupField=true&queryFields=obo_id)

**Expected behavior**
Expected to work similar to existing OLS API

**Comment by henrietteharmse** [comment]
Related #542
