### ISSUE TITLE
CMPO: OLS 3/4 redirects

### ISSUE THREAD

**Issue by joshmoore** [EBISPOT/ols4#541]
* The ontology ID: CMPO
* The title of the ontology: [Cellular Microscopy Phenotype Ontology](https://www.ebi.ac.uk/ols/ontologies/cmpo)
* When last did you publish changes to your ontology?: N/A
* Did the purl of the ontology change recently?: N/A

In the [IDR](https://idr.openmicroscopy.org) we use CMPO links of the form http://www.ebi.ac.uk/cmpo/CMPO_0000393. After being urged by @helenp to update all links to OLS4, we realized that these currently redirect to OLS3 pages like https://www.ebi.ac.uk/ols/ontologies/cmpo/terms?short_form=CMPO_0000393

Will this be handled within the CMPO ontology, in OLS, or is there something we should undertake at the application layer?

Many thanks,
~Josh Moore
Open Microscopy Environment

cc: @francesw @sbesson @will-moore

**Comment by henrietteharmse** [comment]
The plan is to change the firewall rules such that all `/ols/` links will forward to `/ols4/` at switch over.  

This means  `http://www.ebi.ac.uk/cmpo/CMPO_0000393` will forward to `https://www.ebi.ac.uk/ols/ontologies/cmpo/terms?short_form=CMPO_0000393`, which should then forward to `https://www.ebi.ac.uk/ols4/ontologies/cmpo/terms?short_form=CMPO_0000393`

So it should work at switch over. However, I think if you can do a sanity check of the different types of calls you making to OLS against OLS4, it will be a great help. My concern is that we may have missed some use case that you depend on. The sooner we know about it, the better.

Thanks for flagging this! 

I am closing this. Please feel free to open a ticket if you do discover an issue with OLS4.
