### ISSUE TITLE
OLS4 Search API Query  - 500 Internal Server Error

### ISSUE THREAD

**Issue by vikasguptaebi** [EBISPOT/ols4#542]
While using search API, the OLS4 API is returning 500 Internal server error.
API URL - https://www.ebi.ac.uk/ols4/api/search?q=author%20statement&groupField=true&exact=true&start=0&ontology=eco

screenshot - 
![Screenshot 2023-10-09 at 12 26 18](https://github.com/EBISPOT/ols4/assets/98779809/5c855135-ea13-4680-ac6e-99d8ed137093)

In fact, earlier OLS url is working and responding for the search API. reference URL -
https://www.ebi.ac.uk/ols/api/search?q=author%20statement&groupField=true&exact=true&start=0&ontology=eco

Please suggest if we should keep using the OLS3(ols) or should we switch to OLS4? Also, kindly suggest how soon we can have OLS4 working for the production environment.

**Comment by famaladoss** [comment]
I am also facing the same issue. I am migrating OLS3(ols) to OLS4 for a search API. Can you anyone please look into this and provide the guidance? thanks.

**Comment by henrietteharmse** [comment]
The problem here is that grouping can only be done on fields that are single valued. By default the dynamic schema assumes all string fields to be multivalued. To enable grouping based on the iri field, it has been defined explicitly in the schema to be single valued.
