### ISSUE TITLE
SRAO now has a new stable url / purl

### ISSUE THREAD

**Issue by allysonlister** [EBISPOT/ols4#544]
**The ontology ID**
SRAO

**The title of the ontology**
FAIRsharing Subject Ontology (SRAO)

**When last did you publish changes to your ontology?**
Today

**Did the purl of the ontology change recently?**
We have updated our build procedure and as a consequence have updated our OLS configuration file
[SRAO-ontology-configuration-OLS.xlsx](https://github.com/EBISPOT/ols4/files/12857910/SRAO-ontology-configuration-OLS.xlsx)

The only thing that has changed is the ontology_purl, which is now https://github.com/FAIRsharing/subject-ontology/raw/master/SRAO.owl

Please let me know if you have any questions! Thanks :)

**Comment by henrietteharmse** [comment]
This should be updated now!
