### ISSUE TITLE
Tree not visible for chebi term

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#546]
https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17234 tree not visible

because this API call returns 500: https://www.ebi.ac.uk/ols4/api/v2/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_17234/hierarchicalAncestors?size=1000&lang=en&includeObsoleteEntities=false

**Comment by jamesamcl** [comment]
Now it works again. But may be some 500s in the logs.

**Comment by henrietteharmse** [comment]
It was due to this issues showing up again:
https://github.com/EBISPOT/ols4/issues/539
Reopened #539 and closing this.
