### ISSUE TITLE
Search with a dbxref does not work as in OLS3

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#549]
@zoependlington 

**To Reproduce**

In OLS3  go to MONDO. Search for NCIT:C2985
![image](https://github.com/EBISPOT/ols4/assets/32327979/3ec1b58a-db74-4097-9a6d-6748e1b4fe5e)

But nothing is found doing the same in OLS4

**Comment by jamesamcl** [comment]
This is a `hasDbXref` for the mondo term. So ols4 is not searching hasDbXref.

(This would be fixed by implementing `annotations_trimmed` which I am looking into)

**Comment by henrietteharmse** [comment]
I think there is 2 issues here:

1. It seems Mondo no longer maps any terms to NCIT:C2985. I.e., searching through .owl file I cannot find it, except perhaps if loaded via import, but dbXrefs are included in .owl file.
2. I think this is an issue with the V2 API not using `_json` field. I.e., this query for instance seems to find a term on dbxref: [https://www.ebi.ac.uk/ols4/api/search?q=UMLS:C0011195&rows=10&ontology=mondo](https://www.ebi.ac.uk/ols4/api/search?q=UMLS:C0011195&rows=10&ontology=mondo).

**Comment by henrietteharmse** [comment]
Search on ontologies seems to be broken currently on development environment.

**Comment by henrietteharmse** [comment]
Reverted this for now.

**Comment by adityaraute** [comment]
Has this issue been resolved?

**Comment by henrietteharmse** [comment]
Yes. This has been resoled.
