### ISSUE TITLE
Pagination not working for search

### ISSUE THREAD

**Issue by yelenacox** [EBISPOT/ols4#557]
**Describe the bug**
Pagination is not working for the search feature. There is no error, but the same 10 results are returned regardless of page number or size specified in the query. Links to navigate the resources are not provided in the response.

**To Reproduce**
1. Make an API request to http://www.ebi.ac.uk/ols4/api/search?q=diabetes&page=1&size=1
2. Scroll down to compare the results to the request

**Expected behavior**
Links to navigate the resources and a response with specified size and page are expected.

**Comment by ramiromagno** [comment]
I can confirm this.

**Comment by jamesamcl** [comment]
It seems the parameter is actually `start` (in number of rows), not `page`, in both OLS3 and OLS4. I agree `page` would be more standard and we will consider changing this for the next version of the API, but this established API with `start` will continue to be supported either way.

**Comment by yelenacox** [comment]
Thank you for the clarification. I think it would be helpful to update the current documentation to specify which resources are or are not supported by the `page` parameter.
