### ISSUE TITLE
Incorrect forward to OLS4 from https://www.ebi.ac.uk/ols/index

### ISSUE THREAD

**Issue by matthiaskoenig** [EBISPOT/ols4#575]
Most search engines use https://www.ebi.ac.uk/ols/index which forwards to 
https://www.ebi.ac.uk/ols4/index, a page which cannot be found.
Please forward https://www.ebi.ac.uk/ols/index to https://www.ebi.ac.uk/ols4/

**Comment by henrietteharmse** [comment]
This should be resolved now.
