### ISSUE TITLE
Add support for requests of the form https://www.ebi.ac.uk/ols4/?termId=

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#578]
Apparently some users are using requests of this form which has not been implemented in OLS3. See [ols-support ticket](http://helpdesk.ebi.ac.uk/Ticket/Display.html?id=714111).

**Comment by henrietteharmse** [comment]
To reproduce on OLS3 use for example: http://ves-pg-7c:8080/ols/browse.do?termId=ECO:0000353
On OLS3 http://www.ebi.ac.uk/ontology-lookup/?termId=ECO:0000353 redirected to http://ves-pg-7c:8080/ols/browse.do?termId=ECO:0000353.

OLS3 code: uk.ac.ebi.spot.ols.controller.ui.HomeController.java
method: redirectOldUrls

**Comment by haideriqbal** [comment]
This has been fixed and behavior is as expected in the production
