### ISSUE TITLE
Links to Installation and API Docs return 404 when using an old OLS link (redirect issue?)

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/ols4#580]
When searching the web for docs, I came across links to the installation and api docs, but they return a 404. These are the links and what they resolve to:
https://www.ebi.ac.uk/ols/docs/installation-guide --> https://www.ebi.ac.uk/ols4/docs/installation-guide
https://www.ebi.ac.uk/ols/docs/api --> https://www.ebi.ac.uk/ols4/docs/api

Where can I find an installation guide?

**Comment by henrietteharmse** [comment]
Hi Trish, on which website did find these links? If we know which website reference these, we can update it.

Help has been updated with Swagger docs: [OLS Help](https://www.ebi.ac.uk/ols4/help)

Installation is on github: 

- Using [docker](https://github.com/EBISPOT/ols4#development-running-ols4-using-docker).
- Using [native install](https://github.com/EBISPOT/ols4#development-running-ols4-using-docker)

**Comment by twhetzel** [comment]
They were links from a google search. I thought the old links may have had re-directs set-up.
