### ISSUE TITLE
Subset/in_subset is null for VBO terms

### ISSUE THREAD

**Issue by marius-mather** [EBISPOT/ols4#581]
I thought I had tested this earlier and seen that it was working, but currently terms from VBO that should have a subset/`in_subset` property have `null`, both when using individual term lookups and searches. 

For example:

https://www.ebi.ac.uk/ols4/api/ontologies/vbo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FVBO_0000237

is a transboundary breed and should have a subset of `http://purl.obolibrary.org/obo/vbo#transboundary` or just `"transboundary"`. I'm not sure if this is specific to VBO (and maybe due to VBO's configuration), or a general issue across ontologies.

**Comment by marius-mather** [comment]
`in_subset` is working for Mondo terms, e.g. https://www.ebi.ac.uk/ols4/api/ontologies/mondo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0018660, so I assume this is about VBO's configuration.

**Comment by henrietteharmse** [comment]
Hi Marius!
This not a configuration issue but a difference in how these terms are defined in the ontology: for each term the ontology needs to state in which subset that term is defined.
Compare the definition of MONDO_0018660 in OWL 

```
   <owl:Class rdf:about="http://purl.obolibrary.org/obo/MONDO_0018660">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0002242"/>
         ...
        <oboInOwl:id>MONDO:0018660</oboInOwl:id>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/mondo#disease_grouping"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/mondo#gard_rare"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/mondo#nord_rare"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/mondo#ordo_group_of_disorders"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/mondo#orphanet_rare"/>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/mondo#rare"/>
         ...
    </owl:Class>
```
with the definition of VBO_0000237:

```
    <owl:Class rdf:about="http://purl.obolibrary.org/obo/VBO_0000237">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/NCBITaxon_9913"/>
        <dcterms:contributor>https://orcid.org/0000-0002-4142-7153</dcterms:contributor>
        <dcterms:contributor>https://orcid.org/0000-0002-5520-6597</dcterms:contributor>
        <dcterms:contributor>https://orcid.org/0000-0002-9178-3965</dcterms:contributor>
        <dcterms:source rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">https://www.fao.org/dad-is</dcterms:source>
        <oboInOwl:hasExactSynonym>Black and White</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>Friesian</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>Holstein</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>Holstein (black and white)</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>Nordic Holstein</oboInOwl:hasExactSynonym>
        <oboInOwl:hasExactSynonym>Polish Holstein-Friesian cattle</oboInOwl:hasExactSynonym>
        <rdfs:label>Holstein (black and white) (Cattle)</rdfs:label>
    </owl:Class>
```
Note the absence of `<oboInOwl:inSubset>` statements in the case of VBO_0000237.

See this example from Mondo where `in_subset` is not defined: [https://www.ebi.ac.uk/ols4/api/ontologies/mondo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0000082](https://www.ebi.ac.uk/ols4/api/ontologies/mondo/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0000082)

To have this changed, you will need to take it up with the creators of the VBO ontology.
