### ISSUE TITLE
EFO out of date

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/ols4#583]
**The ontology ID**
EFO

**The title of the ontology**
The Experimental Factor Ontology

**When last did you publish changes to your ontology?**
Nov 15th

**Did the purl of the ontology change recently?**
Not sure

**Description**
There was a recent EFO release on Nov 15th, if i remember correctly, i saw the EFO changes reflected in OLS yesterday, but today I cannot, one term that was recently imported to EFO was there yesterday but I cant no longer find it (MONDO_0022308)
Term was confirmed added here: https://github.com/EBISPOT/efo/issues/2118

**Comment by henrietteharmse** [comment]
This data release is in progress and has not been on OLS as yet.
