### ISSUE TITLE
Please bring MAMO back

### ISSUE THREAD

**Issue by ntung** [EBISPOT/ols4#592]
Hello Team,

We are the [BioModels](https://www.ebi.ac.uk/biomodels) repository, one of the EBI's core resources. Our data are heavily relied on MAMO. As things stand, this ontology won't be fixed as you mentioned in a comment of #453 except for having a specific request. Could you please arrange your time to bring it back? 

Thank you,
Tung

**Comment by ntung** [comment]
@serjoshua As I understand so far, you need us to provide an OWL file because MAMO is an OBO. Please have a look at https://data.bioontology.org/ontologies/MAMO/submissions/17/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb for MAMO.

**Comment by henrietteharmse** [comment]
Hi @ntung. It needs to be an OWL RDF file to load in OLS 4.  I am assigning this @udp whose team is responsible for ontology creation. They will be able help you to get MAMO into a format that can be processed by OLS.

**Comment by jamesamcl** [comment]
According to the OBO foundry, MAMO is an orphaned ontology which means it has no maintainers and is not responsive to requests for changes. I suggest we do a one time conversion of it using robot and load it into OLS4 from the NFS as a static file.

**Comment by cthoyt** [comment]
Following the link to MAMO's sourceforge page https://sourceforge.net/p/mamo-ontology/wiki/Home/ it appears that within the last year, someone named [Anna Zhukova](https://sourceforge.net/u/annazhukova/profile/) has made updates. Does anyone know them or how to get in touch?

**Comment by henrietteharmse** [comment]
Now available at: https://www.ebi.ac.uk/ols4/ontologies/mamo
