### ISSUE TITLE
Mention migration to OLS4 on the homepage

### ISSUE THREAD

**Issue by sneumann** [EBISPOT/ols4#594]
Hi,

**Is your feature request related to a problem? Please describe.**
Over the past months, the OLS3 page mentioned the upcoming move to OLS4, with a link to test-drive OLS4.
Now that the switch happened, software might encounter issues, (e.g., https://github.com/ISA-tools/OntoMaton/issues/39) 
Since people might've missed the months-long pre-notice, they come to https://www.ebi.ac.uk/ols/ (redirected to /ols4), and there is no news about the change. 

**Describe the solution you'd like**
The `Report an Issue` section could mention `For details about the migration to the new OLS4 system in Nov. 2023 see ...` 

Yours,
Steffen

**Comment by henrietteharmse** [comment]
Does not make sense at this stage.
