### ISSUE TITLE
OLS4 preferredRoots not working

### ISSUE THREAD

**Issue by grlloyd** [EBISPOT/ols4#598]
**Describe the bug**
Using the `preferredRoots` endpoint returns Status 500: Internal Server Error 

**To Reproduce**
1. Run `curl https://www.ebi.ac.uk/ols4/api/ontologies/GO/terms/preferredRoots`
2. See error

**Expected behavior**
The same as using the `roots` endpoint but filtered to only include terms where `is_preferred_root=true`

**Additional context**
`preferredRoots` is not documented for the previous OLS version; is it a new feature?

**Comment by haideriqbal** [comment]
This is a bug in the code and needs to be fixed. Thanks for reporting @grlloyd

**Comment by haideriqbal** [comment]
This PR https://github.com/EBISPOT/ols4/pull/714 fixes it

**Comment by haideriqbal** [comment]
Its now live in production
