### ISSUE TITLE
The most used terms do not appear on the front page of 'Search results'.

### ISSUE THREAD

**Issue by febinfawaz** [EBISPOT/ols4#606]
In the previous version of the OLS , when we search for a term , the first page of 'Search results' would always show the terms which are most used by the ontologies. But now , in many cases, I do not get the most used term on the front page. It would be great if you are able to fix this.

**To Reproduce**
1. For example search for 'country' in home page.
2. The first page shows the term for an ontology called 'schemaorg_http' which is not the most used.
3. In page 2 we can see the most used used term , which is in HANCESTRO.

**Expected behavior**
It would be great if the HANCESTRO term comes in the front page.

**Comment by henrietteharmse** [comment]
Search results in both OLS 3 and OLS4 are based on relevance. Schema.org was not loaded on OLS3, hence its results were not returned. As ontologies are added, updated and removed, the most relevant search results changes.
