### ISSUE TITLE
Please add The Rat Genome Database to OLS

### ISSUE THREAD

**Issue by kennybaird** [EBISPOT/ols4#611]
Hi, [I am a contractor for Boehringer, we have colleagues who wish to use RDO via OLS, attached is a spreadsheet with details as per the request page.  Thanks
Kenny
]([url](url))
[New OLS ontology request RDO.xlsx](https://github.com/EBISPOT/ols4/files/13965164/New.OLS.ontology.request.RDO.xlsx)

**Comment by matentzn** [comment]
Your spreadsheet is empty - but I have never heard of RDO in the context of rats (only in the context of Radiology); as far as I know RGD (the Rat Genome Database) uses DO for diseases, CMO for measurements and vto for traits, MP for phenotypes - so not sure what Rat Genome Database exactly stands for?

**Comment by kennybaird** [comment]
Hi, apologies for the spreadsheet, it should now be attached correctly.  
[New OLS ontology request RDO.xlsx](https://github.com/EBISPOT/ols4/files/14023136/New.OLS.ontology.request.RDO.xlsx)
The RGD does use DO for diseases, but extends them with concepts which are not in DO
Thanks

**Comment by matentzn** [comment]
> Oh my... This will be so confusing. I never ever heard of this effort of RGD: https://github.com/rat-genome-database/RDO-Disease-Ontology

> It is using DOID identifiers. It is enormous with more than 8000K terms added that have not been reviewed by the DO team, or at least not published. It is republishing DO terms. I dont even get what the purpose/scope of RDO is. Initially I thought ["animal diseases"](https://rgd.mcw.edu/rgdweb/ontology/view.html?acc_id=DOID:9004985&offset=11), but then, there are hundreds if not thousand of classes in that "extension" that are clearly not animal and are sourced from something like Mesh..

> I would very strongly suggest that RDO does not belong in OLS in its current state - it needs to go through OBO first. Ideally, RGD needs to work with DO on some way to integrate the two ontologies. 

> Adding another disease ontology, one with DOID identifiers, is a big mistake IMO. RDO, should work on on a harmonised release product with DO, with a clear scope (rat disease or whatever) and go through OBO.

EDIT: 
I leave my above comments there for transparency but they are supplemented by the less emotional next comment.

**Comment by matentzn** [comment]
Just to be clear: I am not in any position to say yay or nay on anything related to any of the EBI resources - I am sure the SPOT team will add the ontology if they think it is the right thing to do regardless of my opinion. I was told by my friends and colleagues that my tone above was a bit too negative here, and I really did not mean to say anything negative (I am a bit passionate sometimes, huge sorry about that).  So, what I would like to offer here is the following concern:

RDO 

1. is not yet an OBO-reviewed resource (most other RGD products actually are, so I don't know why this one is not)
2. uses identifiers that belong to a different ontology, which may be confusing to people (curator will find a DOID identifier searching OLS and using it _thinking_ they are using DO, but are not).
3. does not have a clear enough scope at first glance - in particular, it seems (to my unprofessional eyes) to contain plenty of human diseases as well.

**Comment by kennybaird** [comment]
I also am v passionate about ontologies, they are wonderful, wonderful things.   I did not take anything negative from your response, which was very helpful, you have nothing to apologise for as far as I am concerned.

**Comment by matentzn** [comment]
Thank you @kennybaird

**Comment by henrietteharmse** [comment]
@kennybaird 
In general OLS is slightly more lenient in accepting ontologies into OLS than OBO. However, in its current state, we cannot accept this ontology for the following reasons.

1.  You did not provide a purl from where we can download the .owl file for the ontology. OLS4 only support .owl files.
2.  as @matentzn has pointed out, you are reusing purls to existing terms to identify terms in your ontology. This goes against the basic principles of the semantic web. As mentioned in an earlier comment you made, you are using terms from DOID from which you extend new terms that are not in DOID. This you can do, but then you have to import those terms from DOID and declare them in your own ontology.

I strongly you reach out to the OBO community to help you in creating a pipeline to achieve 1 and 2.
