### ISSUE TITLE
Facet Data is missing from the search call response (v1)

### ISSUE THREAD

**Issue by Pooya-Oladazimi** [EBISPOT/ols4#613]
**Describe the bug**
When this endpoint is used for the search: https://www.ebi.ac.uk/ols4/api/search?q=data&start=0&groupField=iri&rows=10
There is no facet count data (it only has the search results)

**To Reproduce**
call  https://www.ebi.ac.uk/ols4/api/search?q=data&start=0&groupField=iri&rows=10

**Expected behavior**
facet data needs to be included in the response

**Screenshots**
N/A

**Upload minimal complete example**
N/A

**Additional context**
It should respond like v2 API: https://www.ebi.ac.uk/ols4/api/v2/entities?search=data&size=10&page=0&facetFields=ontologyId
where the **facetFieldsToCount** field contains facet data.

I tried also to include **facetFields** param, but no luck:  https://www.ebi.ac.uk/ols4/api/search?q=data&start=0&groupField=iri&rows=10&facetFields=ontologyId

**Comment by jamesamcl** [comment]
Just to note this needs to be compared with OLS3 as we don't want to make breaking changes to the backwards compatible API.

**Comment by jusa3** [comment]
We are also interested in getting the facet data (facet field information) from the search endpoint as it was with the old API: https://semanticlookup.zbmed.de/api/search?q=diabetes&exact=false&obsoletes=false&groupField=true&rows=10&start=0

We use the type and ontology names and counts for filtering the search results.
