### ISSUE TITLE
UPHENO status

### ISSUE THREAD

**Issue by bschilder** [EBISPOT/ols4#615]
**Is your feature request related to a problem? Please describe.**
I was wondering what the current status and plans were for the UPHENO ontology. It doesn't seem to be currently accessible via OLS (in the browser or the [`rols` R package](https://github.com/lgatto/rols) which uses the API).
I noticed some old issues and PRs that removed it, but I'm not sure why:
- https://github.com/EBISPOT/ols4/pull/564
- https://github.com/EBISPOT/ols4/pull/563

I also noticed that mappings to UPHENO terms do still exist in relation to other ontologies (e.g. DOID):
https://www.ebi.ac.uk/ols4/ontologies/doid/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUPHENO_0001001

Both v1 and v2 or UPHENO are available via the OBO Foundry
https://obofoundry.org/ontology/upheno.html
As well as on GitHub:
https://github.com/obophenotype/upheno/

**Describe the solution you'd like**
Have UPHENO be available via OLS.

**Describe alternatives you've considered**
Currently, I'm downloading UPHENO directly from their OBO Foundry ("https://purl.obolibrary.org/obo/upheno/v2/upheno.owl") and importing it into R with `simona::import_ontology`

**Additional context**
I'm asking in part as it relates to a new package I'm making to help use, filter, and manipulate ontologies and knowledge graphs in R:
https://github.com/neurogenomics/KGExplorer

Thanks for your help!, 
Brian

**Comment by haideriqbal** [comment]
Thank you for your inquiry about the inclusion of UPHENO ontology in the OLS. UPHENO is managed by OBO (Open Biological and Biomedical Ontology) Foundry and we're glad to inform you that UPHENO is in the process of being recognized by the OBO  Foundry community. It's the efforts of the OBO community that determine the inclusion of new ontologies into the OBO.

Once UPHENO is formally part of the OBO, it will automatically be integrated into OLS and then you can query it via OLS.

**Comment by matentzn** [comment]
Just to be clear: there is a slightly confusing situation as there is a "upheno (1)" that has already been accepted in OBO, and a new one developed by @jamesamcl and his team which you can see, for now, here: https://ols.monarchinitiative.org/ontologies/upheno2

It is odd that upheno1 is not at all in OLS (it should be), but its probably because it has 40K unsatisfiable classes..

**Comment by bschilder** [comment]
Thanks so much for the info @matentzn @haideriqbal !


> Just to be clear: there is a slightly confusing situation as there is a "upheno (1)" that has already been accepted in OBO, and a new one developed by @jamesamcl and his team which you can see, for now, here: https://ols.monarchinitiative.org/ontologies/upheno2

Thanks for the link! I'm guessing this page is still under development though? based on the fact that the ontology isn't actually available for download (at least not that I can find there):
https://ols.monarchinitiative.org/ontologies/upheno2/download

> It is odd that upheno1 is not at all in OLS (it should be), but its probably because it has 40K unsatisfiable classes..

This seemed strange to me as well since upheno1 has been out for a quite a while. @haideriqbal am I mistaken in thinking that if it's on OBO Foundry already (see [here](https://obofoundry.org/ontology/upheno.html)) it should also be available on OLS? Is the issue due to the errors reported [here](https://dashboard.obofoundry.org/dashboard/upheno/dashboard.html)? Not sure is this is the same issue with 40k 40K unsatisfiable classes that @matentzn mentioned.

**Comment by haideriqbal** [comment]
Hi @bschilder after further investigating the issue on our end we've come to know that there is an issue with one of the imports of UPHENO ontology. The import is not in the correct format and hence is not loaded in OLS. I've opened an issue with the UPHENO team as well. You can have a look here https://github.com/obophenotype/upheno/issues/929.

Once the UPHENO team fixes the issue with the import then the UPHENO ontology would automatically load in the OLS.

**Comment by bschilder** [comment]
@haideriqbal thanks so much for looking into this! Glad to hear there's activity on this
