### ISSUE TITLE
Search ranking on ontologies page

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#617]
**Describe the bug**

Search ranking on ontologies page does not prioritise exact matches

**To Reproduce**
 
Visit https://www.ebi.ac.uk/ols4/ontologies?search=efo

Or type efo into the search box under Ontologies. EFO is last in the list

**Expected behavior**
 
EFO should be first in the list

**Comment by haideriqbal** [comment]
fixed in production
