### ISSUE TITLE
Clarification of field "id" in API needed

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [EBISPOT/ols4#618]
I was trying today to work out how your API works using the [webpage](https://www.ebi.ac.uk/ols4/swagger-ui/index.html). However, to me it is not at all clear what input is expected in the "id" field. For example, at the moment I want to retrieve all parent terms of the term http://purl.obolibrary.org/obo/ENVO_01000263, using /api/ontologies/{onto}/terms{id}/ancestors. However, I can't seem to get the input for the id field right. My input for the "onto" field is "envo".
So far I have tried "http://purl.obolibrary.org/obo/ENVO_01000263", "ENVO_01000263", "ENVO:01000263" and "01000263" for the id field, but none of them seem to work correctly. Could you clarify exactly what kind of input is needed here?

**Comment by haideriqbal** [comment]
Update documentation with examples is live in production now.
