### ISSUE TITLE
Swagger documentation: missing ols4/api/ontologies/ API

### ISSUE THREAD

**Issue by lgatto** [EBISPOT/ols4#620]
**Describe the bug**

I think that the API to request all ontologies is missing.

**Expected behavior**

I would expect this to be documented:

```
curl -X 'GET' \
  'https://www.ebi.ac.uk/ols4/api/ontologies/?lang=en&page=0&size=1' \
  -H 'accept: application/json'
```

**Comment by haideriqbal** [comment]
Update documentation is live in production now!
