### ISSUE TITLE
Swagger documentation: /api/ontologies/{onto}/terms/{id} wrong or unclear

### ISSUE THREAD

**Issue by lgatto** [EBISPOT/ols4#621]
**Describe the bug**

I am unable to execute the query `/api/ontologies/{onto}/terms/{id}` after trying multiple combinations of `{onto}` and `{id}`.

It is unclear whether I am doing something wrong or of there's another problem. It would be extremely useful for users to have examples - this would also have helped me deciding whether I was calling the API with the wrong parameters.

There are other API calls that I can't figure out. I believe this issue is probably related to #618.

**Comment by lgatto** [comment]
So apparently, the URL to query `ADO:0000090` from the `ado` repository should be

```
https://www.ebi.ac.uk/ols4/api/ontologies/ado/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FADO_0000090?lang=en
```

but I don't see how to encode this into the swagger query interface.

**Comment by henrietteharmse** [comment]
Related: #591,#620, #618

**Comment by haideriqbal** [comment]
Updated OLS documentation includes examples and is live in production.
