### ISSUE TITLE
Add examples and clarification to Swagger documentation

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#622]
**Describe the documentation deficiency**
Currently there are few related issues wrt Swagger documentation. This can be addressed more generally by updating OLS4 Swagger documentation from OLS3 documentation.

**Url to existing documentation if applicable**
Swagger documentation: https://www.ebi.ac.uk/ols4/swagger-ui/index.html
OLS3 documentation: https://www.ebi.ac.uk/ols4/ols3help
Ideally the Swagger documentation should stand by itself and we should be able to get rid of the OLS3 documentation.

**Comment by haideriqbal** [comment]
OLS4 Documentation has replaced by OLS3 in production. https://github.com/EBISPOT/ols4/pull/677
