### ISSUE TITLE
How to get a list of all ontologies (title, URI, file) available on your service? (REST or data dump)

### ISSUE THREAD

**Issue by k00ni** [EBISPOT/ols4#629]
Hello, 

**I would like to get a list of all ontologies available on your service**. *I mean the ones which I can browse at https://www.ebi.ac.uk/ols4/ontologies*. I couldn't find an appropriate method in the Swagger documentation (https://www.ebi.ac.uk/ols4/swagger-ui/index.html#/). I might have overlooked it. 

To show you what I mean, here is an example in Linked Open Vocabularies: they provide a list of their ontologies/vocabularies via the REST API (https://lov.linkeddata.es/dataset/lov/api/v2/vocabulary/list). Besides, there is also a data dump available (https://lov.linkeddata.es/dataset/lov/sparql, look top right).

My current workaround would be to go through each page of https://www.ebi.ac.uk/ols4/ontologies?rowsPerPage=100 and scrape these information by parsing the page HTML.

Thanks for your reply.

**Comment by jamesamcl** [comment]
Hi, you can use this API endpoint: https://www.ebi.ac.uk/ols4/api/ontologies

I agree this does seem to be missing from the swagger docs

**Comment by haideriqbal** [comment]
Hi @k00ni , as @jamesamcl mentioned you can use our API to get the list of all available ontologies in ols. We'll be adding this to our swagger doc soon as well :)

**Comment by k00ni** [comment]
Thank you very much for the quick response. I will look into that.
