### ISSUE TITLE
It should be possible to run a single test via test scripts

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#63]
Currently the test scripts only runs everything. However, for debugging purposes it will be helpful to run a single test straight through from data load right through to being able to run the UI against it.

**Comment by jamesamcl** [comment]
I also think we need to make it clear which scripts are for actual testing (i.e. unit and integration tests; this is `test_api.sh` and `test_dataload.sh`) and which are helper scripts for development.

I'm not sure if there's a better name we can give the latter or if we should put them in a different folder, but the more scripts we have in the root of the repo the more confusing it gets about what to run, especially when there are scripts like `stopall.sh` that are linked to specific deployments of Neo4j and Solr rather than OLS as a whole. (I'm not saying it's not useful! I just want to keep the repo clean and tidy :D)

**Comment by henrietteharmse** [comment]
Yeah, I agree. The names are terrible and I cannot think of something more appropriate as yet. Because it is useful I thought I rather check it than wait until I have better names. I am happy to change it to whatever.

As for `test_api.sh`  and `test_dataload.sh`, are you saying developers should not run them? Personally I see unit and integration testing as developer testing. Certainly they should be run before a developer does a check in and any issues should be resolved before checking in? Then ideally you want to run a single failing test until it is fixed before running everything again. Having to run all tests while resolving an issue is something I will like to avoid.

**Comment by jamesamcl** [comment]
> Yeah, I agree. The names are terrible and I cannot think of something more appropriate as yet. Because it is useful I thought I rather check it than wait until I have better names. I am happy to change it to whatever.

They're not terrible, I just want to minimize the number of things that are at the top level of the repo and make it very clear what does what.

> As for test_api.sh and test_dataload.sh, are you saying developers should not run them? Personally I see unit and integration testing as developer testing. Certainly they should be run before a developer does a check in and any issues should be resolved before checking in? Then ideally you want to run a single failing test until it is fixed before running everything again. Having to run all tests while resolving an issue is something I will like to avoid.

Yes absolutely - developers should run them. The distinction between those scripts and the scripts you added are that those scripts (`test_api.sh` and `test_dataload.sh`) run automated comparisons and fail if there are any differences (which is what I consider a test).

The new scripts (`teststack.sh` and `stopall.sh`) don't actually "test" anything, they just run/stop stuff. Which is also really helpful, but they are distinct from tests.

**Comment by henrietteharmse** [comment]
> new scripts (teststack.sh and stopall.sh) don't actually "test" anything
Not yet ..., but hopefully soon.

**Comment by henrietteharmse** [comment]
The apitester4 needs to be extended to allow testing a single ontology. Currently it will read complete Neo4J db and compare against expected output directory. This is perfect for CI testing. However, typical developer testing will require checking a single ontology rather than all ontologies.  

Depends on #67.

**Comment by jamesamcl** [comment]
> The apitester4 needs to be extended to allow testing a single ontology. Currently it will read complete Neo4J db and compare against expected output directory. This is perfect for CI testing. However, typical developer testing will require checking a single ontology rather than all ontologies.

apitester4 now supports this with the `--ontology` option, e.g. `--ontology efo`.

**Comment by henrietteharmse** [comment]
This is possible via the `/dev-testing/teststack.sh` script.
