### ISSUE TITLE
ols4 down

### ISSUE THREAD

**Issue by lcdaugherty** [EBISPOT/ols4#647]
all urls return 
https://www.ebi.ac.uk/ols4/error

**Comment by lcdaugherty** [comment]
seems to be back up and working as expected. thanks

**Comment by haideriqbal** [comment]
Hi @lcdaugherty , thank you for reporting this... I've created a new issue to handle this https://github.com/EBISPOT/ols4/issues/648

Its basically our data release pipeline step which is causing this brief outage whenever there is a new data release.
