### ISSUE TITLE
OLS goes down for a bit when the latest data release is being copied over

### ISSUE THREAD

**Issue by haideriqbal** [EBISPOT/ols4#648]
As part of the data release process, OLS goes down for a bit when the latest data release is being copied over. The issue is that the frontend pod gets started/deployed pretty quick before the backend/dataload pods are not ready yet hence, users see error when going to  ols website.

This would need to be fixed as only deploy frontend once the backend and dataload (Solr and Neo4J) are deployed and ready.

**Comment by lcdaugherty** [comment]
@haideriqbal  thank you. This  keeps happening (and just now but the downtime was less), so not sure this is just related to the latest data release, unless it is done daily?
 To clarify yesterday release process incurred downtime for an external user of about 25-30 mins.

**Comment by lcdaugherty** [comment]
I have checked my connection and it is ok. Currently I can get to the ebi.a.cuk/ols4, but for the text boxes there is a swirling green circle and if I type in one of the examples given eg: GO:0098743 I get a <no results>
 (the green swirling circle is still happening in the search box)

**Comment by haideriqbal** [comment]
@lcdaugherty we do our data releases daily, and the green swirling circle which you see is because just when our application starts it takes a slight bit of time for solr (where our data is stored) to warm up hence the loading sign you see. I've just checked and our application is all good atm...

this is something we will be looking at soon so that we don't have such downtimes when doing our data releases daily.

**Comment by haideriqbal** [comment]
The issue has been fixed now!

**Comment by lcdaugherty** [comment]
@haideriqbal this still seems to be an issue?
![Screenshot 2024-09-18 095731](https://github.com/user-attachments/assets/0799da89-0fb0-46bb-9953-cf3620819fee)
![Screenshot 2024-09-18 100031](https://github.com/user-attachments/assets/23988253-b8bf-4358-800d-9fcc5027000c)
![Screenshot 2024-09-18 100355](https://github.com/user-attachments/assets/f8c66096-7d75-4c01-a045-b0861e1f7cdc)
![Screenshot 2024-09-18 100408](https://github.com/user-attachments/assets/20a1f2bb-70e0-4b05-96db-0529f2a39a5f)
