### ISSUE TITLE
Term pages loading but ending completely blank

### ISSUE THREAD

**Issue by anitacaron** [EBISPOT/ols4#652]
The page loads, but the tree view is still processing; the page turns blank.

Some examples:
https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001012
https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0010853
https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000144
https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0006801
https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0004411

**Comment by haideriqbal** [comment]
Thanks for reporting this. Looks like something going wrong during the parsing of the tree data. Would need to investigate further and will get back to you.

![Screenshot 2024-04-24 at 16 22 27](https://github.com/EBISPOT/ols4/assets/13108541/1d3b697c-3a7f-477a-90a8-a11e069872f0)

**Comment by henrietteharmse** [comment]
Fixed

**Comment by anitacaron** [comment]
Thanks! 🎉
