### ISSUE TITLE
Race condition searching ontologies list

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#653]
**Describe the bug**

If you type too quickly in the ontology search filter it does not work

**To Reproduce**

Go to https://www.ebi.ac.uk/ols4/ontologies

Type the name of an ontology eg "efo". If you type it quickly the search does not filter.

**Comment by haideriqbal** [comment]
this issue https://github.com/EBISPOT/ols4/issues/617 might be relevant with this one.

**Comment by haideriqbal** [comment]
Fixed in production.
