### ISSUE TITLE
curie not a curie

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#656]
https://www.ebi.ac.uk/ols4/api/v2/ontologies/idocovid19/properties/http%253A%252F%252Fwww.geneontology.org%252Fformats%252FoboInOwl%2523hasDbXref

    "curie" : "hasDbXref",
    "definedBy" : [ "oio" ],

I think the curie should be `oio:hasDbXref`. The above link is to the v2 api to show the issue in the database, but you can see it in the v1 api as `short_form` and `obo_id`:

https://www.ebi.ac.uk/ols4/api/ontologies/idocovid19/properties/http%253A%252F%252Fwww.geneontology.org%252Fformats%252FoboInOwl%2523hasDbXref
 
which I believe should be `oio_hasDbXref` and `oio:hasDbXref` respectively.

**Comment by henrietteharmse** [comment]
According to @jamesamcl this is likely some logic issue in rdf2json :-)

**Comment by jamesamcl** [comment]
Specifically this file:

https://github.com/EBISPOT/ols4/blob/dev/dataload/rdf2json/src/main/java/uk/ac/ebi/rdf2json/annotators/ShortFormAnnotator.java

**Comment by haideriqbal** [comment]
fixed in production
