### ISSUE TITLE
No results (OLS down?)

### ISSUE THREAD

**Issue by egonw** [EBISPOT/ols4#665]
**Describe the bug**
When I search for `oxide` I would expect some results, e.g. from CHEBI and ENM, but I get no results:

![image](https://github.com/EBISPOT/ols4/assets/26721/8f955c1a-d197-4890-91b4-3d6b31d53341)

**To Reproduce**
1. Go to https://www.ebi.ac.uk/ols4/search?q=oxide
2. See error (see above screenshot)

**Expected behavior**
Results from several ontologies, including CHEBI and ENM.

**Comment by jamesamcl** [comment]
Seems like it’s back up now.
