### ISSUE TITLE
exact parameter not functioning correctly in search api

### ISSUE THREAD

**Issue by ma9253** [EBISPOT/ols4#666]
**Describe the bug**
I am reporting an issue with the "exact" parameter in the search API, as documented on the following page: https://www.ebi.ac.uk/ols4/ols3help.

According to the documentation, setting the "exact" parameter to true should return exact matches. However, this does not seem to be working as expected.

**Example To Reproduce**
Here is an example:

When I use the following API call with exact=true:
https://www.ebi.ac.uk/ols4/api/search?q=natural%20killer%20cell&ontology=cl&exact=true
The response does not prioritize the exact match. Instead, it returns "immature natural killer cell" as the first entry. 

Based on my understanding, "natural killer cell" should be the first response.

In contrast, when I use exact=false:
https://www.ebi.ac.uk/ols4/api/search?q=natural%20killer%20cell&ontology=cl&exact=false
The response correctly prioritizes "natural killer cell" as the first result.

It appears that the check for the "exact" parameter may be functioning oppositely to what is intended.

**Comment by haideriqbal** [comment]
Hi @ma9253 ! sorry for the delayed response. We'll fix this as soon as possible.

**Comment by haideriqbal** [comment]
This. has been fixed in production
