### ISSUE TITLE
Deprecated term message not showing any information, only `Object`

### ISSUE THREAD

**Issue by anitacaron** [EBISPOT/ols4#689]
**Describe the bug**
Since some time ago, I've been seeing all obsolete terms without a proper deprecated message on top, and I do remember seeing the message correctly.

<img width="598" alt="Screenshot 2024-06-25 at 16 59 42" src="https://github.com/EBISPOT/ols4/assets/2208124/e2446f2c-708f-4d29-a7a6-6bf0f277de34">

**To Reproduce**
Check any obsolete term, for example https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0000695 

**Expected behavior**
As seen in the first [issue showing the implementation](https://github.com/EBISPOT/ols4/issues/411#issuecomment-1623971937).

<img src="https://private-user-images.githubusercontent.com/25520595/251512949-caf4d934-c056-437d-a61b-070256603ad6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzIxMDcsIm5iZiI6MTcxOTMzMTgwNywicGF0aCI6Ii8yNTUyMDU5NS8yNTE1MTI5NDktY2FmNGQ5MzQtYzA1Ni00MzdkLWE2MWItMDcwMjU2NjAzYWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE2MTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YzY1NDA1ZjgzOTg2ZjI5MDNlZjA2NWFlNzkzNzMzZjM0YzljODVhYTI4NDM3NWNmZTUxNTM2NWRkZmE4NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2cMpYJ_5EBssV7Ls_MA--wGpSFvM4O1aKnMOS5PmfIs">

**Comment by haideriqbal** [comment]
Thanks @anitacaron for reporting! I will let you know once this is fixed :)
