### ISSUE TITLE
value of type is set to class for V1SearchController + V1SelectController

### ISSUE THREAD

**Issue by rombaum** [EBISPOT/ols4#693]
**Describe the bug**
I'm using the value _**individual**_ or **_property_** for the parameter **_type_** for a V1 select/search API request. In the response I am getting **_class_** as the value of **_type_** for each request. At the moment the value of key **_type_** for a search/select API call is directly set to `class` in the corresponding Java classes V1SearchController + V1SelectController. 

**To Reproduce**
I decrease the complexity of the response by setting the fieldList to type and id. Steps to reproduce the behavior:

1. Go to ['API v1: q=see+a&type=individual&fieldList=type,id'](https://www.ebi.ac.uk/ols4/api/select?q=see+a&type=individual&fieldList=type,id)
2. Have a look to the docs of the response to see the error.

**Expected behavior**
The response should provide the requested type (e.g. individual, property, ...).

**Screenshots**
![grafik](https://github.com/EBISPOT/ols4/assets/47030738/5fe32ab8-defa-417f-a3bd-aef2be501c11)

**Additional context**
The lines to change should be here:

https://github.com/EBISPOT/ols4/blob/56a60e3e403b1f5f6e2edcb8010eab8161198c2e/backend/src/main/java/uk/ac/ebi/spot/ols/controller/api/v1/V1SearchController.java#L259

https://github.com/EBISPOT/ols4/blob/56a60e3e403b1f5f6e2edcb8010eab8161198c2e/backend/src/main/java/uk/ac/ebi/spot/ols/controller/api/v1/V1SelectController.java#L164

I didn't had the time to test this out, but I would guess that the two lines should look like:

`if (fieldList.contains("type")) outDoc.put("type", JsonHelper.getString(json, "class"));` 

similar to the other code of the possible fields:

> if (fieldList.contains("id")) outDoc.put("id", res.get("id").toString().replace('+', ':'));
>             if (fieldList.contains("iri")) outDoc.put("iri", JsonHelper.getString(json, "iri"));
>             if (fieldList.contains("ontology_name")) outDoc.put("ontology_name", JsonHelper.getString(json, "ontologyId"));
>             if (fieldList.contains("label")) outDoc.put("label", JsonHelper.getString(json, "label"));
>             if (fieldList.contains("description")) outDoc.put("description", JsonHelper.getStrings(json, "definition"));
>             if (fieldList.contains("short_form")) outDoc.put("short_form", JsonHelper.getString(json, "shortForm"));
>             if (fieldList.contains("obo_id")) outDoc.put("obo_id", JsonHelper.getString(json, "curie"));
>             if (fieldList.contains("is_defining_ontology")) outDoc.put("is_defining_ontology",
>                     JsonHelper.getString(json, "isDefiningOntology") != null && JsonHelper.getString(json, "isDefiningOntology").equals("true"));
>             if (fieldList.contains("type")) outDoc.put("type", "class");
>             if (fieldList.contains("synonym")) outDoc.put("synonym", JsonHelper.getStrings(json, "synonym"));
>             if (fieldList.contains("ontology_prefix")) outDoc.put("ontology_prefix", JsonHelper.getString(json, "ontologyPreferredPrefix"));
> [source](https://github.com/EBISPOT/ols4/blob/56a60e3e403b1f5f6e2edcb8010eab8161198c2e/backend/src/main/java/uk/ac/ebi/spot/ols/controller/api/v1/V1SelectController.java#L154C1-L166C141)

**Comment by henrietteharmse** [comment]
Fix is available on our dev environment: [https://wwwdev.ebi.ac.uk/ols4/api/select?q=see+a&type=individual&fieldList=type,id](https://wwwdev.ebi.ac.uk/ols4/api/select?q=see+a&type=individual&fieldList=type,id).

It should be on prod by tomorrow.
