### ISSUE TITLE
OLS search is intermittently slow

### ISSUE THREAD

**Issue by lopierra** [EBISPOT/ols4#695]
**Screenshot of page that is not loading**
<img width="1187" alt="image" src="https://github.com/EBISPOT/ols4/assets/34149564/da287f63-12af-4db2-8d25-ce6a582a48c9">
<img width="1169" alt="image" src="https://github.com/EBISPOT/ols4/assets/34149564/00165d1e-4832-4d62-b215-1618deaa21e1">

**API that is not loading**
Takes 30 sec to a couple of minutes to search for a term in HP or MONDO. After clicking on a term, the tree is equally slow to load. It has been intermittently very slow, then normal, then slow again today.

**Desktop (please complete the following information):**
Windows 11, Chrome Version 126.0.6478.127

**Comment by haideriqbal** [comment]
Hi @lopierra! we have been investigating our Kubernetes usage stats and it looks like there are certain spikes in memory usage around the time you reported the issue which would have led to this... we are working on finding a solution for this and will fix it as soon as possible.

**Comment by lopierra** [comment]
Thank you @haideriqbal!

**Comment by henrietteharmse** [comment]
This seems to have been due to some network issues within EBI, which have thankfully been resolved.
