### ISSUE TITLE
Missing EFO ontology entirely

### ISSUE THREAD

**Issue by M-casado** [EBISPOT/ols4#703]
**Describe the bug**
The Experimental Factor Ontology (EFO) was removed from OLS. I cannot find it in Ontologies, nor in existing records I had bookmarked.

**To Reproduce**
1. Go to [EFO's record at OLS](https://www.ebi.ac.uk/ols4/ontologies/efo) (``https://www.ebi.ac.uk/ols4/ontologies/efo``)
2. See error page:
![image](https://github.com/user-attachments/assets/d62aa3f9-1b50-406c-8f70-954358463aab)

Other ways to reproduce:
1. Go to [OLS' ontologies record](https://www.ebi.ac.uk/ols4/ontologies) (``https://www.ebi.ac.uk/ols4/ontologies``)
2. Search for EFO ontology
3. See no results

Final way:
1. Try to access any EFO record (e.g., [``https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0000542``](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0000542))
2. See same error as above.

**Expected behavior**
Records of EFO can be accessed.

**Screenshots**
![image](https://github.com/user-attachments/assets/d62aa3f9-1b50-406c-8f70-954358463aab)

**Upload minimal complete example**
NA

**Additional context**
I checked EFO's page and GH repository, and found no banners describing down time. Same at OLS'

**Comment by henrietteharmse** [comment]
@M-casado  Yes! We are aware of it and we are looking into it. Thanks for reporting it!

**Comment by henrietteharmse** [comment]
The step that failed for EFO yesterday passed today without any issues. If all goes well, EFO should be back on OLS by tomorrow evening.

**Comment by henrietteharmse** [comment]
EFO is back on OLS!
