### ISSUE TITLE
Loading STATO v1.5 to OLS

### ISSUE THREAD

**Issue by proccaserra** [EBISPOT/ols4#704]
**The ontology ID**
STATO

**The title of the ontology**
The Statistics Ontology 

**When last did you publish changes to your ontology?**
[released 12.07.2024](https://github.com/ISA-tools/stato/releases/tag/v1.5)

Please confirm the format requirements: Is RDF/XML required and OWL/XML not accepted?

**Comment by henrietteharmse** [comment]
Yes, OLS only supports RDF/XML, not OWL/XML.

**Comment by proccaserra** [comment]
Thank you @henrietteharmse , I have now updated the release package available from
https://github.com/ISA-tools/stato/releases/download/v1.5/1.5.zip
The archive contains rdf, obo, and owl format serialization. 
Let me know if there is a specific process to notify OLS of new releases automatically. Many thanks for OLS

**Comment by matentzn** [comment]
@proccaserra sorry for barging in here :) As STATO as listed as an OBO Foundry ontology (https://obofoundry.org/ontology/stato.html), you should make sure that `http://purl.obolibrary.org/obo/stato.owl` redirects to the latest RDF/XML release of your ontology, as per OBO principles (https://obofoundry.org/principles/fp-002-format.html). 

You can update the redirect here: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/stato.yml

**Comment by proccaserra** [comment]
hi @matentzn ! always nice to hear from you :) Just to be clear, it is fine for me to add more than one product, i.e.:
```code
products:
- stato.owl: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/latest_release/stato.owl
- stato.rdf: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/latest_release/stato.rdf
- stato.owl: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/latest_release/stato.obo
```
Is this fine for the redirect?

**Comment by matentzn** [comment]
Likewise @proccaserra :) 

The key to OBO interoperability is that the .owl extension points to the rdfxml file. For owlxml, we tend to use owx, see https://www.w3.org/TR/owl2-xml-serialization/ for the W3C recommendation!

We tend to avoid the .rdf extension for anything OWL related altogether, and keep it for pure rdf / rdfs type files.

**Comment by henrietteharmse** [comment]
@proccaserra Once STATO is updated on OBO, OLS will pick it up automatically.

**Comment by proccaserra** [comment]
okay Thank you both again! I will the file extensions to meet the pattern.

**Comment by henrietteharmse** [comment]
STATO is available in OLS again!

![image](https://github.com/user-attachments/assets/03a5084a-8a6a-481e-8529-cd06ea54cd92)

**Comment by proccaserra** [comment]
Thank you very much @henrietteharmse and team.
