### ISSUE TITLE
API documentation issues

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#709]
**Describe the documentation deficiency**
1. Request parameters of type `array[string]` are not documented for `/search` and `/select` requests. A partial list is shown in the screenshot.

![image](https://github.com/user-attachments/assets/c28f7417-a34b-4f52-a4f5-b307e9783fba)

2. The `format` probably also requires clarification. I.e., what other formats are allowed?
![image](https://github.com/user-attachments/assets/511afd78-dd1c-47e7-aff7-73f0b169e69a)

**Comment by haideriqbal** [comment]
Details relating to these fields have been added and its live in production now
