### ISSUE TITLE
slim option

### ISSUE THREAD

**Issue by djacob65** [EBISPOT/ols4#715]
Hi
I would like to know what the 'slim' option is for. I searched everywhere on the site but couldn't find anything.
Thanks

**Comment by haideriqbal** [comment]
Hi, thank you for your enquiry. Slims are selected parts of the ontologies where you can choose certain terms of your choice within the ontology. However, there isn't any standardised way within the ontologies community about the definition of slims or what constitutes a slim therefore it's not implemented in the OLS. You can further read about slims here: https://www.ebi.ac.uk/QuickGO/help/slims

I hope this helps.

**Comment by djacob65** [comment]
Thanks for your answer.
