### ISSUE TITLE
Links in custom properties dont work as expected

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/ols4#718]
See here: http://purl.obolibrary.org/obo/MONDO_0020119

<img width="581" alt="image" src="https://github.com/user-attachments/assets/b922ba87-db6b-4e69-891e-6b2dc27df7e9">

The URL is partially clickable in a wrong way.

**Comment by haideriqbal** [comment]
Thanks for reporting this @matentzn ! I'll look into it

**Comment by haideriqbal** [comment]
This has been fixed in production.
