### ISSUE TITLE
Errors generated during API testing.

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#719]
**Describe the bug**
Errors written out such as the following: 
```
{
  "error": "<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Aug 07 09:55:37 BST 2024</div><div>There was an unexpected error (type=Not Found, status=404).</div></body></html>"
}
```

**To Reproduce**
1. Run testcases
2. Run API tests
3. Compare output directories using a tool such as Meld.

The output above causes a large number of bogus differences as the date gets updated with each run and thus ends up being different from expected output.

**Expected behavior**
Add mapping for error in such a way that it will be resilient under testing.

**Comment by haideriqbal** [comment]
This has been deployed to production
