### ISSUE TITLE
OLS data dumps not updated since March 2024

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#724]
Notice that the file dates are all from March 2024 rather than the latest data release.

![image](https://github.com/user-attachments/assets/44021165-9780-456f-9c86-b4f57fa4d5b9)

This is most likely due to the data release process still coping dumps from LSF related directory rather than the Slurm directory.

**Comment by haideriqbal** [comment]
Just checked on this and we have a new path for latest data release files and its up to date.

Latest data release files are located here https://ftp.ebi.ac.uk/pub/databases/spot/ols/slurm_pipeline/latest/

![Screenshot 2024-08-20 at 20 25 16](https://github.com/user-attachments/assets/61342b3f-7e72-4c48-8b91-147a5ab52f14)

we can change the directory path if want to have latest files at `ols/latest`?

**Comment by henrietteharmse** [comment]
That sounds perfect!

**Comment by haideriqbal** [comment]
latest data dump is on ftp under ols/latest directory.
