### ISSUE TITLE
OLS4 dev is very slow

### ISSUE THREAD

**Issue by amnonkhen** [EBISPOT/ols4#726]
**Describe the bug**
As I was porting HCA to use OLS4, I started working with OLS4 dev whose response time was very long, in the order of a minute. Many of my tests timed out because of that, so I had to use OLS4 prod instead. This does not happen for all terms.

**To Reproduce**
1. search for `EDAM:0006` on [dev](https://wwwdev.ebi.ac.uk/ols4/api/search?q=EDAM:0006&exact=true&groupField=true&queryFields=obo_id) - 1min
2. search on [prod](https://www.ebi.ac.uk/ols4/api/search?q=EDAM:0006&exact=true&groupField=true&queryFields=obo_id) - 50ms

**Expected behavior**
dev should a reasonable response time

**Comment by haideriqbal** [comment]
As mentioned in https://github.com/EBISPOT/ols4/issues/727 kindly use OLS prod instance for your pipelines and processes. For the slowness of dev instances, there can be many reasons but the major one I would believe is down to the k8 cluster as for prod we have two k8 clusters serving it whereas for dev we only have one.
