### ISSUE TITLE
inconsistency between ols4 dev and prod

### ISSUE THREAD

**Issue by amnonkhen** [EBISPOT/ols4#727]
**Describe the bug**
The results for some terms are inconsistent between ols4 dev and prod. 
For example: 
**To Reproduce**
1. search for [`hancestro:0004` on dev](https://wwwdev.ebi.ac.uk/ols4/api/search?q=hancestro:0004&exact=true&groupField=true&queryFields=obo_id)
2. The 2 documents come from _foodon_ and _genepio_ ontologies
3. search for [`hancestro:0004` on prod](https://www.ebi.ac.uk/ols4/api/search?q=hancestro:0004&exact=true&groupField=true&queryFields=obo_id)
4. The 2 documents come from hancestro and genepio.

**Expected behavior**

1. `hancestro:0004` should be in _hancenstro_ ontology
2. dev and prod result should be consistent

**Comment by haideriqbal** [comment]
Hi @amnonkhen! the difference between dev and prod instances is expected as we use the dev instance for testing and is not a stable instance so I would suggest that you base your pipelines, processes etc on the prod instance because that's the one which has the latest data and is in a stable state.
