### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by ClaudeHu** [EBISPOT/ols4#740]
**Describe the bug**
The API for ontology terms from Human Phenotype Ontology was not accessible for page 360 (size=20), while page 359 and page 361 are fine.

**To Reproduce**
1. Go to https://www.ebi.ac.uk/ols4/api/ontologies/hp/terms?page=360&size=20
2. See error
![Screenshot from 2024-09-16 11-03-47](https://github.com/user-attachments/assets/17b15eab-6b7e-46c8-b712-9d89079f3623)

**Comment by haideriqbal** [comment]
Thanks for reporting this @ClaudeHu! We'll look into it

**Comment by haideriqbal** [comment]
@ClaudeHu this has been fixed in production... please let us know if you face this issue again.

**Comment by corinabioinformatic** [comment]
@haideriqbal when I click on the link I get this message

<img width="675" alt="image" src="https://github.com/user-attachments/assets/d0b6feef-3010-4fb6-b0ac-8a1b614a70e4">

**Comment by haideriqbal** [comment]
@corinabioinformatic there was a network hiccup... OLS is back up now :)

**Comment by corinabioinformatic** [comment]
It was back for a bit but now again failed 
<img width="883" alt="image" src="https://github.com/user-attachments/assets/74498016-fc48-4e76-acc7-88ce5cf6eb92">

UPDATE: Now is back :)

**Comment by ClaudeHu** [comment]
[Page 1130 of HP(size = 20)](https://www.ebi.ac.uk/ols4/api/ontologies/hp/terms?page=1130&size=20) returns null.

**Comment by haideriqbal** [comment]
@ClaudeHu would need to investigate that... setting size to 19, 21 onwards returns normal... but will check why size 20 fails on that page

**Comment by haideriqbal** [comment]
@ClaudeHu this has been fixed... have tried pages from 1125 till 1135 I don't see the error anymore... please try again and let me know if you still face the issue..

**Comment by haideriqbal** [comment]
closing this as not facing this issue anymore... feel free to reopen the issue if you face the error again

**Comment by ClaudeHu** [comment]
[Page 1274](https://www.ebi.ac.uk/ols4/api/ontologies/hp/terms?page=1274&size=20) has that error again @haideriqbal
