### ISSUE TITLE
New ontology addition request for HBA and DHBA

### ISSUE THREAD

**Issue by hkir-dev** [EBISPOT/ols4#744]
Can you please add Human Brain Atlas Ontology (HBA) and Developing Human Brain Atlas Ontology (DHBA) ontologies to OLS?

Excel sheets are as follows:
- [HBA New OLS ontology request.xlsx](https://github.com/user-attachments/files/17057598/HBA.New.OLS.ontology.request.xlsx)
- [DHBA New OLS ontology request.xlsx](https://github.com/user-attachments/files/17057607/DHBA.New.OLS.ontology.request.xlsx)

**Comment by Felipe-Rafael-Rosa** [comment]
maybe this will help
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by haideriqbal** [comment]
why is a c compiler needed @Felipe-Rafael-Rosa ?

**Comment by hkir-dev** [comment]
> why is a c compiler needed @Felipe-Rafael-Rosa ?

This can be a spam. Please don't download that link.

**Comment by haideriqbal** [comment]
yup thought so didn't click it

**Comment by haideriqbal** [comment]
Both of the ontologies are now in OLS
