### ISSUE TITLE
Request to add AddictO to the EBI OLS instance 

### ISSUE THREAD

**Issue by b-gehrke** [EBISPOT/ols4#751]
Can you please add the addiction ontology (AddictO) to the EBI-OLS instance?

Here is the excel sheet with the details: [AddictO request.xlsx](https://github.com/user-attachments/files/17209973/New.OLS.ontology.request.xlsx)

**Comment by haideriqbal** [comment]
Addicto is now live in OLS

https://www.ebi.ac.uk/ols4/ontologies/addicto
