### ISSUE TITLE
Blank page accessing term biolink functional association

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#758]
https://www.ebi.ac.uk/ols4/ontologies/biolink/classes/https%253A%252F%252Fw3id.org%252Fbiolink%252Fvocab%252FFunctionalAssociation

**Comment by haideriqbal** [comment]
![Screenshot 2024-10-14 at 12 34 30](https://github.com/user-attachments/assets/00eb4d4a-f069-486f-831d-3f3f2f468cbb)

seeing this in the console... seems like a data problem that needs further investigation. I'll let you know then.

**Comment by haideriqbal** [comment]
fixed in production.
![Screenshot 2024-11-26 at 12 31 37](https://github.com/user-attachments/assets/1733ec2e-c5a0-4ad6-99c9-d4ee8d8dc979)
