### ISSUE TITLE
Set affinities for Neo4j and Solr 

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/ols4#764]
**Describe the bug**
Currently K8s config assumes setting affinities for PVCs are sufficient - i.e., that K8s is smart enough to determine that the solr and neo4j deployments need to adhere to these affinities as well due to their dependencies. However, we had an occurrence on our dev environment where, according to infrastructure, these affinities were not taken into consideration for the solr and neo4j deployments, which resulted in outage of the dev environment.

To ensure that this issue does not arise on our cluster, we should set these affinities for the neo4j and solr deployments.

**Comment by haideriqbal** [comment]
updated in production and dev.
