### ISSUE TITLE
Request to Add Lifestyle Factors Ontology (LSFO) to OLS

### ISSUE THREAD

**Issue by EsmaeilNourani** [EBISPOT/ols4#806]
We would like to request the addition of the Lifestyle Factors Ontology (LSFO) to the Ontology Lookup Service (OLS).

In this ontology, we defined nine distinct categories that encompass various aspects of lifestyle factors (LSFs), creating a unified Lifestyle Factors Ontology (LSFO) across these categories. Within the context of lifestyle, we have identified nine categories that can collectively describe all LSFs, namely: 1-Nutrition, a category that covers different branches such as dietary habits, food groups, food processing and preparation, macronutrients, and micronutrients, among others. 2-Socioeconomic factors, which includes social and economic conditions such as income, wealth, education and socioeconomic status. 3-Environmental exposures, includes exposure to various environmental factors, such as air pollution, water quality, and workplace hazards, that can impact an individual’s health. 4-Substance use, covers concepts such as smoking, as well as illicit drug use. 5-Physical activities, includes regular exercise and physically demanding activities like leisure time, occupational, and household physical activities. 6-Non-physical leisure time activities, describes any activity an individual might engage in during their free time that is not a physical activity. 7-Personal care products and cosmetic procedures, covers activities related to hygiene, use of cosmetic and cleaning products as well as invasive procedures that people undergo to improve their appearance, such as cosmetic surgery. 8-Sleep, covers sleep quality, stages, and habits. 9-Mental health practices, includes the behaviors and habits related to maintaining good mental health and emotional well-being such as meditation, and psychotherapy.

A completed spreadsheet with all the required information is attached for your review. Please let us know if additional details or adjustments are needed.

Thank you for your consideration!

[New OLS ontology request.xlsx](https://github.com/user-attachments/files/17879736/New.OLS.ontology.request.xlsx)

**Comment by henrietteharmse** [comment]
Hi @EsmaeilNourani, thank you for considering adding your ontology to OLS and filling out the form. 

There are 2 issues though, that you will need to address before your ontology can be loaded into OLS:

1. We need a purl for your ontology. Currently you have provided: https://data.bioontology.org/ontologies/LSFO/submissions/1/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb, which not a permanent. Whenever you do a new upload to BioPortal, the purl in OLS will need to be changed. I suggest you a github repo for your ontology and have the latest version of your available there. This is indeed where most ontologies in OLS are loaded from.

2.  Currently your ontology is in .obo format. OLS does not load .obo files. As for why OLS does not support .obo, see [here](https://github.com/EBISPOT/ols4/wiki/Why-does-OLS-not-support-.obo-format%3F) for details. To convert your ontology to `RDF/XML` you can use either Protege [desktop](https://protege.stanford.edu/software.php#desktop-protege) or the ROBOT [convert command](http://robot.obolibrary.org/convert) to achieve this. You can load your ontology into Protege to check it is rendering as you will expect.

Then, lastly I noted that your stated that your ontology is an OBO Foundry ontology. That is actually incorrect. Your ontology is in OBO format, but it is not an OBO Foundry ontology. If you want your ontology to be an OBO Foundry ontology, reach out to the OBO Foundry to have your ontology added. The advantage of this is that they can give guidance wrt processes for maintaining your ontology and when your ontology is added to the OBO Foundy, it will appear automatically in OLS. However, OLS does not require your ontology to be an OBO Foundry ontology to be loaded into OLS. I mainly wanted to point out that adding your ontology to the OBO Foundry may be something you want to explore.

**Comment by EsmaeilNourani** [comment]
Thanks @henrietteharmse for your detailed feedback and for considering adding our ontology to OLS.

We have addressed the issues you highlighted:

- **PURL**: The latest version of the ontology in OWL format is hosted on GitHub, and the link has been provided in the updated spreadsheet.

Additionally, the `is_foundry` field has been corrected to reflect that the ontology is not part of the OBO Foundry.

Please let us know if there are any additional updates needed.
[New OLS ontology request.xlsx](https://github.com/user-attachments/files/17905209/New.OLS.ontology.request.xlsx)

**Comment by henrietteharmse** [comment]
Wonderful! Will get this sorted for you ASAP @EsmaeilNourani!

**Comment by haideriqbal** [comment]
Ontology is live in OLS now! https://www.ebi.ac.uk/ols4/ontologies/lifestylefactors

closing this issue
