### ISSUE TITLE
Request to add SCO to OLS

### ISSUE THREAD

**Issue by gioUbbiali** [EBISPOT/ols4#812]
Good evening,
I gently ask if my Sustainability Core Ontology (SCO) may be added to OLS. I attached the spreadsheet filled out with details regarding SCO.  I remain at your disposal for clarifications and if additional information is required.
Sincerely,
Giorgio Ubbiali
[New OLS ontology request. Ubbiali.xlsx](https://github.com/user-attachments/files/17996597/New.OLS.ontology.request.Ubbiali.xlsx)

**Comment by haideriqbal** [comment]
@gioUbbiali I see in your ontology sheet that you have referred the ontology URL to your personal github and the ontology purl also refers to your personal repo. Is this ontology your personal project or is it related to any organisation and would be maintained by that organisation going forward?

Also, I noticed that the ontology is not in RDF/XML format either, for OLS to process the ontology it needs to be in RDF format.

**Comment by gioUbbiali** [comment]
Dear @haideriqbal,
I developed this resource as part of my PhD project that involves different partners. I refer you to the SCO repo. I will maintain the resource. 
You’re about the ontology format. Here is the spreadsheet with reference to the rdf file.
Best,
Giorgio Ubbiali
[New OLS ontology request. Ubbiali.xlsx](https://github.com/user-attachments/files/18041895/New.OLS.ontology.request.Ubbiali.xlsx)

**Comment by haideriqbal** [comment]
Hi @gioUbbiali, after careful consideration amongst our team, I am sorry to let you know that we cannot accommodate this request. We have concerns regarding the long-term maintainability of this ontology and we encourage you to consider listing your ontology with the [OBO Foundry](http://www.obofoundry.org/), which might better align with your needs.

We appreciate your understanding and thank you for your contributions to the ontology community. Please don't hesitate to reach out if you have further questions or need assistance with other aspects of OLS.

**Comment by matentzn** [comment]
@gioUbbiali, just to be clear - if you get into OBO Foundry, you automatically get into OLS as well! So you will get some expert feedback from your peers as an additional bonus!

**Comment by gioUbbiali** [comment]
Dear @haideriqbal and @matentzn 
thank you for considering SCO for inclusion. I assure you that there are already long-term plans to implement and maintain this resource. I will check out for possible inclusion in the OBO-Foundry.
Best,
Giorgio

**Comment by haideriqbal** [comment]
closing this issue now! if anything changes feel free to reopen this issue.
