### ISSUE TITLE
Implement download buttons for ontologies where allowDownload: true

### ISSUE THREAD

**Issue by jamesamcl** [EBISPOT/ols4#90]
The button will simply be a link to the PURL from the ontology config.

**Comment by jamesamcl** [comment]
This should also go on the actions column in the ontology list

**Comment by rombaum** [comment]
Hi @udp,

I have three questions or thoughts in this context 

1. How is ensured that a user will get the loaded version of an ontology via the PURL? E.g. it could be that the .owl-file at the PURL will change between indexing for ols4 and clicking on the download?
2. What will happen if allowDownload is set to false. Will the PURL information automatically hidden from the API?
3. Will that approach also work for a local loaded ontology which use the scheme file:///?

**Comment by jamesamcl** [comment]
1. Then you would get the latest version. However OLS4 will be updated nightly, so it would be at most 24 hours newer which I don't think is a major concern.
2. Yes
3. No it would not, which is a good point. Though we host very few such ontologies at EBI.

This hasn't been implemented yet so it's still possible we could host the loaded owl files in OLS instead, depending on use cases.

**Comment by jamesamcl** [comment]
@serjoshua As it is I'm not sure the purl info is actually hidden from the API when allow download is false. We need to skip ontology_purl when writing the json in rdf2json if allow_download = false.

**Comment by serjoshua** [comment]
This has been resolved via #526. To disable Download button, just add `"allowDownload": false` in the JSON configuration of any ontology.
